// Auto-generated by langue. Do not edit.
// Regenerate: scripts/gen_langue.sh

use super::SyntaxKind;
use super::{SyntaxNode, SyntaxElement, LosslessToken};

pub trait AstNode<'a>: Sized {
    fn cast(node: &'a SyntaxNode) -> Option<Self>;
    fn syntax(&self) -> &'a SyntaxNode;
}

pub struct File<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for File<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::FILE).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> File<'a> {
    pub fn items(&self) -> impl Iterator<Item = Item<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => Item::cast(n),
            _ => None,
        })
    }
}

pub enum Item<'a> {
    ExternTypeDecl(ExternTypeDecl<'a>),
    ExternFnDecl(ExternFnDecl<'a>),
    DataDecl(DataDecl<'a>),
    CapDecl(CapDecl<'a>),
    FnDecl(FnDecl<'a>),
    UseDecl(UseDecl<'a>),
    ImplDecl(ImplDecl<'a>),
}

impl<'a> AstNode<'a> for Item<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        None
            .or_else(|| ExternTypeDecl::cast(node).map(Self::ExternTypeDecl))
            .or_else(|| ExternFnDecl::cast(node).map(Self::ExternFnDecl))
            .or_else(|| DataDecl::cast(node).map(Self::DataDecl))
            .or_else(|| CapDecl::cast(node).map(Self::CapDecl))
            .or_else(|| FnDecl::cast(node).map(Self::FnDecl))
            .or_else(|| UseDecl::cast(node).map(Self::UseDecl))
            .or_else(|| ImplDecl::cast(node).map(Self::ImplDecl))
    }
    fn syntax(&self) -> &'a SyntaxNode {
        match self {
            Self::ExternTypeDecl(n) => n.syntax(),
            Self::ExternFnDecl(n) => n.syntax(),
            Self::DataDecl(n) => n.syntax(),
            Self::CapDecl(n) => n.syntax(),
            Self::FnDecl(n) => n.syntax(),
            Self::UseDecl(n) => n.syntax(),
            Self::ImplDecl(n) => n.syntax(),
        }
    }
}

pub struct ExternTypeDecl<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ExternTypeDecl<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::EXTERN_TYPE_DECL).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ExternTypeDecl<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn extern_as(&self) -> Option<ExternAs<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ExternAs::cast(n),
            _ => None,
        })
    }
}

pub struct ExternFnDecl<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ExternFnDecl<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::EXTERN_FN_DECL).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ExternFnDecl<'a> {
    pub fn inline(&self) -> Option<InlineHint<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => InlineHint::cast(n),
            _ => None,
        })
    }
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn param_list(&self) -> Option<ParamList<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ParamList::cast(n),
            _ => None,
        })
    }
    pub fn return_ann(&self) -> Option<ReturnAnn<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ReturnAnn::cast(n),
            _ => None,
        })
    }
    pub fn cap_annotation(&self) -> Option<CapAnnotation<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => CapAnnotation::cast(n),
            _ => None,
        })
    }
    pub fn extern_as(&self) -> Option<ExternAs<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ExternAs::cast(n),
            _ => None,
        })
    }
}

pub struct ExternAs<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ExternAs<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::EXTERN_AS).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ExternAs<'a> {
    pub fn value(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::STRING_LIT => Some(t),
            _ => None,
        })
    }
}

pub struct InlineHint<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for InlineHint<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::INLINE_HINT).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

pub struct DataDecl<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for DataDecl<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::DATA_DECL).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> DataDecl<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn generic_params(&self) -> Option<GenericParams<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => GenericParams::cast(n),
            _ => None,
        })
    }
    pub fn variants(&self) -> impl Iterator<Item = Variant<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => Variant::cast(n),
            _ => None,
        })
    }
}

pub struct Variant<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for Variant<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::VARIANT).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> Variant<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn variant_fields(&self) -> Option<VariantFields<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => VariantFields::cast(n),
            _ => None,
        })
    }
}

pub struct VariantFields<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for VariantFields<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::VARIANT_FIELDS).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> VariantFields<'a> {
    pub fn fields(&self) -> impl Iterator<Item = TypeExpr<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => TypeExpr::cast(n),
            _ => None,
        })
    }
}

pub struct CapDecl<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for CapDecl<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::CAP_DECL).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> CapDecl<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn operations(&self) -> impl Iterator<Item = OperationDecl<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => OperationDecl::cast(n),
            _ => None,
        })
    }
}

pub struct OperationDecl<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for OperationDecl<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::OPERATION_DECL).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> OperationDecl<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn param_list(&self) -> Option<ParamList<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ParamList::cast(n),
            _ => None,
        })
    }
    pub fn return_ann(&self) -> Option<ReturnAnn<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ReturnAnn::cast(n),
            _ => None,
        })
    }
}

pub struct FnDecl<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for FnDecl<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::FN_DECL).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> FnDecl<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn generic_params(&self) -> Option<GenericParams<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => GenericParams::cast(n),
            _ => None,
        })
    }
    pub fn param_list(&self) -> Option<ParamList<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ParamList::cast(n),
            _ => None,
        })
    }
    pub fn return_ann(&self) -> Option<ReturnAnn<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ReturnAnn::cast(n),
            _ => None,
        })
    }
    pub fn cap_annotation(&self) -> Option<CapAnnotation<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => CapAnnotation::cast(n),
            _ => None,
        })
    }
    pub fn body(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
}

pub struct UseDecl<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for UseDecl<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::USE_DECL).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> UseDecl<'a> {
    pub fn path(&self) -> Option<UsePath<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => UsePath::cast(n),
            _ => None,
        })
    }
}

pub struct UsePath<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for UsePath<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::USE_PATH).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> UsePath<'a> {
    pub fn segments(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
}

pub struct UseTree<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for UseTree<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::USE_TREE).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> UseTree<'a> {
    pub fn names(&self) -> impl Iterator<Item = &'a LosslessToken> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
}

pub struct ImplDecl<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ImplDecl<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::IMPL_DECL).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ImplDecl<'a> {
    pub fn generic_params(&self) -> Option<GenericParams<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => GenericParams::cast(n),
            _ => None,
        })
    }
    pub fn impl_name(&self) -> Option<ImplName<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ImplName::cast(n),
            _ => None,
        })
    }
    pub fn target(&self) -> Option<TypeExpr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => TypeExpr::cast(n),
            _ => None,
        })
    }
    pub fn impl_cap(&self) -> Option<ImplCap<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ImplCap::cast(n),
            _ => None,
        })
    }
    pub fn methods(&self) -> impl Iterator<Item = ImplMethod<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => ImplMethod::cast(n),
            _ => None,
        })
    }
}

pub struct ImplName<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ImplName<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::IMPL_NAME).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ImplName<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
}

pub struct ImplCap<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ImplCap<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::IMPL_CAP).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ImplCap<'a> {
    pub fn cap(&self) -> Option<TypeExpr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => TypeExpr::cast(n),
            _ => None,
        })
    }
}

pub struct ImplMethod<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ImplMethod<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::IMPL_METHOD).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ImplMethod<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn param_list(&self) -> Option<ParamList<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ParamList::cast(n),
            _ => None,
        })
    }
    pub fn return_ann(&self) -> Option<ReturnAnn<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ReturnAnn::cast(n),
            _ => None,
        })
    }
    pub fn body(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
}

pub struct GenericParams<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for GenericParams<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::GENERIC_PARAMS).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> GenericParams<'a> {
    pub fn params(&self) -> impl Iterator<Item = &'a LosslessToken> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
}

pub struct ParamList<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ParamList<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::PARAM_LIST).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ParamList<'a> {
    pub fn params(&self) -> impl Iterator<Item = Param<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => Param::cast(n),
            _ => None,
        })
    }
}

pub struct Param<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for Param<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::PARAM).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> Param<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn ty(&self) -> Option<TypeExpr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => TypeExpr::cast(n),
            _ => None,
        })
    }
}

pub struct ReturnAnn<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ReturnAnn<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::RETURN_ANN).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ReturnAnn<'a> {
    pub fn ty(&self) -> Option<TypeExpr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => TypeExpr::cast(n),
            _ => None,
        })
    }
}

pub struct CapAnnotation<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for CapAnnotation<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::CAP_ANNOTATION).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> CapAnnotation<'a> {
    pub fn caps(&self) -> impl Iterator<Item = TypeExpr<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => TypeExpr::cast(n),
            _ => None,
        })
    }
}

pub struct TypeExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for TypeExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::TYPE_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> TypeExpr<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn generic_args(&self) -> Option<GenericArgs<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => GenericArgs::cast(n),
            _ => None,
        })
    }
}

pub struct GenericArgs<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for GenericArgs<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::GENERIC_ARGS).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> GenericArgs<'a> {
    pub fn args(&self) -> impl Iterator<Item = TypeExpr<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => TypeExpr::cast(n),
            _ => None,
        })
    }
}

pub enum Expr<'a> {
    IdentExpr(IdentExpr<'a>),
    StringExpr(StringExpr<'a>),
    NumberExpr(NumberExpr<'a>),
    LetExpr(LetExpr<'a>),
    ProduceExpr(ProduceExpr<'a>),
    ThunkExpr(ThunkExpr<'a>),
    ForceExpr(ForceExpr<'a>),
    MatchExpr(MatchExpr<'a>),
    CallExpr(CallExpr<'a>),
    MemberExpr(MemberExpr<'a>),
    PerformExpr(PerformExpr<'a>),
    HandleExpr(HandleExpr<'a>),
    BundleExpr(BundleExpr<'a>),
    AnnExpr(AnnExpr<'a>),
    ErrorExpr(ErrorExpr<'a>),
}

impl<'a> AstNode<'a> for Expr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        None
            .or_else(|| IdentExpr::cast(node).map(Self::IdentExpr))
            .or_else(|| StringExpr::cast(node).map(Self::StringExpr))
            .or_else(|| NumberExpr::cast(node).map(Self::NumberExpr))
            .or_else(|| LetExpr::cast(node).map(Self::LetExpr))
            .or_else(|| ProduceExpr::cast(node).map(Self::ProduceExpr))
            .or_else(|| ThunkExpr::cast(node).map(Self::ThunkExpr))
            .or_else(|| ForceExpr::cast(node).map(Self::ForceExpr))
            .or_else(|| MatchExpr::cast(node).map(Self::MatchExpr))
            .or_else(|| CallExpr::cast(node).map(Self::CallExpr))
            .or_else(|| MemberExpr::cast(node).map(Self::MemberExpr))
            .or_else(|| PerformExpr::cast(node).map(Self::PerformExpr))
            .or_else(|| HandleExpr::cast(node).map(Self::HandleExpr))
            .or_else(|| BundleExpr::cast(node).map(Self::BundleExpr))
            .or_else(|| AnnExpr::cast(node).map(Self::AnnExpr))
            .or_else(|| ErrorExpr::cast(node).map(Self::ErrorExpr))
    }
    fn syntax(&self) -> &'a SyntaxNode {
        match self {
            Self::IdentExpr(n) => n.syntax(),
            Self::StringExpr(n) => n.syntax(),
            Self::NumberExpr(n) => n.syntax(),
            Self::LetExpr(n) => n.syntax(),
            Self::ProduceExpr(n) => n.syntax(),
            Self::ThunkExpr(n) => n.syntax(),
            Self::ForceExpr(n) => n.syntax(),
            Self::MatchExpr(n) => n.syntax(),
            Self::CallExpr(n) => n.syntax(),
            Self::MemberExpr(n) => n.syntax(),
            Self::PerformExpr(n) => n.syntax(),
            Self::HandleExpr(n) => n.syntax(),
            Self::BundleExpr(n) => n.syntax(),
            Self::AnnExpr(n) => n.syntax(),
            Self::ErrorExpr(n) => n.syntax(),
        }
    }
}

pub struct IdentExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for IdentExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::IDENT_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> IdentExpr<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
}

pub struct StringExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for StringExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::STRING_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> StringExpr<'a> {
    pub fn value(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::STRING_LIT => Some(t),
            _ => None,
        })
    }
}

pub struct NumberExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for NumberExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::NUMBER_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> NumberExpr<'a> {
    pub fn value(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::NUMBER_LIT => Some(t),
            _ => None,
        })
    }
}

pub struct LetExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for LetExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::LET_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> LetExpr<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn value(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
    pub fn body(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
}

pub struct ProduceExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ProduceExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::PRODUCE_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ProduceExpr<'a> {
    pub fn value(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
}

pub struct ThunkExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ThunkExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::THUNK_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ThunkExpr<'a> {
    pub fn body(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
}

pub struct ForceExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ForceExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::FORCE_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> ForceExpr<'a> {
    pub fn expr(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
}

pub struct MatchExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for MatchExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::MATCH_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> MatchExpr<'a> {
    pub fn scrutinee(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
    pub fn arms(&self) -> impl Iterator<Item = MatchArm<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => MatchArm::cast(n),
            _ => None,
        })
    }
}

pub struct MatchArm<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for MatchArm<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::MATCH_ARM).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> MatchArm<'a> {
    pub fn pattern(&self) -> Option<Pattern<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Pattern::cast(n),
            _ => None,
        })
    }
    pub fn body(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
}

pub struct CallExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for CallExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::CALL_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> CallExpr<'a> {
    pub fn callee(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
    pub fn args(&self) -> impl Iterator<Item = Expr<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
}

pub struct MemberExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for MemberExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::MEMBER_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> MemberExpr<'a> {
    pub fn object(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
    pub fn member(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
}

pub struct PerformExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for PerformExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::PERFORM_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> PerformExpr<'a> {
    pub fn cap(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
}

pub struct HandleExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for HandleExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::HANDLE_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> HandleExpr<'a> {
    pub fn cap(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn type_args(&self) -> Option<GenericArgs<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => GenericArgs::cast(n),
            _ => None,
        })
    }
    pub fn handler(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
    pub fn body(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
}

pub struct BundleExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for BundleExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::BUNDLE_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> BundleExpr<'a> {
    pub fn entries(&self) -> impl Iterator<Item = BundleEntry<'a>> + 'a {
        self.0.children.iter().filter_map(|c| match c {
            SyntaxElement::Node(n) => BundleEntry::cast(n),
            _ => None,
        })
    }
}

pub struct BundleEntry<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for BundleEntry<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::BUNDLE_ENTRY).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> BundleEntry<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
    pub fn param_list(&self) -> Option<ParamList<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => ParamList::cast(n),
            _ => None,
        })
    }
    pub fn body(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
}

pub struct AnnExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for AnnExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::ANN_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> AnnExpr<'a> {
    pub fn expr(&self) -> Option<Expr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => Expr::cast(n),
            _ => None,
        })
    }
    pub fn ty(&self) -> Option<TypeExpr<'a>> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Node(n) => TypeExpr::cast(n),
            _ => None,
        })
    }
}

pub struct ErrorExpr<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for ErrorExpr<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::ERROR_EXPR).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

pub enum Pattern<'a> {
    VariantPattern(VariantPattern<'a>),
    BindPattern(BindPattern<'a>),
    WildcardPattern(WildcardPattern<'a>),
}

impl<'a> AstNode<'a> for Pattern<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        None
            .or_else(|| VariantPattern::cast(node).map(Self::VariantPattern))
            .or_else(|| BindPattern::cast(node).map(Self::BindPattern))
            .or_else(|| WildcardPattern::cast(node).map(Self::WildcardPattern))
    }
    fn syntax(&self) -> &'a SyntaxNode {
        match self {
            Self::VariantPattern(n) => n.syntax(),
            Self::BindPattern(n) => n.syntax(),
            Self::WildcardPattern(n) => n.syntax(),
        }
    }
}

pub struct VariantPattern<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for VariantPattern<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::VARIANT_PATTERN).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> VariantPattern<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
}

pub struct BindPattern<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for BindPattern<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::BIND_PATTERN).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

impl<'a> BindPattern<'a> {
    pub fn name(&self) -> Option<&'a LosslessToken> {
        self.0.children.iter().find_map(|c| match c {
            SyntaxElement::Token(t) if t.kind == SyntaxKind::IDENT => Some(t),
            _ => None,
        })
    }
}

pub struct WildcardPattern<'a>(pub(crate) &'a SyntaxNode);

impl<'a> AstNode<'a> for WildcardPattern<'a> {
    fn cast(node: &'a SyntaxNode) -> Option<Self> {
        (node.kind == SyntaxKind::WILDCARD_PATTERN).then(|| Self(node))
    }
    fn syntax(&self) -> &'a SyntaxNode { self.0 }
}

