// Auto-generated by langue. Do not edit.
// Regenerate: scripts/gen_langue.sh

use lumo_lexer::{lex_lossless, Keyword, LosslessTokenKind as LexKind};
use lumo_span::Span;

use crate::syntax_kind::SyntaxKind;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseError {
    pub span: Span,
    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LosslessToken {
    pub kind: SyntaxKind,
    pub span: Span,
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SyntaxElement {
    Node(Box<SyntaxNode>),
    Token(LosslessToken),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SyntaxNode {
    pub kind: SyntaxKind,
    pub span: Span,
    pub children: Vec<SyntaxElement>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseOutput {
    pub root: SyntaxNode,
    pub errors: Vec<ParseError>,
}

pub fn parse(source: &str) -> ParseOutput {
    let lexed = lex_lossless(source);
    let mut p = Parser { tokens: lexed.tokens, index: 0, errors: Vec::new() };
    let root = p.parse_file();
    ParseOutput { root, errors: p.errors }
}

pub fn node_text(node: &SyntaxNode) -> String {
    let mut out = String::new();
    write_node_text(node, &mut out);
    out
}

fn write_node_text(node: &SyntaxNode, out: &mut String) {
    for child in &node.children {
        match child {
            SyntaxElement::Node(n) => write_node_text(n, out),
            SyntaxElement::Token(t) => out.push_str(&t.text),
        }
    }
}

fn node_from_children(kind: SyntaxKind, children: Vec<SyntaxElement>) -> SyntaxNode {
    let span = children_span(&children);
    SyntaxNode { kind, span, children }
}

fn children_span(children: &[SyntaxElement]) -> Span {
    let start = children.iter().find_map(|c| match c {
        SyntaxElement::Token(t) => Some(t.span.start),
        SyntaxElement::Node(n) => if n.children.is_empty() { None } else { Some(n.span.start) },
    }).unwrap_or(0);
    let end = children.iter().rev().find_map(|c| match c {
        SyntaxElement::Token(t) => Some(t.span.end),
        SyntaxElement::Node(n) => if n.children.is_empty() { None } else { Some(n.span.end) },
    }).unwrap_or(0);
    Span::new(start, end)
}

fn lexer_token_to_lst(t: lumo_lexer::LosslessToken) -> LosslessToken {
    LosslessToken { kind: lexer_kind_to_syntax_kind(&t.kind, &t.text), span: t.span, text: t.text }
}

fn lexer_kind_to_syntax_kind(kind: &LexKind, text: &str) -> SyntaxKind {
    match kind {
        LexKind::Ident => SyntaxKind::IDENT,
        LexKind::StringLit => SyntaxKind::STRING_LIT,
        LexKind::NumberLit => SyntaxKind::NUMBER_LIT,
        LexKind::Whitespace => SyntaxKind::WHITESPACE,
        LexKind::Newline => SyntaxKind::NEWLINE,
        LexKind::Unknown => SyntaxKind::UNKNOWN,
        LexKind::Keyword(kw) => match kw {
            Keyword::Bundle => SyntaxKind::BUNDLE_KW,
            Keyword::Cap => SyntaxKind::CAP_KW,
            Keyword::Data => SyntaxKind::DATA_KW,
            Keyword::Else => SyntaxKind::ELSE_KW,
            Keyword::Extern => SyntaxKind::EXTERN_KW,
            Keyword::Fn => SyntaxKind::FN_KW,
            Keyword::For => SyntaxKind::FOR_KW,
            Keyword::Force => SyntaxKind::FORCE_KW,
            Keyword::Handle => SyntaxKind::HANDLE_KW,
            Keyword::If => SyntaxKind::IF_KW,
            Keyword::Impl => SyntaxKind::IMPL_KW,
            Keyword::In => SyntaxKind::IN_KW,
            Keyword::Let => SyntaxKind::LET_KW,
            Keyword::Match => SyntaxKind::MATCH_KW,
            Keyword::Perform => SyntaxKind::PERFORM_KW,
            Keyword::Thunk => SyntaxKind::THUNK_KW,
            Keyword::Type => SyntaxKind::TYPE_KW,
            Keyword::Use => SyntaxKind::USE_KW,
            _ => SyntaxKind::UNKNOWN,
        },
        LexKind::Symbol(_) => SyntaxKind::from_symbol(text).unwrap_or(SyntaxKind::UNKNOWN),
    }
}

struct Parser {
    tokens: Vec<lumo_lexer::LosslessToken>,
    index: usize,
    errors: Vec<ParseError>,
}

impl Parser {
    fn eof(&self) -> bool { self.index >= self.tokens.len() }
    fn current(&self) -> Option<&lumo_lexer::LosslessToken> { self.tokens.get(self.index) }
    fn bump(&mut self) -> Option<LosslessToken> {
        let token = self.tokens.get(self.index).cloned();
        if token.is_some() { self.index += 1; }
        token.map(lexer_token_to_lst)
    }
    fn is_trivia_lex(kind: &LexKind) -> bool {
        matches!(kind, LexKind::Whitespace | LexKind::Newline)
    }
    fn at_trivia(&self) -> bool {
        self.current().map(|t| Self::is_trivia_lex(&t.kind)).unwrap_or(false)
    }
    fn skip_trivia_into(&mut self, children: &mut Vec<SyntaxElement>) {
        while self.at_trivia() { children.push(SyntaxElement::Token(self.bump().unwrap())); }
    }
    fn peek_non_trivia_token(&self, n: usize) -> Option<&lumo_lexer::LosslessToken> {
        let mut count = 0; let mut i = self.index;
        while i < self.tokens.len() {
            let tok = &self.tokens[i];
            if !Self::is_trivia_lex(&tok.kind) {
                if count == n { return Some(tok); }
                count += 1;
            }
            i += 1;
        }
        None
    }
    fn at_keyword(&self, kw: Keyword) -> bool {
        matches!(self.current().map(|t| &t.kind), Some(LexKind::Keyword(actual)) if *actual == kw)
    }
    fn at_non_trivia_keyword(&self, kw: Keyword) -> bool {
        matches!(self.peek_non_trivia_token(0).map(|t| &t.kind), Some(LexKind::Keyword(actual)) if *actual == kw)
    }
    fn at_non_trivia_symbol(&self, text: &str) -> bool {
        self.peek_non_trivia_token(0).map(|t| t.text.as_str()) == Some(text)
    }
    fn at_non_trivia_ident(&self) -> bool {
        matches!(self.peek_non_trivia_token(0).map(|t| &t.kind), Some(LexKind::Ident))
    }
    fn at_non_trivia_string_lit(&self) -> bool {
        matches!(self.peek_non_trivia_token(0).map(|t| &t.kind), Some(LexKind::StringLit))
    }
    fn at_non_trivia_number_lit(&self) -> bool {
        matches!(self.peek_non_trivia_token(0).map(|t| &t.kind), Some(LexKind::NumberLit))
    }
    fn at_non_trivia_name(&self) -> bool {
        matches!(self.peek_non_trivia_token(0).map(|t| &t.kind), Some(LexKind::Ident) | Some(LexKind::Keyword(_)))
    }
    fn expect_name(&mut self, children: &mut Vec<SyntaxElement>) {
        self.skip_trivia_into(children);
        if self.at_non_trivia_name() { children.push(SyntaxElement::Token(self.bump().unwrap())); }
        else { self.error_here("expected identifier"); }
    }
    fn at_non_trivia_ident_text(&self, text: &str) -> bool {
        matches!(self.peek_non_trivia_token(0), Some(tok) if matches!(tok.kind, LexKind::Ident) && tok.text == text)
    }
    fn at_ident(&self) -> bool {
        matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident))
    }
    fn at_symbol_text(&self, text: &str) -> bool {
        self.current().map(|t| t.text.as_str()) == Some(text)
    }
    fn at_trivia_or_unknown(&self) -> bool {
        self.current().map(|t| matches!(t.kind, LexKind::Whitespace | LexKind::Newline | LexKind::Unknown)).unwrap_or(false)
    }
    fn error_here(&mut self, message: &str) {
        let span = self.current().map(|t| t.span).unwrap_or(Span::new(0, 0));
        self.errors.push(ParseError { span, message: message.to_owned() });
    }
    fn expect_keyword(&mut self, kw: Keyword, children: &mut Vec<SyntaxElement>) {
        self.skip_trivia_into(children);
        if self.at_keyword(kw) { children.push(SyntaxElement::Token(self.bump().unwrap())); }
        else { self.error_here("expected keyword"); }
    }
    fn expect_symbol(&mut self, sym: &str, children: &mut Vec<SyntaxElement>) {
        self.skip_trivia_into(children);
        if self.at_symbol_text(sym) { children.push(SyntaxElement::Token(self.bump().unwrap())); }
        else { self.error_here(&format!("expected '{}'", sym)); }
    }
    fn expect_ident(&mut self, children: &mut Vec<SyntaxElement>) {
        self.skip_trivia_into(children);
        if self.at_ident() { children.push(SyntaxElement::Token(self.bump().unwrap())); }
        else { self.error_here("expected identifier"); }
    }
}

impl Parser {
    fn can_parse_file(&self) -> bool { false }
    fn parse_file(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        while !self.eof() {
            self.skip_trivia_into(&mut children);
            if self.eof() { break; }
            if self.can_parse_item() {
                children.push(SyntaxElement::Node(Box::new(self.parse_item())));
            } else {
                children.push(SyntaxElement::Node(Box::new(
                    node_from_children(SyntaxKind::ERROR, vec![SyntaxElement::Token(self.bump().unwrap())])
                )));
            }
        }
        node_from_children(SyntaxKind::FILE, children)
    }

    fn can_parse_item(&self) -> bool { self.at_non_trivia_symbol("#") || self.can_parse_item_body() }
    fn parse_item(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        while self.can_parse_attribute() {
            children.push(SyntaxElement::Node(Box::new(self.parse_attribute())));
        }
        children.push(SyntaxElement::Node(Box::new(self.parse_item_body())));
        node_from_children(SyntaxKind::ITEM, children)
    }

    fn can_parse_item_body(&self) -> bool { self.can_parse_extern_decl() || self.can_parse_data_decl() || self.can_parse_cap_decl() || self.can_parse_fn_decl() || self.can_parse_use_decl() || self.can_parse_impl_decl() }
    fn parse_item_body(&mut self) -> SyntaxNode {
        if self.can_parse_extern_decl() { return self.parse_extern_decl(); }
        if self.can_parse_data_decl() { return self.parse_data_decl(); }
        if self.can_parse_cap_decl() { return self.parse_cap_decl(); }
        if self.can_parse_fn_decl() { return self.parse_fn_decl(); }
        if self.can_parse_use_decl() { return self.parse_use_decl(); }
        if self.can_parse_impl_decl() { return self.parse_impl_decl(); }
        self.error_here("expected ItemBody");
        node_from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_attribute(&self) -> bool { self.at_non_trivia_symbol("#") }
    fn parse_attribute(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("#", &mut children);
        self.expect_symbol("[", &mut children);
        self.expect_name(&mut children);
        if self.can_parse_attribute_args() {
            children.push(SyntaxElement::Node(Box::new(self.parse_attribute_args())));
        }
        self.expect_symbol("]", &mut children);
        node_from_children(SyntaxKind::ATTRIBUTE, children)
    }

    fn can_parse_attribute_args(&self) -> bool { self.at_non_trivia_symbol("(") }
    fn parse_attribute_args(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("(", &mut children);
        while self.can_parse_attribute_arg_item() {
            children.push(SyntaxElement::Node(Box::new(self.parse_attribute_arg_item())));
        }
        self.expect_symbol(")", &mut children);
        node_from_children(SyntaxKind::ATTRIBUTE_ARGS, children)
    }

    fn can_parse_attribute_arg_item(&self) -> bool { self.at_non_trivia_name() }
    fn parse_attribute_arg_item(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_name(&mut children);
        if self.at_non_trivia_symbol("=") {
            self.expect_symbol("=", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        }
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::ATTRIBUTE_ARG_ITEM, children)
    }

    fn can_parse_data_decl(&self) -> bool { self.at_non_trivia_keyword(Keyword::Data) }
    fn parse_data_decl(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Data, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.can_parse_generic_params() {
            children.push(SyntaxElement::Node(Box::new(self.parse_generic_params())));
        }
        self.expect_symbol("{", &mut children);
        while self.can_parse_variant() {
            children.push(SyntaxElement::Node(Box::new(self.parse_variant())));
        }
        self.expect_symbol("}", &mut children);
        node_from_children(SyntaxKind::DATA_DECL, children)
    }

    fn can_parse_variant(&self) -> bool { self.at_non_trivia_symbol("#") || self.at_non_trivia_symbol(".") }
    fn parse_variant(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        while self.can_parse_attribute() {
            children.push(SyntaxElement::Node(Box::new(self.parse_attribute())));
        }
        self.expect_symbol(".", &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.can_parse_variant_fields() {
            children.push(SyntaxElement::Node(Box::new(self.parse_variant_fields())));
        }
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::VARIANT, children)
    }

    fn can_parse_variant_fields(&self) -> bool { self.at_non_trivia_symbol("(") }
    fn parse_variant_fields(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("(", &mut children);
        if self.can_parse_variant_field_items() {
            children.push(SyntaxElement::Node(Box::new(self.parse_variant_field_items())));
        }
        self.expect_symbol(")", &mut children);
        node_from_children(SyntaxKind::VARIANT_FIELDS, children)
    }

    fn can_parse_variant_field_items(&self) -> bool { self.can_parse_type_expr() }
    fn parse_variant_field_items(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        while self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::VARIANT_FIELD_ITEMS, children)
    }

    fn can_parse_fn_decl(&self) -> bool { self.at_non_trivia_keyword(Keyword::Fn) }
    fn parse_fn_decl(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Fn, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.can_parse_generic_params() {
            children.push(SyntaxElement::Node(Box::new(self.parse_generic_params())));
        }
        children.push(SyntaxElement::Node(Box::new(self.parse_param_list())));
        if self.at_non_trivia_symbol(":") {
            self.expect_symbol(":", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        if self.can_parse_cap_annotation() {
            children.push(SyntaxElement::Node(Box::new(self.parse_cap_annotation())));
        }
        children.push(SyntaxElement::Node(Box::new(self.parse_fn_body())));
        node_from_children(SyntaxKind::FN_DECL, children)
    }

    fn can_parse_fn_body(&self) -> bool { self.can_parse_block_expr() || self.can_parse_expr_body() }
    fn parse_fn_body(&mut self) -> SyntaxNode {
        if self.can_parse_block_expr() { return self.parse_block_expr(); }
        if self.can_parse_expr_body() { return self.parse_expr_body(); }
        self.error_here("expected FnBody");
        node_from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_expr_body(&self) -> bool { self.at_non_trivia_symbol("=") }
    fn parse_expr_body(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("=", &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        node_from_children(SyntaxKind::EXPR_BODY, children)
    }

    fn can_parse_generic_params(&self) -> bool { self.at_non_trivia_symbol("[") }
    fn parse_generic_params(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("[", &mut children);
        if self.can_parse_generic_param_items() {
            children.push(SyntaxElement::Node(Box::new(self.parse_generic_param_items())));
        }
        self.expect_symbol("]", &mut children);
        node_from_children(SyntaxKind::GENERIC_PARAMS, children)
    }

    fn can_parse_generic_param_items(&self) -> bool { self.can_parse_generic_param() }
    fn parse_generic_param_items(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_generic_param())));
        while self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_generic_param())));
        }
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::GENERIC_PARAM_ITEMS, children)
    }

    fn can_parse_generic_param(&self) -> bool { self.at_non_trivia_ident() }
    fn parse_generic_param(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.at_non_trivia_symbol(":") {
            self.expect_symbol(":", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        node_from_children(SyntaxKind::GENERIC_PARAM, children)
    }

    fn can_parse_param_list(&self) -> bool { self.at_non_trivia_symbol("(") }
    fn parse_param_list(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("(", &mut children);
        if self.can_parse_param_items() {
            children.push(SyntaxElement::Node(Box::new(self.parse_param_items())));
        }
        self.expect_symbol(")", &mut children);
        node_from_children(SyntaxKind::PARAM_LIST, children)
    }

    fn can_parse_param_items(&self) -> bool { self.can_parse_param() }
    fn parse_param_items(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_param())));
        while self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_param())));
        }
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::PARAM_ITEMS, children)
    }

    fn can_parse_param(&self) -> bool { self.at_non_trivia_ident() }
    fn parse_param(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        self.expect_symbol(":", &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        node_from_children(SyntaxKind::PARAM, children)
    }

    fn can_parse_cap_annotation(&self) -> bool { self.at_non_trivia_symbol("/") }
    fn parse_cap_annotation(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("/", &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_cap_set())));
        node_from_children(SyntaxKind::CAP_ANNOTATION, children)
    }

    fn can_parse_cap_set(&self) -> bool { self.at_non_trivia_symbol("{") }
    fn parse_cap_set(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("{", &mut children);
        while self.can_parse_cap_sig() {
            children.push(SyntaxElement::Node(Box::new(self.parse_cap_sig())));
        }
        self.expect_symbol("}", &mut children);
        node_from_children(SyntaxKind::CAP_SET, children)
    }

    fn can_parse_cap_sig(&self) -> bool { self.at_non_trivia_ident() }
    fn parse_cap_sig(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.can_parse_generic_args() {
            children.push(SyntaxElement::Node(Box::new(self.parse_generic_args())));
        }
        node_from_children(SyntaxKind::CAP_SIG, children)
    }

    fn can_parse_cap_decl(&self) -> bool { self.at_non_trivia_keyword(Keyword::Cap) }
    fn parse_cap_decl(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Cap, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        self.expect_symbol("{", &mut children);
        while self.can_parse_operation_decl() {
            children.push(SyntaxElement::Node(Box::new(self.parse_operation_decl())));
        }
        self.expect_symbol("}", &mut children);
        node_from_children(SyntaxKind::CAP_DECL, children)
    }

    fn can_parse_operation_decl(&self) -> bool { self.at_non_trivia_keyword(Keyword::Fn) }
    fn parse_operation_decl(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Fn, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        children.push(SyntaxElement::Node(Box::new(self.parse_param_list())));
        if self.at_non_trivia_symbol(":") {
            self.expect_symbol(":", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        node_from_children(SyntaxKind::OPERATION_DECL, children)
    }

    fn can_parse_extern_decl(&self) -> bool { self.at_non_trivia_keyword(Keyword::Extern) }
    fn parse_extern_decl(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Extern, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_extern_rest())));
        node_from_children(SyntaxKind::EXTERN_DECL, children)
    }

    fn can_parse_extern_rest(&self) -> bool { self.can_parse_extern_type_tail() || self.can_parse_extern_fn_tail() || self.can_parse_extern_block_tail() }
    fn parse_extern_rest(&mut self) -> SyntaxNode {
        if self.can_parse_extern_type_tail() { return self.parse_extern_type_tail(); }
        if self.can_parse_extern_fn_tail() { return self.parse_extern_fn_tail(); }
        if self.can_parse_extern_block_tail() { return self.parse_extern_block_tail(); }
        self.error_here("expected ExternRest");
        node_from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_extern_type_tail(&self) -> bool { self.at_non_trivia_keyword(Keyword::Type) }
    fn parse_extern_type_tail(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Type, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.at_non_trivia_symbol(";") {
            self.expect_symbol(";", &mut children);
        }
        node_from_children(SyntaxKind::EXTERN_TYPE_TAIL, children)
    }

    fn can_parse_extern_fn_tail(&self) -> bool { self.at_non_trivia_keyword(Keyword::Fn) }
    fn parse_extern_fn_tail(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Fn, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        children.push(SyntaxElement::Node(Box::new(self.parse_param_list())));
        if self.at_non_trivia_symbol(":") {
            self.expect_symbol(":", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        if self.can_parse_cap_annotation() {
            children.push(SyntaxElement::Node(Box::new(self.parse_cap_annotation())));
        }
        if self.at_non_trivia_symbol(";") {
            self.expect_symbol(";", &mut children);
        }
        node_from_children(SyntaxKind::EXTERN_FN_TAIL, children)
    }

    fn can_parse_extern_block_tail(&self) -> bool { self.at_non_trivia_symbol("{") }
    fn parse_extern_block_tail(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("{", &mut children);
        while self.can_parse_extern_block_item() {
            children.push(SyntaxElement::Node(Box::new(self.parse_extern_block_item())));
        }
        self.expect_symbol("}", &mut children);
        node_from_children(SyntaxKind::EXTERN_BLOCK_TAIL, children)
    }

    fn can_parse_extern_block_item(&self) -> bool { self.at_non_trivia_symbol("#") || self.can_parse_extern_block_item_body() }
    fn parse_extern_block_item(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        while self.can_parse_attribute() {
            children.push(SyntaxElement::Node(Box::new(self.parse_attribute())));
        }
        children.push(SyntaxElement::Node(Box::new(self.parse_extern_block_item_body())));
        node_from_children(SyntaxKind::EXTERN_BLOCK_ITEM, children)
    }

    fn can_parse_extern_block_item_body(&self) -> bool { self.can_parse_extern_type_tail() || self.can_parse_extern_fn_tail() }
    fn parse_extern_block_item_body(&mut self) -> SyntaxNode {
        if self.can_parse_extern_type_tail() { return self.parse_extern_type_tail(); }
        if self.can_parse_extern_fn_tail() { return self.parse_extern_fn_tail(); }
        self.error_here("expected ExternBlockItemBody");
        node_from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_use_decl(&self) -> bool { self.at_non_trivia_keyword(Keyword::Use) }
    fn parse_use_decl(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Use, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_use_path())));
        self.expect_symbol(";", &mut children);
        node_from_children(SyntaxKind::USE_DECL, children)
    }

    fn can_parse_use_path(&self) -> bool { self.at_non_trivia_ident() }
    fn parse_use_path(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.can_parse_use_path_rest() {
            children.push(SyntaxElement::Node(Box::new(self.parse_use_path_rest())));
        }
        node_from_children(SyntaxKind::USE_PATH, children)
    }

    fn can_parse_use_path_rest(&self) -> bool { self.at_non_trivia_symbol(".") }
    fn parse_use_path_rest(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol(".", &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_use_path_item())));
        node_from_children(SyntaxKind::USE_PATH_REST, children)
    }

    fn can_parse_use_path_item(&self) -> bool { self.can_parse_use_path_branch() || self.can_parse_use_tree() }
    fn parse_use_path_item(&mut self) -> SyntaxNode {
        if self.can_parse_use_path_branch() { return self.parse_use_path_branch(); }
        if self.can_parse_use_tree() { return self.parse_use_tree(); }
        self.error_here("expected UsePathItem");
        node_from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_use_path_branch(&self) -> bool { self.at_non_trivia_ident() }
    fn parse_use_path_branch(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.can_parse_use_path_rest() {
            children.push(SyntaxElement::Node(Box::new(self.parse_use_path_rest())));
        }
        node_from_children(SyntaxKind::USE_PATH_BRANCH, children)
    }

    fn can_parse_use_tree(&self) -> bool { self.at_non_trivia_symbol("{") }
    fn parse_use_tree(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("{", &mut children);
        if self.can_parse_use_name_items() {
            children.push(SyntaxElement::Node(Box::new(self.parse_use_name_items())));
        }
        self.expect_symbol("}", &mut children);
        node_from_children(SyntaxKind::USE_TREE, children)
    }

    fn can_parse_use_name_items(&self) -> bool { self.can_parse_use_name_item() }
    fn parse_use_name_items(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_use_name_item())));
        while self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_use_name_item())));
        }
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::USE_NAME_ITEMS, children)
    }

    fn can_parse_use_name_item(&self) -> bool { self.at_non_trivia_ident() }
    fn parse_use_name_item(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        node_from_children(SyntaxKind::USE_NAME_ITEM, children)
    }

    fn can_parse_impl_decl(&self) -> bool { self.at_non_trivia_keyword(Keyword::Impl) }
    fn parse_impl_decl(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Impl, &mut children);
        if self.can_parse_generic_params() {
            children.push(SyntaxElement::Node(Box::new(self.parse_generic_params())));
        }
        if self.at_non_trivia_ident() {
            self.skip_trivia_into(&mut children);
            if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
                children.push(SyntaxElement::Token(self.bump().unwrap()));
            } else { self.error_here("expected Ident"); }
        }
        children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        if self.at_non_trivia_symbol(":") {
            self.expect_symbol(":", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        self.expect_symbol("{", &mut children);
        while self.can_parse_impl_method() {
            children.push(SyntaxElement::Node(Box::new(self.parse_impl_method())));
        }
        self.expect_symbol("}", &mut children);
        node_from_children(SyntaxKind::IMPL_DECL, children)
    }

    fn can_parse_impl_method(&self) -> bool { self.at_non_trivia_keyword(Keyword::Fn) }
    fn parse_impl_method(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Fn, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        children.push(SyntaxElement::Node(Box::new(self.parse_param_list())));
        if self.at_non_trivia_symbol(":") {
            self.expect_symbol(":", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        children.push(SyntaxElement::Node(Box::new(self.parse_fn_body())));
        node_from_children(SyntaxKind::IMPL_METHOD, children)
    }

    fn can_parse_expr(&self) -> bool { self.at_pratt_unary_expr() || self.can_parse_ident_expr() || self.can_parse_string_expr() || self.can_parse_number_expr() || self.can_parse_let_expr() || self.can_parse_thunk_expr() || self.can_parse_force_expr() || self.can_parse_match_expr() || self.can_parse_handle_expr() || self.can_parse_bundle_expr() || self.can_parse_if_else_expr() || self.can_parse_block_expr() || self.can_parse_paren_expr() || self.can_parse_annotation_expr() || self.can_parse_lambda_expr() || self.can_parse_perform_expr() }
    fn parse_expr(&mut self) -> SyntaxNode {
        self.parse_expr_bp(0)
    }

    fn parse_expr_bp(&mut self, min_bp: u8) -> SyntaxNode {
        let mut lhs = self.parse_expr_atom();
        loop {
            // MemberExpr (lbp=90)
            if self.at_pratt_member_expr() && 90 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.expect_symbol(".", &mut children);
                self.skip_trivia_into(&mut children);
                if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
                    children.push(SyntaxElement::Token(self.bump().unwrap()));
                } else { self.error_here("expected Ident"); }
                lhs = node_from_children(SyntaxKind::MEMBER_EXPR, children);
                continue;
            }
            // CallExpr (lbp=90)
            if self.at_pratt_call_expr() && 90 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.expect_symbol("(", &mut children);
                children.push(SyntaxElement::Node(Box::new(self.parse_call_arg_items())));
                self.expect_symbol(")", &mut children);
                lhs = node_from_children(SyntaxKind::CALL_EXPR, children);
                continue;
            }
            // BinaryExpr (lbp=30)
            if self.at_pratt_binary_expr() && 30 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.expect_symbol("*", &mut children);
                self.expect_symbol("/", &mut children);
                self.expect_symbol("%", &mut children);
                lhs = node_from_children(SyntaxKind::BINARY_EXPR, children);
                continue;
            }
            // BinaryExpr (lbp=20)
            if self.at_pratt_binary_expr() && 20 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.expect_symbol("+", &mut children);
                self.expect_symbol("-", &mut children);
                lhs = node_from_children(SyntaxKind::BINARY_EXPR, children);
                continue;
            }
            // BinaryExpr (lbp=10)
            if self.at_pratt_binary_expr() && 10 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.expect_symbol("==", &mut children);
                self.expect_symbol("!=", &mut children);
                self.expect_symbol("<", &mut children);
                self.expect_symbol("<=", &mut children);
                self.expect_symbol(">", &mut children);
                self.expect_symbol(">=", &mut children);
                lhs = node_from_children(SyntaxKind::BINARY_EXPR, children);
                continue;
            }
            // BinaryExpr (lbp=5)
            if self.at_pratt_binary_expr() && 5 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.expect_symbol("&&", &mut children);
                lhs = node_from_children(SyntaxKind::BINARY_EXPR, children);
                continue;
            }
            // BinaryExpr (lbp=3)
            if self.at_pratt_binary_expr() && 3 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.expect_symbol("||", &mut children);
                lhs = node_from_children(SyntaxKind::BINARY_EXPR, children);
                continue;
            }
            // AssignExpr (lbp=1)
            if self.at_pratt_assign_expr() && 1 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.expect_symbol("=", &mut children);
                children.push(SyntaxElement::Node(Box::new(self.parse_expr_bp(1))));
                self.expect_symbol(";", &mut children);
                children.push(SyntaxElement::Node(Box::new(self.parse_expr_bp(1))));
                lhs = node_from_children(SyntaxKind::ASSIGN_EXPR, children);
                continue;
            }
            break;
        }
        lhs
    }

    fn parse_expr_atom(&mut self) -> SyntaxNode {
        if self.at_pratt_unary_expr() {
            let mut children = Vec::new();
            self.expect_symbol("-", &mut children);
            self.expect_symbol("!", &mut children);
            return node_from_children(SyntaxKind::UNARY_EXPR, children);
        }
        if self.can_parse_ident_expr() { return self.parse_ident_expr(); }
        if self.can_parse_string_expr() { return self.parse_string_expr(); }
        if self.can_parse_number_expr() { return self.parse_number_expr(); }
        if self.can_parse_let_expr() { return self.parse_let_expr(); }
        if self.can_parse_thunk_expr() { return self.parse_thunk_expr(); }
        if self.can_parse_force_expr() { return self.parse_force_expr(); }
        if self.can_parse_match_expr() { return self.parse_match_expr(); }
        if self.can_parse_handle_expr() { return self.parse_handle_expr(); }
        if self.can_parse_bundle_expr() { return self.parse_bundle_expr(); }
        if self.can_parse_if_else_expr() { return self.parse_if_else_expr(); }
        if self.can_parse_block_expr() { return self.parse_block_expr(); }
        if self.can_parse_paren_expr() { return self.parse_paren_expr(); }
        if self.can_parse_annotation_expr() { return self.parse_annotation_expr(); }
        if self.can_parse_lambda_expr() { return self.parse_lambda_expr(); }
        if self.can_parse_perform_expr() { return self.parse_perform_expr(); }
        self.error_here("expected expression");
        node_from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn at_pratt_unary_expr(&self) -> bool { self.at_non_trivia_symbol("-") }
    fn at_pratt_member_expr(&self) -> bool { self.at_non_trivia_symbol(".") }
    fn at_pratt_call_expr(&self) -> bool { self.at_non_trivia_symbol("(") }
    fn at_pratt_binary_expr(&self) -> bool { self.at_non_trivia_symbol("*") }
    fn at_pratt_assign_expr(&self) -> bool { self.at_non_trivia_symbol("=") }
    fn can_parse_call_arg_items(&self) -> bool { self.can_parse_expr() }
    fn parse_call_arg_items(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        while self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        }
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::CALL_ARG_ITEMS, children)
    }

    fn can_parse_ident_expr(&self) -> bool { self.at_non_trivia_ident() }
    fn parse_ident_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        node_from_children(SyntaxKind::IDENT_EXPR, children)
    }

    fn can_parse_string_expr(&self) -> bool { self.at_non_trivia_string_lit() }
    fn parse_string_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::StringLit)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected StringLit"); }
        node_from_children(SyntaxKind::STRING_EXPR, children)
    }

    fn can_parse_number_expr(&self) -> bool { self.at_non_trivia_number_lit() }
    fn parse_number_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::NumberLit)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected NumberLit"); }
        node_from_children(SyntaxKind::NUMBER_EXPR, children)
    }

    fn can_parse_let_expr(&self) -> bool { self.at_non_trivia_keyword(Keyword::Let) }
    fn parse_let_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Let, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.at_non_trivia_symbol(":") {
            self.expect_symbol(":", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        self.expect_symbol("=", &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        node_from_children(SyntaxKind::LET_EXPR, children)
    }

    fn can_parse_thunk_expr(&self) -> bool { self.at_non_trivia_keyword(Keyword::Thunk) }
    fn parse_thunk_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Thunk, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        node_from_children(SyntaxKind::THUNK_EXPR, children)
    }

    fn can_parse_force_expr(&self) -> bool { self.at_non_trivia_keyword(Keyword::Force) }
    fn parse_force_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Force, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        node_from_children(SyntaxKind::FORCE_EXPR, children)
    }

    fn can_parse_perform_expr(&self) -> bool { self.at_non_trivia_keyword(Keyword::Perform) }
    fn parse_perform_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Perform, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        node_from_children(SyntaxKind::PERFORM_EXPR, children)
    }

    fn can_parse_match_expr(&self) -> bool { self.at_non_trivia_keyword(Keyword::Match) }
    fn parse_match_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Match, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        self.expect_symbol("{", &mut children);
        while self.can_parse_match_arm() {
            children.push(SyntaxElement::Node(Box::new(self.parse_match_arm())));
        }
        self.expect_symbol("}", &mut children);
        node_from_children(SyntaxKind::MATCH_EXPR, children)
    }

    fn can_parse_match_arm(&self) -> bool { self.can_parse_pattern() }
    fn parse_match_arm(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_pattern())));
        self.expect_symbol("=>", &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::MATCH_ARM, children)
    }

    fn can_parse_handle_expr(&self) -> bool { self.at_non_trivia_keyword(Keyword::Handle) }
    fn parse_handle_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Handle, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.at_non_trivia_keyword(Keyword::For) {
            self.expect_keyword(Keyword::For, &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        self.skip_trivia_into(&mut children);
        if self.current().map(|t| matches!(t.kind, LexKind::Ident) && t.text.as_str() == "with").unwrap_or(false) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected 'with'"); }
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        self.expect_keyword(Keyword::In, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        node_from_children(SyntaxKind::HANDLE_EXPR, children)
    }

    fn can_parse_bundle_expr(&self) -> bool { self.at_non_trivia_keyword(Keyword::Bundle) }
    fn parse_bundle_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Bundle, &mut children);
        self.expect_symbol("{", &mut children);
        while self.can_parse_bundle_entry() {
            children.push(SyntaxElement::Node(Box::new(self.parse_bundle_entry())));
        }
        self.expect_symbol("}", &mut children);
        node_from_children(SyntaxKind::BUNDLE_EXPR, children)
    }

    fn can_parse_bundle_entry(&self) -> bool { self.at_non_trivia_keyword(Keyword::Fn) }
    fn parse_bundle_entry(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Fn, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        children.push(SyntaxElement::Node(Box::new(self.parse_param_list())));
        children.push(SyntaxElement::Node(Box::new(self.parse_fn_body())));
        node_from_children(SyntaxKind::BUNDLE_ENTRY, children)
    }

    fn can_parse_paren_expr(&self) -> bool { self.at_non_trivia_symbol("(") }
    fn parse_paren_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("(", &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        self.expect_symbol(")", &mut children);
        node_from_children(SyntaxKind::PAREN_EXPR, children)
    }

    fn can_parse_annotation_expr(&self) -> bool { self.at_non_trivia_symbol("(") }
    fn parse_annotation_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("(", &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        self.expect_symbol(":", &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        self.expect_symbol(")", &mut children);
        node_from_children(SyntaxKind::ANNOTATION_EXPR, children)
    }

    fn can_parse_lambda_expr(&self) -> bool { self.at_non_trivia_keyword(Keyword::Fn) }
    fn parse_lambda_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Fn, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_lambda_param_list())));
        children.push(SyntaxElement::Node(Box::new(self.parse_fn_body())));
        node_from_children(SyntaxKind::LAMBDA_EXPR, children)
    }

    fn can_parse_lambda_param_list(&self) -> bool { self.at_non_trivia_symbol("(") }
    fn parse_lambda_param_list(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("(", &mut children);
        if self.can_parse_lambda_param_items() {
            children.push(SyntaxElement::Node(Box::new(self.parse_lambda_param_items())));
        }
        self.expect_symbol(")", &mut children);
        node_from_children(SyntaxKind::LAMBDA_PARAM_LIST, children)
    }

    fn can_parse_lambda_param_items(&self) -> bool { self.can_parse_lambda_param() }
    fn parse_lambda_param_items(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_lambda_param())));
        while self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_lambda_param())));
        }
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::LAMBDA_PARAM_ITEMS, children)
    }

    fn can_parse_lambda_param(&self) -> bool { self.at_non_trivia_ident() }
    fn parse_lambda_param(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.at_non_trivia_symbol(":") {
            self.expect_symbol(":", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        node_from_children(SyntaxKind::LAMBDA_PARAM, children)
    }

    fn can_parse_block_expr(&self) -> bool { self.at_non_trivia_symbol("{") }
    fn parse_block_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("{", &mut children);
        while self.can_parse_block_stmt() {
            children.push(SyntaxElement::Node(Box::new(self.parse_block_stmt())));
        }
        self.expect_symbol("}", &mut children);
        node_from_children(SyntaxKind::BLOCK_EXPR, children)
    }

    fn can_parse_if_else_expr(&self) -> bool { self.at_non_trivia_keyword(Keyword::If) }
    fn parse_if_else_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::If, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        children.push(SyntaxElement::Node(Box::new(self.parse_block_expr())));
        if self.at_non_trivia_keyword(Keyword::Else) {
            self.expect_keyword(Keyword::Else, &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_else_clause())));
        }
        node_from_children(SyntaxKind::IF_ELSE_EXPR, children)
    }

    fn can_parse_else_clause(&self) -> bool { self.can_parse_if_else_expr() || self.can_parse_block_expr() }
    fn parse_else_clause(&mut self) -> SyntaxNode {
        if self.can_parse_if_else_expr() { return self.parse_if_else_expr(); }
        if self.can_parse_block_expr() { return self.parse_block_expr(); }
        self.error_here("expected ElseClause");
        node_from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_block_stmt(&self) -> bool { self.can_parse_let_stmt() || self.can_parse_expr_stmt() }
    fn parse_block_stmt(&mut self) -> SyntaxNode {
        if self.can_parse_let_stmt() { return self.parse_let_stmt(); }
        if self.can_parse_expr_stmt() { return self.parse_expr_stmt(); }
        self.error_here("expected BlockStmt");
        node_from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_let_stmt(&self) -> bool { self.at_non_trivia_keyword(Keyword::Let) }
    fn parse_let_stmt(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Let, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        self.expect_symbol("=", &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        self.expect_symbol(";", &mut children);
        node_from_children(SyntaxKind::LET_STMT, children)
    }

    fn can_parse_expr_stmt(&self) -> bool { self.can_parse_expr() }
    fn parse_expr_stmt(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        if self.at_non_trivia_symbol(";") {
            self.expect_symbol(";", &mut children);
        }
        node_from_children(SyntaxKind::EXPR_STMT, children)
    }

    fn can_parse_pattern(&self) -> bool { self.can_parse_variant_pattern() || self.can_parse_bind_pattern() || self.can_parse_wildcard_pattern() }
    fn parse_pattern(&mut self) -> SyntaxNode {
        if self.can_parse_variant_pattern() { return self.parse_variant_pattern(); }
        if self.can_parse_bind_pattern() { return self.parse_bind_pattern(); }
        if self.can_parse_wildcard_pattern() { return self.parse_wildcard_pattern(); }
        self.error_here("expected Pattern");
        node_from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_variant_pattern(&self) -> bool { self.at_non_trivia_symbol(".") }
    fn parse_variant_pattern(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol(".", &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.at_non_trivia_symbol("(") {
            self.expect_symbol("(", &mut children);
            if self.can_parse_variant_pattern_fields() {
                children.push(SyntaxElement::Node(Box::new(self.parse_variant_pattern_fields())));
            }
            self.expect_symbol(")", &mut children);
        }
        node_from_children(SyntaxKind::VARIANT_PATTERN, children)
    }

    fn can_parse_variant_pattern_fields(&self) -> bool { self.can_parse_pattern() }
    fn parse_variant_pattern_fields(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_pattern())));
        while self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_pattern())));
        }
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::VARIANT_PATTERN_FIELDS, children)
    }

    fn can_parse_bind_pattern(&self) -> bool { self.at_non_trivia_keyword(Keyword::Let) }
    fn parse_bind_pattern(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_keyword(Keyword::Let, &mut children);
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        node_from_children(SyntaxKind::BIND_PATTERN, children)
    }

    fn can_parse_wildcard_pattern(&self) -> bool { self.at_non_trivia_symbol("_") }
    fn parse_wildcard_pattern(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("_", &mut children);
        node_from_children(SyntaxKind::WILDCARD_PATTERN, children)
    }

    fn can_parse_type_expr(&self) -> bool { self.at_non_trivia_ident() }
    fn parse_type_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.skip_trivia_into(&mut children);
        if matches!(self.current().map(|t| &t.kind), Some(LexKind::Ident)) {
            children.push(SyntaxElement::Token(self.bump().unwrap()));
        } else { self.error_here("expected Ident"); }
        if self.can_parse_generic_args() {
            children.push(SyntaxElement::Node(Box::new(self.parse_generic_args())));
        }
        node_from_children(SyntaxKind::TYPE_EXPR, children)
    }

    fn can_parse_generic_args(&self) -> bool { self.at_non_trivia_symbol("[") }
    fn parse_generic_args(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.expect_symbol("[", &mut children);
        if self.can_parse_generic_arg_items() {
            children.push(SyntaxElement::Node(Box::new(self.parse_generic_arg_items())));
        }
        self.expect_symbol("]", &mut children);
        node_from_children(SyntaxKind::GENERIC_ARGS, children)
    }

    fn can_parse_generic_arg_items(&self) -> bool { self.can_parse_type_expr() }
    fn parse_generic_arg_items(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        while self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_expr())));
        }
        if self.at_non_trivia_symbol(",") {
            self.expect_symbol(",", &mut children);
        }
        node_from_children(SyntaxKind::GENERIC_ARG_ITEMS, children)
    }

}
