// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.

use langue_rt::ParseReport;

pub struct LanguageOps {
    pub name: &'static str,
    pub parse_report: fn(&str) -> ParseReport,
}

pub static LANGUAGES: &[LanguageOps] = &[
    LanguageOps { name: "Lumo", parse_report: lumo_report },
];

pub fn language(name: &str) -> Option<&'static LanguageOps> {
    LANGUAGES.iter().find(|l| l.name == name)
}

fn lumo_report(text: &str) -> ParseReport {
    let out = crate::lumo::parser::parse(text);
    let canonical = crate::lumo::printer::canonical(&out.root);
    let reparse = crate::lumo::parser::parse(&canonical);
    ParseReport {
        sexpr: crate::lumo::printer::sexpr(&out.root),
        errors: out.errors.iter().map(|e| format!("{}: {}", e.span, e.message)).collect(),
        lossless: out.root.text(),
        round_trip_sexpr: crate::lumo::printer::sexpr(&reparse.root),
        canonical,
    }
}
