// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.

use langue_rt::{ElabReport, ParseReport};

pub struct LanguageOps {
    pub name: &'static str,
    pub parse_report: fn(&str) -> ParseReport,
}

pub static LANGUAGES: &[LanguageOps] = &[
    LanguageOps { name: "JS", parse_report: js_report },
    LanguageOps { name: "Lumo", parse_report: lumo_report },
    LanguageOps { name: "MIR", parse_report: mir_report },
];

pub fn language(name: &str) -> Option<&'static LanguageOps> {
    LANGUAGES.iter().find(|l| l.name == name)
}

pub struct ElabOps {
    pub from: &'static str,
    pub to: &'static str,
    pub elab_report: fn(&str) -> ElabReport,
}

pub static ELABS: &[ElabOps] = &[
    ElabOps { from: "Lumo", to: "MIR", elab_report: lumo_to_mir_elab_report },
];

pub fn elab(from: &str, to: &str) -> Option<&'static ElabOps> {
    ELABS.iter().find(|e| e.from == from && e.to == to)
}

/// Externs come from the handwritten `crate::elab_externs::lumo_to_mir()`.
fn lumo_to_mir_elab_report(text: &str) -> ElabReport {
    let mut externs = crate::elab_externs::lumo_to_mir();
    crate::elab::lumo_to_mir::elab(text, externs.as_mut())
}

fn js_report(text: &str) -> ParseReport {
    let out = crate::js::parser::parse(text);
    let canonical = crate::js::printer::canonical(&out.root);
    let reparse = crate::js::parser::parse(&canonical);
    ParseReport {
        sexpr: crate::js::printer::sexpr(&out.root),
        errors: out.errors.iter().map(|e| format!("{}: {}", e.span, e.message)).collect(),
        lossless: out.root.text(),
        round_trip_sexpr: crate::js::printer::sexpr(&reparse.root),
        canonical,
    }
}

fn lumo_report(text: &str) -> ParseReport {
    let out = crate::lumo::parser::parse(text);
    let canonical = crate::lumo::printer::canonical(&out.root);
    let reparse = crate::lumo::parser::parse(&canonical);
    ParseReport {
        sexpr: crate::lumo::printer::sexpr(&out.root),
        errors: out.errors.iter().map(|e| format!("{}: {}", e.span, e.message)).collect(),
        lossless: out.root.text(),
        round_trip_sexpr: crate::lumo::printer::sexpr(&reparse.root),
        canonical,
    }
}

fn mir_report(text: &str) -> ParseReport {
    let out = crate::mir::parser::parse(text);
    let canonical = crate::mir::printer::canonical(&out.root);
    let reparse = crate::mir::parser::parse(&canonical);
    ParseReport {
        sexpr: crate::mir::printer::sexpr(&out.root),
        errors: out.errors.iter().map(|e| format!("{}: {}", e.span, e.message)).collect(),
        lossless: out.root.text(),
        round_trip_sexpr: crate::mir::printer::sexpr(&reparse.root),
        canonical,
    }
}
