// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.
#![allow(dead_code)]

use super::syntax_kind::SyntaxKind;

/// A praat operand: rendered text plus its root kind, when known.
/// `None` renders defensively (always parenthesized).
pub struct Operand<'a> {
    pub text: &'a str,
    pub kind: Option<SyntaxKind>,
}

fn push(out: &mut String, s: &str) {
    if s.is_empty() {
        return;
    }
    if !out.is_empty() {
        out.push(' ');
    }
    out.push_str(s);
}

/// Render a `BundleClause` node as reparseable text.
pub fn bundle_clause(name: &str, params: &[&str], body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "fn");
    push(&mut out, name);
    push(&mut out, "(");
    for (i, item) in params.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    push(&mut out, "=>");
    push(&mut out, body);
    out
}

/// Render a `BundleV` node as reparseable text.
pub fn bundle_v(clauses: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "bundle");
    push(&mut out, "{");
    for item in clauses {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `CapEntry` node as reparseable text.
pub fn cap_entry(body: &str) -> String {
    let mut out = String::new();
    push(&mut out, body);
    out
}

/// Render a `CapRest` node as reparseable text.
pub fn cap_rest(name: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, "..");
    if let Some(v) = name {
        push(&mut out, v);
    }
    out
}

/// Render a `CapRow` node as reparseable text.
pub fn cap_row(cap: &str) -> String {
    let mut out = String::new();
    push(&mut out, "/");
    push(&mut out, cap);
    out
}

/// Render a `CapSet` node as reparseable text.
pub fn cap_set(entries: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "{");
    for item in entries {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `CapSig` node as reparseable text.
pub fn cap_sig(name: &str, args: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, name);
    if let Some(v) = args {
        push(&mut out, v);
    }
    out
}

/// Render a `CaseArm` node as reparseable text.
pub fn case_arm(tag: &str, binders: Option<&str>, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, ".");
    push(&mut out, tag);
    if let Some(v) = binders {
        push(&mut out, v);
    }
    push(&mut out, "=>");
    push(&mut out, body);
    out
}

/// Render a `CaseBinders` node as reparseable text.
pub fn case_binders(names: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    for (i, item) in names.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    out
}

/// Render a `CaseC` node as reparseable text.
pub fn case_c(scrutinee: &str, arms: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "case");
    push(&mut out, scrutinee);
    push(&mut out, "{");
    for item in arms {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Trailing openness of a `Comp` operand (see module docs).
fn comp_r_bound(kind: Option<SyntaxKind>) -> u16 {
    let Some(kind) = kind else { return 0 };
    match kind {
        SyntaxKind::FIX_C | SyntaxKind::HANDLE_C | SyntaxKind::LAM_C | SyntaxKind::LET_C => 0,
        _ => u16::MAX,
    }
}

fn comp_b_bound(kind: Option<SyntaxKind>) -> u16 {
    let Some(kind) = kind else { return 0 };
    match kind {
        SyntaxKind::COMP_POSTFIX => 110,
        _ => u16::MAX,
    }
}

fn comp_paren(text: &str) -> String {
    paren_c(text)
}

/// Left operand of an operator row: parenthesize iff the row would
/// bind inside it.
fn comp_left(op: Operand, bind: u16) -> String {
    if bind > comp_r_bound(op.kind) {
        comp_paren(op.text)
    } else {
        op.text.to_owned()
    }
}

/// Operand parsed at a known min_bp (prefix/infix right side).
fn comp_at(op: Operand, min_bp: u16) -> String {
    if comp_b_bound(op.kind) <= min_bp {
        comp_paren(op.text)
    } else {
        op.text.to_owned()
    }
}

pub fn comp_postfix(expr: Operand, value_args: &str) -> String {
    let mut out = String::new();
    push(&mut out, &comp_left(expr, 110));
    push(&mut out, "(");
    push(&mut out, value_args);
    push(&mut out, ")");
    out
}

/// Render a `CtorArgs` node as reparseable text.
pub fn ctor_args(args: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    for (i, item) in args.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    out
}

/// Render a `CtorV` node as reparseable text.
pub fn ctor_v(tag: &str, args: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, ".");
    push(&mut out, tag);
    if let Some(v) = args {
        push(&mut out, v);
    }
    out
}

/// Render a `Def` node as reparseable text.
pub fn def(name: &str, value: &str) -> String {
    let mut out = String::new();
    push(&mut out, "def");
    push(&mut out, name);
    push(&mut out, "=");
    push(&mut out, value);
    out
}

/// Render a `FTypeC` node as reparseable text.
pub fn f_type_c(inner: &str, row: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, "F");
    push(&mut out, "(");
    push(&mut out, inner);
    push(&mut out, ")");
    if let Some(v) = row {
        push(&mut out, v);
    }
    out
}

/// Render a `File` node as reparseable text.
pub fn file(defs: &[&str]) -> String {
    let mut out = String::new();
    for item in defs {
        push(&mut out, item);
    }
    out
}

/// Render a `FixC` node as reparseable text.
pub fn fix_c(name: &str, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "fix");
    push(&mut out, name);
    push(&mut out, "=>");
    push(&mut out, body);
    out
}

/// Render a `FnTypeC` node as reparseable text.
pub fn fn_type_c(params: &[&str], ret: &str) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    for (i, item) in params.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    push(&mut out, "->");
    push(&mut out, ret);
    out
}

/// Render a `ForallTypeC` node as reparseable text.
pub fn forall_type_c(params: &[&str], body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "forall");
    for (i, item) in params.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ".");
    push(&mut out, body);
    out
}

/// Render a `ForceC` node as reparseable text.
pub fn force_c(value: &str) -> String {
    let mut out = String::new();
    push(&mut out, "force");
    push(&mut out, value);
    out
}

/// Render a `HandleC` node as reparseable text.
pub fn handle_c(cap: &str, handler: &str, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "handle");
    push(&mut out, cap);
    push(&mut out, "with");
    push(&mut out, handler);
    push(&mut out, "in");
    push(&mut out, body);
    out
}

/// Render a `LamC` node as reparseable text.
pub fn lam_c(param: &str, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "fn");
    push(&mut out, "(");
    push(&mut out, param);
    push(&mut out, ")");
    push(&mut out, "=>");
    push(&mut out, body);
    out
}

/// Render a `LetC` node as reparseable text.
pub fn let_c(name: &str, value: &str, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "let");
    push(&mut out, name);
    push(&mut out, "=");
    push(&mut out, value);
    push(&mut out, "in");
    push(&mut out, body);
    out
}

/// Render a `NamedTypeV` node as reparseable text.
pub fn named_type_v(name: &str, args: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, name);
    if let Some(v) = args {
        push(&mut out, v);
    }
    out
}

/// Render a `NumV` node as reparseable text.
pub fn num_v(value: &str) -> String {
    let mut out = String::new();
    push(&mut out, value);
    out
}

/// Render a `ParenC` node as reparseable text.
pub fn paren_c(inner: &str) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    push(&mut out, inner);
    push(&mut out, ")");
    out
}

/// Render a `ParenV` node as reparseable text.
pub fn paren_v(inner: &str, ty: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    push(&mut out, inner);
    if ty.is_some() {
        push(&mut out, ":");
        if let Some(v) = ty {
            push(&mut out, v);
        }
    }
    push(&mut out, ")");
    out
}

/// Render a `PerformC` node as reparseable text.
pub fn perform_c(cap: &str) -> String {
    let mut out = String::new();
    push(&mut out, "perform");
    push(&mut out, cap);
    out
}

/// Render a `RetC` node as reparseable text.
pub fn ret_c(value: &str) -> String {
    let mut out = String::new();
    push(&mut out, "ret");
    push(&mut out, value);
    out
}

/// Render a `RollV` node as reparseable text.
pub fn roll_v(value: &str) -> String {
    let mut out = String::new();
    push(&mut out, "roll");
    push(&mut out, value);
    out
}

/// Render a `SelC` node as reparseable text.
pub fn sel_c(value: &str, field: &str) -> String {
    let mut out = String::new();
    push(&mut out, "sel");
    push(&mut out, value);
    push(&mut out, ".");
    push(&mut out, field);
    out
}

/// Render a `StrV` node as reparseable text.
pub fn str_v(value: &str) -> String {
    let mut out = String::new();
    push(&mut out, value);
    out
}

/// Render a `ThunkV` node as reparseable text.
pub fn thunk_v(body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "thunk");
    push(&mut out, "{");
    push(&mut out, body);
    push(&mut out, "}");
    out
}

/// Render a `TypeArgs` node as reparseable text.
pub fn type_args(args: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "[");
    for (i, item) in args.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, "]");
    out
}

/// Render a `UTypeV` node as reparseable text.
pub fn u_type_v(inner: &str) -> String {
    let mut out = String::new();
    push(&mut out, "U");
    push(&mut out, "(");
    push(&mut out, inner);
    push(&mut out, ")");
    out
}

/// Render a `UnrollV` node as reparseable text.
pub fn unroll_v(value: &str) -> String {
    let mut out = String::new();
    push(&mut out, "unroll");
    push(&mut out, value);
    out
}

/// Render a `ValueArgs` node as reparseable text.
pub fn value_args(args: &[&str]) -> String {
    let mut out = String::new();
    for (i, item) in args.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    out
}

/// Render a `VarV` node as reparseable text.
pub fn var_v(name: &str) -> String {
    let mut out = String::new();
    push(&mut out, name);
    out
}
