// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.

use std::sync::LazyLock;

use langue_rt::LexDfa;

use super::lossless::Token;
use super::syntax_kind::SyntaxKind;

static PATTERNS: &[&str] = &[
    "=>", // arrow.fat
    "->", // arrow.thin
    "\\}", // brace.close
    "\\{", // brace.open
    "\\]", // bracket.close
    "\\[", // bracket.open
    ":", // colon
    ",", // comma
    "\\.", // dot
    "\\.\\.", // dotdot
    "bundle", // keyword.bundle
    "case", // keyword.case
    "def", // keyword.def
    "fix", // keyword.fix
    "fn", // keyword.fn
    "forall", // keyword.forall
    "force", // keyword.force
    "handle", // keyword.handle
    "in", // keyword.in
    "let", // keyword.let
    "perform", // keyword.perform
    "ret", // keyword.ret
    "roll", // keyword.roll
    "sel", // keyword.sel
    "thunk", // keyword.thunk
    "unroll", // keyword.unroll
    "with", // keyword.with
    "=", // op.eq
    "/", // op.slash
    "\\)", // paren.close
    "\\(", // paren.open
    ";", // semi
    "F", // type.f
    "U", // type.u
    "//[^\\n]*", // comment.line
    "[a-zA-Z_][a-zA-Z0-9_]*", // ident
    "[0-9]+(\\.[0-9]+)?", // lit.number
    "\"([^\"\\\\]|\\\\.)*\"", // lit.string
    "[ \\t\\r\\n]+", // whitespace
];

const KINDS: &[SyntaxKind] = &[
    SyntaxKind::ARROW_FAT,
    SyntaxKind::ARROW_THIN,
    SyntaxKind::BRACE_CLOSE,
    SyntaxKind::BRACE_OPEN,
    SyntaxKind::BRACKET_CLOSE,
    SyntaxKind::BRACKET_OPEN,
    SyntaxKind::COLON,
    SyntaxKind::COMMA,
    SyntaxKind::DOT,
    SyntaxKind::DOTDOT,
    SyntaxKind::KEYWORD_BUNDLE,
    SyntaxKind::KEYWORD_CASE,
    SyntaxKind::KEYWORD_DEF,
    SyntaxKind::KEYWORD_FIX,
    SyntaxKind::KEYWORD_FN,
    SyntaxKind::KEYWORD_FORALL,
    SyntaxKind::KEYWORD_FORCE,
    SyntaxKind::KEYWORD_HANDLE,
    SyntaxKind::KEYWORD_IN,
    SyntaxKind::KEYWORD_LET,
    SyntaxKind::KEYWORD_PERFORM,
    SyntaxKind::KEYWORD_RET,
    SyntaxKind::KEYWORD_ROLL,
    SyntaxKind::KEYWORD_SEL,
    SyntaxKind::KEYWORD_THUNK,
    SyntaxKind::KEYWORD_UNROLL,
    SyntaxKind::KEYWORD_WITH,
    SyntaxKind::OP_EQ,
    SyntaxKind::OP_SLASH,
    SyntaxKind::PAREN_CLOSE,
    SyntaxKind::PAREN_OPEN,
    SyntaxKind::SEMI,
    SyntaxKind::TYPE_F,
    SyntaxKind::TYPE_U,
    SyntaxKind::COMMENT_LINE,
    SyntaxKind::IDENT,
    SyntaxKind::LIT_NUMBER,
    SyntaxKind::LIT_STRING,
    SyntaxKind::WHITESPACE,
];

static DFA: LazyLock<LexDfa> = LazyLock::new(|| LexDfa::build(PATTERNS));

/// Lossless tokenization: every input byte lands in exactly one
/// token; unlexable bytes become 1-byte UNKNOWN tokens.
pub fn lex(text: &str) -> Vec<Token> {
    DFA.lex(text)
        .into_iter()
        .map(|raw| Token {
            kind: raw.pattern.map_or(SyntaxKind::UNKNOWN, |p| KINDS[p as usize]),
            text: raw.span.slice(text).to_owned(),
            span: raw.span,
        })
        .collect()
}
