// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.
#![allow(dead_code)]

use langue_rt::Cursor;

use super::lossless::{ParseOutput, SyntaxElement, SyntaxNode};
use super::syntax_kind::SyntaxKind;

pub fn parse(text: &str) -> ParseOutput {
    let tokens = super::lexer::lex(text);
    let mut p = Parser { c: Cursor::new(tokens, SyntaxKind::is_trivia) };
    let mut root = p.parse_file();
    // Losslessness: sweep whatever the start rule left behind.
    let mut rest = Vec::new();
    p.c.drain_rest_into(SyntaxKind::ERROR, &mut rest);
    if !rest.is_empty() {
        let mut children = std::mem::take(&mut root.children);
        children.extend(rest);
        root = SyntaxNode::from_children(root.kind, children);
    }
    ParseOutput { root, errors: std::mem::take(&mut p.c.errors) }
}

struct Parser {
    c: Cursor<SyntaxKind>,
}

impl Parser {
    fn can_parse_bundle_clause(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_FN)
    }
    fn parse_bundle_clause(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_FN, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        if self.c.at(SyntaxKind::IDENT) {
            self.c.expect_into(SyntaxKind::IDENT, &mut children);
            while self.c.at(SyntaxKind::COMMA) {
                self.c.bump_into(&mut children);
                // Trailing separator is allowed.
                if self.c.at(SyntaxKind::IDENT) {
                    self.c.expect_into(SyntaxKind::IDENT, &mut children);
                } else {
                    break;
                }
            }
        }
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        self.c.expect_into(SyntaxKind::ARROW_FAT, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_comp())));
        if self.c.at(SyntaxKind::SEMI) {
            self.c.expect_into(SyntaxKind::SEMI, &mut children);
        }
        SyntaxNode::from_children(SyntaxKind::BUNDLE_CLAUSE, children)
    }

    fn can_parse_bundle_v(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_BUNDLE)
    }
    fn parse_bundle_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_BUNDLE, &mut children);
        self.c.expect_into(SyntaxKind::BRACE_OPEN, &mut children);
        loop {
            if self.c.at(SyntaxKind::KEYWORD_FN) {
                children.push(SyntaxElement::Node(Box::new(self.parse_bundle_clause())));
                continue;
            }
            if !self.c.eof() && !self.c.at(SyntaxKind::BRACE_CLOSE) {
                self.c.error_here("unexpected input".to_owned());
                let mut bad = Vec::new();
                while !self.c.eof() && !self.c.at(SyntaxKind::BRACE_CLOSE) && !self.c.at(SyntaxKind::KEYWORD_FN) {
                    self.c.bump_into(&mut bad);
                }
                children.push(SyntaxElement::Node(Box::new(SyntaxNode::from_children(SyntaxKind::ERROR, bad))));
                continue;
            }
            break;
        }
        self.c.expect_into(SyntaxKind::BRACE_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::BUNDLE_V, children)
    }

    fn can_parse_cap_entry(&self) -> bool {
        self.c.at_any(&[SyntaxKind::DOTDOT, SyntaxKind::IDENT])
    }
    fn parse_cap_entry(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_cap_entry_body())));
        if self.c.at(SyntaxKind::COMMA) {
            self.c.expect_into(SyntaxKind::COMMA, &mut children);
        }
        SyntaxNode::from_children(SyntaxKind::CAP_ENTRY, children)
    }

    fn can_parse_cap_entry_body(&self) -> bool {
        self.c.at_any(&[SyntaxKind::DOTDOT, SyntaxKind::IDENT])
    }
    fn parse_cap_entry_body(&mut self) -> SyntaxNode {
        if self.can_parse_cap_sig() {
            return self.parse_cap_sig();
        }
        if self.can_parse_cap_rest() {
            return self.parse_cap_rest();
        }
        self.c.error_here("expected CapEntryBody".to_owned());
        SyntaxNode::from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_cap_rest(&self) -> bool {
        self.c.at(SyntaxKind::DOTDOT)
    }
    fn parse_cap_rest(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::DOTDOT, &mut children);
        if self.c.at(SyntaxKind::IDENT) {
            self.c.expect_into(SyntaxKind::IDENT, &mut children);
        }
        SyntaxNode::from_children(SyntaxKind::CAP_REST, children)
    }

    fn can_parse_cap_row(&self) -> bool {
        self.c.at(SyntaxKind::OP_SLASH)
    }
    fn parse_cap_row(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::OP_SLASH, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_cap_set())));
        SyntaxNode::from_children(SyntaxKind::CAP_ROW, children)
    }

    fn can_parse_cap_set(&self) -> bool {
        self.c.at(SyntaxKind::BRACE_OPEN)
    }
    fn parse_cap_set(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::BRACE_OPEN, &mut children);
        loop {
            if self.c.at_any(&[SyntaxKind::DOTDOT, SyntaxKind::IDENT]) {
                children.push(SyntaxElement::Node(Box::new(self.parse_cap_entry())));
                continue;
            }
            if !self.c.eof() && !self.c.at(SyntaxKind::BRACE_CLOSE) {
                self.c.error_here("unexpected input".to_owned());
                let mut bad = Vec::new();
                while !self.c.eof() && !self.c.at(SyntaxKind::BRACE_CLOSE) && !self.c.at_any(&[SyntaxKind::DOTDOT, SyntaxKind::IDENT]) {
                    self.c.bump_into(&mut bad);
                }
                children.push(SyntaxElement::Node(Box::new(SyntaxNode::from_children(SyntaxKind::ERROR, bad))));
                continue;
            }
            break;
        }
        self.c.expect_into(SyntaxKind::BRACE_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::CAP_SET, children)
    }

    fn can_parse_cap_sig(&self) -> bool {
        self.c.at(SyntaxKind::IDENT)
    }
    fn parse_cap_sig(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        if self.c.at(SyntaxKind::BRACKET_OPEN) {
            children.push(SyntaxElement::Node(Box::new(self.parse_type_args())));
        }
        SyntaxNode::from_children(SyntaxKind::CAP_SIG, children)
    }

    fn can_parse_case_arm(&self) -> bool {
        self.c.at(SyntaxKind::DOT)
    }
    fn parse_case_arm(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::DOT, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        if self.c.at(SyntaxKind::PAREN_OPEN) {
            children.push(SyntaxElement::Node(Box::new(self.parse_case_binders())));
        }
        self.c.expect_into(SyntaxKind::ARROW_FAT, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_comp())));
        if self.c.at(SyntaxKind::COMMA) {
            self.c.expect_into(SyntaxKind::COMMA, &mut children);
        }
        SyntaxNode::from_children(SyntaxKind::CASE_ARM, children)
    }

    fn can_parse_case_binders(&self) -> bool {
        self.c.at(SyntaxKind::PAREN_OPEN)
    }
    fn parse_case_binders(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        if self.c.at(SyntaxKind::IDENT) {
            self.c.expect_into(SyntaxKind::IDENT, &mut children);
            while self.c.at(SyntaxKind::COMMA) {
                self.c.bump_into(&mut children);
                // Trailing separator is allowed.
                if self.c.at(SyntaxKind::IDENT) {
                    self.c.expect_into(SyntaxKind::IDENT, &mut children);
                } else {
                    break;
                }
            }
        }
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::CASE_BINDERS, children)
    }

    fn can_parse_case_c(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_CASE)
    }
    fn parse_case_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_CASE, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_value())));
        self.c.expect_into(SyntaxKind::BRACE_OPEN, &mut children);
        loop {
            if self.c.at(SyntaxKind::DOT) {
                children.push(SyntaxElement::Node(Box::new(self.parse_case_arm())));
                continue;
            }
            if !self.c.eof() && !self.c.at(SyntaxKind::BRACE_CLOSE) {
                self.c.error_here("unexpected input".to_owned());
                let mut bad = Vec::new();
                while !self.c.eof() && !self.c.at(SyntaxKind::BRACE_CLOSE) && !self.c.at(SyntaxKind::DOT) {
                    self.c.bump_into(&mut bad);
                }
                children.push(SyntaxElement::Node(Box::new(SyntaxNode::from_children(SyntaxKind::ERROR, bad))));
                continue;
            }
            break;
        }
        self.c.expect_into(SyntaxKind::BRACE_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::CASE_C, children)
    }

    fn can_parse_comp(&self) -> bool {
        self.c.at_any(&[SyntaxKind::KEYWORD_CASE, SyntaxKind::KEYWORD_FIX, SyntaxKind::KEYWORD_FN, SyntaxKind::KEYWORD_FORCE, SyntaxKind::KEYWORD_HANDLE, SyntaxKind::KEYWORD_LET, SyntaxKind::KEYWORD_PERFORM, SyntaxKind::KEYWORD_RET, SyntaxKind::KEYWORD_SEL, SyntaxKind::PAREN_OPEN])
    }
    fn parse_comp(&mut self) -> SyntaxNode {
        self.parse_comp_bp(0)
    }
    fn parse_comp_bp(&mut self, min_bp: u16) -> SyntaxNode {
        let mut lhs = self.parse_comp_atom();
        loop {
            if self.c.at_any(&[SyntaxKind::PAREN_OPEN]) && 110 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.c.bump_into(&mut children);
                children.push(SyntaxElement::Node(Box::new(self.parse_value_args())));
                self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
                lhs = SyntaxNode::from_children(SyntaxKind::COMP_POSTFIX, children);
                continue;
            }
            break;
        }
        lhs
    }
    fn parse_comp_atom(&mut self) -> SyntaxNode {
        if self.can_parse_ret_c() {
            return self.parse_ret_c();
        }
        if self.can_parse_let_c() {
            return self.parse_let_c();
        }
        if self.can_parse_lam_c() {
            return self.parse_lam_c();
        }
        if self.can_parse_force_c() {
            return self.parse_force_c();
        }
        if self.can_parse_case_c() {
            return self.parse_case_c();
        }
        if self.can_parse_fix_c() {
            return self.parse_fix_c();
        }
        if self.can_parse_perform_c() {
            return self.parse_perform_c();
        }
        if self.can_parse_handle_c() {
            return self.parse_handle_c();
        }
        if self.can_parse_sel_c() {
            return self.parse_sel_c();
        }
        if self.can_parse_paren_c() {
            return self.parse_paren_c();
        }
        self.c.error_here("expected Comp".to_owned());
        // Consume one token so enclosing loops make progress.
        if self.c.eof() {
            SyntaxNode::from_children(SyntaxKind::ERROR, Vec::new())
        } else {
            let mut children = Vec::new();
            self.c.bump_into(&mut children);
            SyntaxNode::from_children(SyntaxKind::ERROR, children)
        }
    }

    fn can_parse_ctor_args(&self) -> bool {
        self.c.at(SyntaxKind::PAREN_OPEN)
    }
    fn parse_ctor_args(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        if self.c.at_any(&[SyntaxKind::DOT, SyntaxKind::IDENT, SyntaxKind::KEYWORD_BUNDLE, SyntaxKind::KEYWORD_ROLL, SyntaxKind::KEYWORD_THUNK, SyntaxKind::KEYWORD_UNROLL, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN]) {
            children.push(SyntaxElement::Node(Box::new(self.parse_value())));
            while self.c.at(SyntaxKind::COMMA) {
                self.c.bump_into(&mut children);
                // Trailing separator is allowed.
                if self.c.at_any(&[SyntaxKind::DOT, SyntaxKind::IDENT, SyntaxKind::KEYWORD_BUNDLE, SyntaxKind::KEYWORD_ROLL, SyntaxKind::KEYWORD_THUNK, SyntaxKind::KEYWORD_UNROLL, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN]) {
                    children.push(SyntaxElement::Node(Box::new(self.parse_value())));
                } else {
                    break;
                }
            }
        }
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::CTOR_ARGS, children)
    }

    fn can_parse_ctor_v(&self) -> bool {
        self.c.at(SyntaxKind::DOT)
    }
    fn parse_ctor_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::DOT, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        if self.c.at(SyntaxKind::PAREN_OPEN) {
            children.push(SyntaxElement::Node(Box::new(self.parse_ctor_args())));
        }
        SyntaxNode::from_children(SyntaxKind::CTOR_V, children)
    }

    fn can_parse_def(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_DEF)
    }
    fn parse_def(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_DEF, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        self.c.expect_into(SyntaxKind::OP_EQ, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_value())));
        SyntaxNode::from_children(SyntaxKind::DEF, children)
    }

    fn can_parse_f_type_c(&self) -> bool {
        self.c.at(SyntaxKind::TYPE_F)
    }
    fn parse_f_type_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::TYPE_F, &mut children);
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_type_v())));
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        if self.c.at(SyntaxKind::OP_SLASH) {
            children.push(SyntaxElement::Node(Box::new(self.parse_cap_row())));
        }
        SyntaxNode::from_children(SyntaxKind::F_TYPE_C, children)
    }

    fn can_parse_file(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_DEF)
    }
    fn parse_file(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        loop {
            if self.c.at(SyntaxKind::KEYWORD_DEF) {
                children.push(SyntaxElement::Node(Box::new(self.parse_def())));
                continue;
            }
            if !self.c.eof() && !false {
                self.c.error_here("unexpected input".to_owned());
                let mut bad = Vec::new();
                while !self.c.eof() && !false && !self.c.at(SyntaxKind::KEYWORD_DEF) {
                    self.c.bump_into(&mut bad);
                }
                children.push(SyntaxElement::Node(Box::new(SyntaxNode::from_children(SyntaxKind::ERROR, bad))));
                continue;
            }
            break;
        }
        SyntaxNode::from_children(SyntaxKind::FILE, children)
    }

    fn can_parse_fix_c(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_FIX)
    }
    fn parse_fix_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_FIX, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        self.c.expect_into(SyntaxKind::ARROW_FAT, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_comp())));
        SyntaxNode::from_children(SyntaxKind::FIX_C, children)
    }

    fn can_parse_fn_type_c(&self) -> bool {
        self.c.at(SyntaxKind::PAREN_OPEN)
    }
    fn parse_fn_type_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        if self.c.at_any(&[SyntaxKind::IDENT, SyntaxKind::TYPE_U]) {
            children.push(SyntaxElement::Node(Box::new(self.parse_type_v())));
            while self.c.at(SyntaxKind::COMMA) {
                self.c.bump_into(&mut children);
                // Trailing separator is allowed.
                if self.c.at_any(&[SyntaxKind::IDENT, SyntaxKind::TYPE_U]) {
                    children.push(SyntaxElement::Node(Box::new(self.parse_type_v())));
                } else {
                    break;
                }
            }
        }
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        self.c.expect_into(SyntaxKind::ARROW_THIN, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_type_c())));
        SyntaxNode::from_children(SyntaxKind::FN_TYPE_C, children)
    }

    fn can_parse_forall_type_c(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_FORALL)
    }
    fn parse_forall_type_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_FORALL, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        while self.c.at(SyntaxKind::COMMA) {
            self.c.bump_into(&mut children);
            // Trailing separator is allowed.
            if self.c.at(SyntaxKind::IDENT) {
                self.c.expect_into(SyntaxKind::IDENT, &mut children);
            } else {
                break;
            }
        }
        self.c.expect_into(SyntaxKind::DOT, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_type_c())));
        SyntaxNode::from_children(SyntaxKind::FORALL_TYPE_C, children)
    }

    fn can_parse_force_c(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_FORCE)
    }
    fn parse_force_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_FORCE, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_value())));
        SyntaxNode::from_children(SyntaxKind::FORCE_C, children)
    }

    fn can_parse_handle_c(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_HANDLE)
    }
    fn parse_handle_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_HANDLE, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        self.c.expect_into(SyntaxKind::KEYWORD_WITH, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_value())));
        self.c.expect_into(SyntaxKind::KEYWORD_IN, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_comp())));
        SyntaxNode::from_children(SyntaxKind::HANDLE_C, children)
    }

    fn can_parse_lam_c(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_FN)
    }
    fn parse_lam_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_FN, &mut children);
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        self.c.expect_into(SyntaxKind::ARROW_FAT, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_comp())));
        SyntaxNode::from_children(SyntaxKind::LAM_C, children)
    }

    fn can_parse_let_c(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_LET)
    }
    fn parse_let_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_LET, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        self.c.expect_into(SyntaxKind::OP_EQ, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_comp())));
        self.c.expect_into(SyntaxKind::KEYWORD_IN, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_comp())));
        SyntaxNode::from_children(SyntaxKind::LET_C, children)
    }

    fn can_parse_named_type_v(&self) -> bool {
        self.c.at(SyntaxKind::IDENT)
    }
    fn parse_named_type_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        if self.c.at(SyntaxKind::BRACKET_OPEN) {
            children.push(SyntaxElement::Node(Box::new(self.parse_type_args())));
        }
        SyntaxNode::from_children(SyntaxKind::NAMED_TYPE_V, children)
    }

    fn can_parse_num_v(&self) -> bool {
        self.c.at(SyntaxKind::LIT_NUMBER)
    }
    fn parse_num_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::LIT_NUMBER, &mut children);
        SyntaxNode::from_children(SyntaxKind::NUM_V, children)
    }

    fn can_parse_paren_c(&self) -> bool {
        self.c.at(SyntaxKind::PAREN_OPEN)
    }
    fn parse_paren_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_comp())));
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::PAREN_C, children)
    }

    fn can_parse_paren_v(&self) -> bool {
        self.c.at(SyntaxKind::PAREN_OPEN)
    }
    fn parse_paren_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_value())));
        if self.c.at(SyntaxKind::COLON) {
            self.c.expect_into(SyntaxKind::COLON, &mut children);
            children.push(SyntaxElement::Node(Box::new(self.parse_type_v())));
        }
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::PAREN_V, children)
    }

    fn can_parse_perform_c(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_PERFORM)
    }
    fn parse_perform_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_PERFORM, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        SyntaxNode::from_children(SyntaxKind::PERFORM_C, children)
    }

    fn can_parse_ret_c(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_RET)
    }
    fn parse_ret_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_RET, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_value())));
        SyntaxNode::from_children(SyntaxKind::RET_C, children)
    }

    fn can_parse_roll_v(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_ROLL)
    }
    fn parse_roll_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_ROLL, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_value())));
        SyntaxNode::from_children(SyntaxKind::ROLL_V, children)
    }

    fn can_parse_sel_c(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_SEL)
    }
    fn parse_sel_c(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_SEL, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_value())));
        self.c.expect_into(SyntaxKind::DOT, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        SyntaxNode::from_children(SyntaxKind::SEL_C, children)
    }

    fn can_parse_str_v(&self) -> bool {
        self.c.at(SyntaxKind::LIT_STRING)
    }
    fn parse_str_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::LIT_STRING, &mut children);
        SyntaxNode::from_children(SyntaxKind::STR_V, children)
    }

    fn can_parse_thunk_v(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_THUNK)
    }
    fn parse_thunk_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_THUNK, &mut children);
        self.c.expect_into(SyntaxKind::BRACE_OPEN, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_comp())));
        self.c.expect_into(SyntaxKind::BRACE_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::THUNK_V, children)
    }

    fn can_parse_type_args(&self) -> bool {
        self.c.at(SyntaxKind::BRACKET_OPEN)
    }
    fn parse_type_args(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::BRACKET_OPEN, &mut children);
        if self.c.at_any(&[SyntaxKind::IDENT, SyntaxKind::TYPE_U]) {
            children.push(SyntaxElement::Node(Box::new(self.parse_type_v())));
            while self.c.at(SyntaxKind::COMMA) {
                self.c.bump_into(&mut children);
                // Trailing separator is allowed.
                if self.c.at_any(&[SyntaxKind::IDENT, SyntaxKind::TYPE_U]) {
                    children.push(SyntaxElement::Node(Box::new(self.parse_type_v())));
                } else {
                    break;
                }
            }
        }
        self.c.expect_into(SyntaxKind::BRACKET_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::TYPE_ARGS, children)
    }

    fn can_parse_type_c(&self) -> bool {
        self.c.at_any(&[SyntaxKind::KEYWORD_FORALL, SyntaxKind::PAREN_OPEN, SyntaxKind::TYPE_F])
    }
    fn parse_type_c(&mut self) -> SyntaxNode {
        if self.can_parse_f_type_c() {
            return self.parse_f_type_c();
        }
        if self.can_parse_fn_type_c() {
            return self.parse_fn_type_c();
        }
        if self.can_parse_forall_type_c() {
            return self.parse_forall_type_c();
        }
        self.c.error_here("expected TypeC".to_owned());
        SyntaxNode::from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_type_v(&self) -> bool {
        self.c.at_any(&[SyntaxKind::IDENT, SyntaxKind::TYPE_U])
    }
    fn parse_type_v(&mut self) -> SyntaxNode {
        if self.can_parse_u_type_v() {
            return self.parse_u_type_v();
        }
        if self.can_parse_named_type_v() {
            return self.parse_named_type_v();
        }
        self.c.error_here("expected TypeV".to_owned());
        SyntaxNode::from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_u_type_v(&self) -> bool {
        self.c.at(SyntaxKind::TYPE_U)
    }
    fn parse_u_type_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::TYPE_U, &mut children);
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_type_c())));
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::U_TYPE_V, children)
    }

    fn can_parse_unroll_v(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_UNROLL)
    }
    fn parse_unroll_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_UNROLL, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_value())));
        SyntaxNode::from_children(SyntaxKind::UNROLL_V, children)
    }

    fn can_parse_value(&self) -> bool {
        self.c.at_any(&[SyntaxKind::DOT, SyntaxKind::IDENT, SyntaxKind::KEYWORD_BUNDLE, SyntaxKind::KEYWORD_ROLL, SyntaxKind::KEYWORD_THUNK, SyntaxKind::KEYWORD_UNROLL, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN])
    }
    fn parse_value(&mut self) -> SyntaxNode {
        if self.can_parse_var_v() {
            return self.parse_var_v();
        }
        if self.can_parse_num_v() {
            return self.parse_num_v();
        }
        if self.can_parse_str_v() {
            return self.parse_str_v();
        }
        if self.can_parse_thunk_v() {
            return self.parse_thunk_v();
        }
        if self.can_parse_ctor_v() {
            return self.parse_ctor_v();
        }
        if self.can_parse_roll_v() {
            return self.parse_roll_v();
        }
        if self.can_parse_unroll_v() {
            return self.parse_unroll_v();
        }
        if self.can_parse_bundle_v() {
            return self.parse_bundle_v();
        }
        if self.can_parse_paren_v() {
            return self.parse_paren_v();
        }
        self.c.error_here("expected Value".to_owned());
        SyntaxNode::from_children(SyntaxKind::ERROR, Vec::new())
    }

    fn can_parse_value_args(&self) -> bool {
        self.c.at_any(&[SyntaxKind::DOT, SyntaxKind::IDENT, SyntaxKind::KEYWORD_BUNDLE, SyntaxKind::KEYWORD_ROLL, SyntaxKind::KEYWORD_THUNK, SyntaxKind::KEYWORD_UNROLL, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN])
    }
    fn parse_value_args(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        if self.c.at_any(&[SyntaxKind::DOT, SyntaxKind::IDENT, SyntaxKind::KEYWORD_BUNDLE, SyntaxKind::KEYWORD_ROLL, SyntaxKind::KEYWORD_THUNK, SyntaxKind::KEYWORD_UNROLL, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN]) {
            children.push(SyntaxElement::Node(Box::new(self.parse_value())));
            while self.c.at(SyntaxKind::COMMA) {
                self.c.bump_into(&mut children);
                // Trailing separator is allowed.
                if self.c.at_any(&[SyntaxKind::DOT, SyntaxKind::IDENT, SyntaxKind::KEYWORD_BUNDLE, SyntaxKind::KEYWORD_ROLL, SyntaxKind::KEYWORD_THUNK, SyntaxKind::KEYWORD_UNROLL, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN]) {
                    children.push(SyntaxElement::Node(Box::new(self.parse_value())));
                } else {
                    break;
                }
            }
        }
        SyntaxNode::from_children(SyntaxKind::VALUE_ARGS, children)
    }

    fn can_parse_var_v(&self) -> bool {
        self.c.at(SyntaxKind::IDENT)
    }
    fn parse_var_v(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        SyntaxNode::from_children(SyntaxKind::VAR_V, children)
    }
}
