// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum SyntaxKind { // language `MIR`
    /// an unlexable byte
    UNKNOWN,
    /// a recovery node wrapping skipped input
    ERROR,
    /// token `arrow.fat`
    ARROW_FAT,
    /// token `arrow.thin`
    ARROW_THIN,
    /// token `brace.close`
    BRACE_CLOSE,
    /// token `brace.open`
    BRACE_OPEN,
    /// token `bracket.close`
    BRACKET_CLOSE,
    /// token `bracket.open`
    BRACKET_OPEN,
    /// token `colon`
    COLON,
    /// token `comma`
    COMMA,
    /// token `dot`
    DOT,
    /// token `dotdot`
    DOTDOT,
    /// token `keyword.bundle`
    KEYWORD_BUNDLE,
    /// token `keyword.case`
    KEYWORD_CASE,
    /// token `keyword.def`
    KEYWORD_DEF,
    /// token `keyword.fix`
    KEYWORD_FIX,
    /// token `keyword.fn`
    KEYWORD_FN,
    /// token `keyword.forall`
    KEYWORD_FORALL,
    /// token `keyword.force`
    KEYWORD_FORCE,
    /// token `keyword.handle`
    KEYWORD_HANDLE,
    /// token `keyword.in`
    KEYWORD_IN,
    /// token `keyword.let`
    KEYWORD_LET,
    /// token `keyword.perform`
    KEYWORD_PERFORM,
    /// token `keyword.ret`
    KEYWORD_RET,
    /// token `keyword.roll`
    KEYWORD_ROLL,
    /// token `keyword.sel`
    KEYWORD_SEL,
    /// token `keyword.thunk`
    KEYWORD_THUNK,
    /// token `keyword.unroll`
    KEYWORD_UNROLL,
    /// token `keyword.with`
    KEYWORD_WITH,
    /// token `op.eq`
    OP_EQ,
    /// token `op.slash`
    OP_SLASH,
    /// token `paren.close`
    PAREN_CLOSE,
    /// token `paren.open`
    PAREN_OPEN,
    /// token `semi`
    SEMI,
    /// token `type.f`
    TYPE_F,
    /// token `type.u`
    TYPE_U,
    /// token `comment.line`
    COMMENT_LINE,
    /// token `ident`
    IDENT,
    /// token `lit.number`
    LIT_NUMBER,
    /// token `lit.string`
    LIT_STRING,
    /// token `whitespace`
    WHITESPACE,
    /// rule `BundleClause`
    BUNDLE_CLAUSE,
    /// rule `BundleV`
    BUNDLE_V,
    /// rule `CapEntry`
    CAP_ENTRY,
    /// rule `CapEntryBody`
    CAP_ENTRY_BODY,
    /// rule `CapRest`
    CAP_REST,
    /// rule `CapRow`
    CAP_ROW,
    /// rule `CapSet`
    CAP_SET,
    /// rule `CapSig`
    CAP_SIG,
    /// rule `CaseArm`
    CASE_ARM,
    /// rule `CaseBinders`
    CASE_BINDERS,
    /// rule `CaseC`
    CASE_C,
    /// rule `Comp`
    COMP,
    /// praat row of `Comp`
    COMP_POSTFIX,
    /// rule `CtorArgs`
    CTOR_ARGS,
    /// rule `CtorV`
    CTOR_V,
    /// rule `Def`
    DEF,
    /// rule `FTypeC`
    F_TYPE_C,
    /// rule `File`
    FILE,
    /// rule `FixC`
    FIX_C,
    /// rule `FnTypeC`
    FN_TYPE_C,
    /// rule `ForallTypeC`
    FORALL_TYPE_C,
    /// rule `ForceC`
    FORCE_C,
    /// rule `HandleC`
    HANDLE_C,
    /// rule `LamC`
    LAM_C,
    /// rule `LetC`
    LET_C,
    /// rule `NamedTypeV`
    NAMED_TYPE_V,
    /// rule `NumV`
    NUM_V,
    /// rule `ParenC`
    PAREN_C,
    /// rule `ParenV`
    PAREN_V,
    /// rule `PerformC`
    PERFORM_C,
    /// rule `RetC`
    RET_C,
    /// rule `RollV`
    ROLL_V,
    /// rule `SelC`
    SEL_C,
    /// rule `StrV`
    STR_V,
    /// rule `ThunkV`
    THUNK_V,
    /// rule `TypeArgs`
    TYPE_ARGS,
    /// rule `TypeC`
    TYPE_C,
    /// rule `TypeV`
    TYPE_V,
    /// rule `UTypeV`
    U_TYPE_V,
    /// rule `UnrollV`
    UNROLL_V,
    /// rule `Value`
    VALUE,
    /// rule `ValueArgs`
    VALUE_ARGS,
    /// rule `VarV`
    VAR_V,
}

impl SyntaxKind {
    pub fn is_trivia(self) -> bool {
        matches!(self, SyntaxKind::COMMENT_LINE | SyntaxKind::WHITESPACE)
    }

    /// Dotted token names double as highlight scopes (D-09).
    pub fn highlight_scope(self) -> Option<&'static str> {
        match self {
            SyntaxKind::ARROW_FAT => Some("arrow.fat"),
            SyntaxKind::ARROW_THIN => Some("arrow.thin"),
            SyntaxKind::BRACE_CLOSE => Some("brace.close"),
            SyntaxKind::BRACE_OPEN => Some("brace.open"),
            SyntaxKind::BRACKET_CLOSE => Some("bracket.close"),
            SyntaxKind::BRACKET_OPEN => Some("bracket.open"),
            SyntaxKind::KEYWORD_BUNDLE => Some("keyword.bundle"),
            SyntaxKind::KEYWORD_CASE => Some("keyword.case"),
            SyntaxKind::KEYWORD_DEF => Some("keyword.def"),
            SyntaxKind::KEYWORD_FIX => Some("keyword.fix"),
            SyntaxKind::KEYWORD_FN => Some("keyword.fn"),
            SyntaxKind::KEYWORD_FORALL => Some("keyword.forall"),
            SyntaxKind::KEYWORD_FORCE => Some("keyword.force"),
            SyntaxKind::KEYWORD_HANDLE => Some("keyword.handle"),
            SyntaxKind::KEYWORD_IN => Some("keyword.in"),
            SyntaxKind::KEYWORD_LET => Some("keyword.let"),
            SyntaxKind::KEYWORD_PERFORM => Some("keyword.perform"),
            SyntaxKind::KEYWORD_RET => Some("keyword.ret"),
            SyntaxKind::KEYWORD_ROLL => Some("keyword.roll"),
            SyntaxKind::KEYWORD_SEL => Some("keyword.sel"),
            SyntaxKind::KEYWORD_THUNK => Some("keyword.thunk"),
            SyntaxKind::KEYWORD_UNROLL => Some("keyword.unroll"),
            SyntaxKind::KEYWORD_WITH => Some("keyword.with"),
            SyntaxKind::OP_EQ => Some("op.eq"),
            SyntaxKind::OP_SLASH => Some("op.slash"),
            SyntaxKind::PAREN_CLOSE => Some("paren.close"),
            SyntaxKind::PAREN_OPEN => Some("paren.open"),
            SyntaxKind::TYPE_F => Some("type.f"),
            SyntaxKind::TYPE_U => Some("type.u"),
            SyntaxKind::COMMENT_LINE => Some("comment.line"),
            SyntaxKind::LIT_NUMBER => Some("lit.number"),
            SyntaxKind::LIT_STRING => Some("lit.string"),
            _ => None,
        }
    }
}
