// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.
#![allow(dead_code)]

use super::syntax_kind::SyntaxKind;

/// A praat operand: rendered text plus its root kind, when known.
/// `None` renders defensively (always parenthesized).
pub struct Operand<'a> {
    pub text: &'a str,
    pub kind: Option<SyntaxKind>,
}

fn push(out: &mut String, s: &str) {
    if s.is_empty() {
        return;
    }
    if !out.is_empty() {
        out.push(' ');
    }
    out.push_str(s);
}

/// Render a `ArrayExpr` node as reparseable text.
pub fn array_expr(items: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "[");
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, "]");
    out
}

/// Render a `CallArgs` node as reparseable text.
pub fn call_args(args: &[&str]) -> String {
    let mut out = String::new();
    for (i, item) in args.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    out
}

/// Render a `ConstDecl` node as reparseable text.
pub fn const_decl(name: &str, value: &str) -> String {
    let mut out = String::new();
    push(&mut out, "const");
    push(&mut out, name);
    push(&mut out, "=");
    push(&mut out, value);
    push(&mut out, ";");
    out
}

/// Trailing openness of a `Expr` operand (see module docs).
fn expr_r_bound(kind: Option<SyntaxKind>) -> u16 {
    let Some(kind) = kind else { return 0 };
    match kind {
        SyntaxKind::EXPR_INFIX => 20,
        _ => u16::MAX,
    }
}

fn expr_b_bound(kind: Option<SyntaxKind>) -> u16 {
    let Some(kind) = kind else { return 0 };
    match kind {
        SyntaxKind::EXPR_INFIX => 21,
        SyntaxKind::EXPR_POSTFIX => 30,
        _ => u16::MAX,
    }
}

fn expr_paren(text: &str) -> String {
    panic!("language has no paren atom for `Expr` — cannot wrap {text}")
}

/// Left operand of an operator row: parenthesize iff the row would
/// bind inside it.
fn expr_left(op: Operand, bind: u16) -> String {
    if bind > expr_r_bound(op.kind) {
        expr_paren(op.text)
    } else {
        op.text.to_owned()
    }
}

/// Operand parsed at a known min_bp (prefix/infix right side).
fn expr_at(op: Operand, min_bp: u16) -> String {
    if expr_b_bound(op.kind) <= min_bp {
        expr_paren(op.text)
    } else {
        op.text.to_owned()
    }
}

pub fn expr_postfix_0(expr: Operand, member_name: &str) -> String {
    let mut out = String::new();
    push(&mut out, &expr_left(expr, 110));
    push(&mut out, ".");
    push(&mut out, member_name);
    out
}

pub fn expr_postfix_1(expr: Operand, call_args: &str) -> String {
    let mut out = String::new();
    push(&mut out, &expr_left(expr, 110));
    push(&mut out, "(");
    push(&mut out, call_args);
    push(&mut out, ")");
    out
}

pub fn expr_postfix_2(expr: Operand, index_arg: &str) -> String {
    let mut out = String::new();
    push(&mut out, &expr_left(expr, 110));
    push(&mut out, "[");
    push(&mut out, index_arg);
    push(&mut out, "]");
    out
}

pub fn expr_infix_0(lhs: Operand, op: &str, rhs: Operand) -> String {
    let mut out = String::new();
    debug_assert!(["==="].contains(&op));
    push(&mut out, &expr_left(lhs, 59));
    push(&mut out, op);
    push(&mut out, &expr_at(rhs, 60));
    out
}

pub fn expr_postfix_3(expr: Operand, ternary_tail: &str) -> String {
    let mut out = String::new();
    push(&mut out, &expr_left(expr, 30));
    push(&mut out, "?");
    push(&mut out, ternary_tail);
    out
}

pub fn expr_infix_1(lhs: Operand, op: &str, rhs: Operand) -> String {
    let mut out = String::new();
    debug_assert!(["=>"].contains(&op));
    push(&mut out, &expr_left(lhs, 21));
    push(&mut out, op);
    push(&mut out, &expr_at(rhs, 20));
    out
}

/// Render a `File` node as reparseable text.
pub fn file(stmts: &[&str]) -> String {
    let mut out = String::new();
    for item in stmts {
        push(&mut out, item);
    }
    out
}

/// Render a `FnExpr` node as reparseable text.
pub fn fn_expr(name: &str, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "function");
    push(&mut out, name);
    push(&mut out, "(");
    push(&mut out, ")");
    push(&mut out, "{");
    push(&mut out, "return");
    push(&mut out, body);
    push(&mut out, ";");
    push(&mut out, "}");
    out
}

/// Render a `IdentExpr` node as reparseable text.
pub fn ident_expr(name: &str) -> String {
    let mut out = String::new();
    push(&mut out, name);
    out
}

/// Render a `IndexArg` node as reparseable text.
pub fn index_arg(index: &str) -> String {
    let mut out = String::new();
    push(&mut out, index);
    out
}

/// Render a `MemberName` node as reparseable text.
pub fn member_name(name: &str) -> String {
    let mut out = String::new();
    push(&mut out, name);
    out
}

/// Render a `NumExpr` node as reparseable text.
pub fn num_expr(value: &str) -> String {
    let mut out = String::new();
    push(&mut out, value);
    out
}

/// Render a `ObjectExpr` node as reparseable text.
pub fn object_expr(props: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "{");
    for item in props {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `ObjectProp` node as reparseable text.
pub fn object_prop(name: &str, value: &str) -> String {
    let mut out = String::new();
    push(&mut out, name);
    push(&mut out, ":");
    push(&mut out, value);
    out
}

/// Render a `ParenExpr` node as reparseable text.
pub fn paren_expr(items: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    out
}

/// Render a `StrExpr` node as reparseable text.
pub fn str_expr(value: &str) -> String {
    let mut out = String::new();
    push(&mut out, value);
    out
}

/// Render a `TernaryTail` node as reparseable text.
pub fn ternary_tail(then: &str, alt: &str) -> String {
    let mut out = String::new();
    push(&mut out, then);
    push(&mut out, ":");
    push(&mut out, alt);
    out
}
