// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.

use std::sync::LazyLock;

use langue_rt::LexDfa;

use super::lossless::Token;
use super::syntax_kind::SyntaxKind;

static PATTERNS: &[&str] = &[
    "=>", // arrow.fat
    "\\}", // brace.close
    "\\{", // brace.open
    "\\]", // bracket.close
    "\\[", // bracket.open
    ":", // colon
    ",", // comma
    "\\.", // dot
    "const", // keyword.const
    "function", // keyword.function
    "return", // keyword.return
    "=", // op.assign
    "===", // op.eq3
    "\\)", // paren.close
    "\\(", // paren.open
    "\\?", // question
    ";", // semi
    "//[^\\n]*", // comment.line
    "[a-zA-Z_$][a-zA-Z0-9_$]*", // ident
    "[0-9]+(\\.[0-9]+)?", // lit.number
    "\"([^\"\\\\]|\\\\.)*\"", // lit.string
    "[ \\t\\r\\n]+", // whitespace
];

const KINDS: &[SyntaxKind] = &[
    SyntaxKind::ARROW_FAT,
    SyntaxKind::BRACE_CLOSE,
    SyntaxKind::BRACE_OPEN,
    SyntaxKind::BRACKET_CLOSE,
    SyntaxKind::BRACKET_OPEN,
    SyntaxKind::COLON,
    SyntaxKind::COMMA,
    SyntaxKind::DOT,
    SyntaxKind::KEYWORD_CONST,
    SyntaxKind::KEYWORD_FUNCTION,
    SyntaxKind::KEYWORD_RETURN,
    SyntaxKind::OP_ASSIGN,
    SyntaxKind::OP_EQ3,
    SyntaxKind::PAREN_CLOSE,
    SyntaxKind::PAREN_OPEN,
    SyntaxKind::QUESTION,
    SyntaxKind::SEMI,
    SyntaxKind::COMMENT_LINE,
    SyntaxKind::IDENT,
    SyntaxKind::LIT_NUMBER,
    SyntaxKind::LIT_STRING,
    SyntaxKind::WHITESPACE,
];

static DFA: LazyLock<LexDfa> = LazyLock::new(|| LexDfa::build(PATTERNS));

/// Lossless tokenization: every input byte lands in exactly one
/// token; unlexable bytes become 1-byte UNKNOWN tokens.
pub fn lex(text: &str) -> Vec<Token> {
    DFA.lex(text)
        .into_iter()
        .map(|raw| Token {
            kind: raw.pattern.map_or(SyntaxKind::UNKNOWN, |p| KINDS[p as usize]),
            text: raw.span.slice(text).to_owned(),
            span: raw.span,
        })
        .collect()
}
