// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.
//! Generated modules for language `JS`.

pub mod ast;
pub mod builder;
pub mod lexer;
pub mod lossless;
pub mod parser;
pub mod printer;
pub mod syntax_kind;
