// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.
#![allow(dead_code)]

use langue_rt::Cursor;

use super::lossless::{ParseOutput, SyntaxElement, SyntaxNode};
use super::syntax_kind::SyntaxKind;

pub fn parse(text: &str) -> ParseOutput {
    let tokens = super::lexer::lex(text);
    let mut p = Parser { c: Cursor::new(tokens, SyntaxKind::is_trivia) };
    let mut root = p.parse_file();
    // Losslessness: sweep whatever the start rule left behind.
    let mut rest = Vec::new();
    p.c.drain_rest_into(SyntaxKind::ERROR, &mut rest);
    if !rest.is_empty() {
        let mut children = std::mem::take(&mut root.children);
        children.extend(rest);
        root = SyntaxNode::from_children(root.kind, children);
    }
    ParseOutput { root, errors: std::mem::take(&mut p.c.errors) }
}

struct Parser {
    c: Cursor<SyntaxKind>,
}

impl Parser {
    fn can_parse_array_expr(&self) -> bool {
        self.c.at(SyntaxKind::BRACKET_OPEN)
    }
    fn parse_array_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::BRACKET_OPEN, &mut children);
        if self.c.at_any(&[SyntaxKind::BRACE_OPEN, SyntaxKind::BRACKET_OPEN, SyntaxKind::IDENT, SyntaxKind::KEYWORD_FUNCTION, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN]) {
            children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
            while self.c.at(SyntaxKind::COMMA) {
                self.c.bump_into(&mut children);
                // Trailing separator is allowed.
                if self.c.at_any(&[SyntaxKind::BRACE_OPEN, SyntaxKind::BRACKET_OPEN, SyntaxKind::IDENT, SyntaxKind::KEYWORD_FUNCTION, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN]) {
                    children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
                } else {
                    break;
                }
            }
        }
        self.c.expect_into(SyntaxKind::BRACKET_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::ARRAY_EXPR, children)
    }

    fn can_parse_call_args(&self) -> bool {
        self.c.at_any(&[SyntaxKind::BRACE_OPEN, SyntaxKind::BRACKET_OPEN, SyntaxKind::IDENT, SyntaxKind::KEYWORD_FUNCTION, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN])
    }
    fn parse_call_args(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        if self.c.at_any(&[SyntaxKind::BRACE_OPEN, SyntaxKind::BRACKET_OPEN, SyntaxKind::IDENT, SyntaxKind::KEYWORD_FUNCTION, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN]) {
            children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
            while self.c.at(SyntaxKind::COMMA) {
                self.c.bump_into(&mut children);
                // Trailing separator is allowed.
                if self.c.at_any(&[SyntaxKind::BRACE_OPEN, SyntaxKind::BRACKET_OPEN, SyntaxKind::IDENT, SyntaxKind::KEYWORD_FUNCTION, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN]) {
                    children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
                } else {
                    break;
                }
            }
        }
        SyntaxNode::from_children(SyntaxKind::CALL_ARGS, children)
    }

    fn can_parse_const_decl(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_CONST)
    }
    fn parse_const_decl(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_CONST, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        self.c.expect_into(SyntaxKind::OP_ASSIGN, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        self.c.expect_into(SyntaxKind::SEMI, &mut children);
        SyntaxNode::from_children(SyntaxKind::CONST_DECL, children)
    }

    fn can_parse_expr(&self) -> bool {
        self.c.at_any(&[SyntaxKind::BRACE_OPEN, SyntaxKind::BRACKET_OPEN, SyntaxKind::IDENT, SyntaxKind::KEYWORD_FUNCTION, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN])
    }
    fn parse_expr(&mut self) -> SyntaxNode {
        self.parse_expr_bp(0)
    }
    fn parse_expr_bp(&mut self, min_bp: u16) -> SyntaxNode {
        let mut lhs = self.parse_expr_atom();
        loop {
            if self.c.at_any(&[SyntaxKind::DOT]) && 110 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.c.bump_into(&mut children);
                children.push(SyntaxElement::Node(Box::new(self.parse_member_name())));
                lhs = SyntaxNode::from_children(SyntaxKind::EXPR_POSTFIX, children);
                continue;
            }
            if self.c.at_any(&[SyntaxKind::PAREN_OPEN]) && 110 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.c.bump_into(&mut children);
                children.push(SyntaxElement::Node(Box::new(self.parse_call_args())));
                self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
                lhs = SyntaxNode::from_children(SyntaxKind::EXPR_POSTFIX, children);
                continue;
            }
            if self.c.at_any(&[SyntaxKind::BRACKET_OPEN]) && 110 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.c.bump_into(&mut children);
                children.push(SyntaxElement::Node(Box::new(self.parse_index_arg())));
                self.c.expect_into(SyntaxKind::BRACKET_CLOSE, &mut children);
                lhs = SyntaxNode::from_children(SyntaxKind::EXPR_POSTFIX, children);
                continue;
            }
            if self.c.at_any(&[SyntaxKind::OP_EQ3]) && 59 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.c.bump_into(&mut children);
                children.push(SyntaxElement::Node(Box::new(self.parse_expr_bp(60))));
                lhs = SyntaxNode::from_children(SyntaxKind::EXPR_INFIX, children);
                continue;
            }
            if self.c.at_any(&[SyntaxKind::QUESTION]) && 30 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.c.bump_into(&mut children);
                children.push(SyntaxElement::Node(Box::new(self.parse_ternary_tail())));
                lhs = SyntaxNode::from_children(SyntaxKind::EXPR_POSTFIX, children);
                continue;
            }
            if self.c.at_any(&[SyntaxKind::ARROW_FAT]) && 21 > min_bp {
                let mut children = vec![SyntaxElement::Node(Box::new(lhs))];
                self.c.bump_into(&mut children);
                children.push(SyntaxElement::Node(Box::new(self.parse_expr_bp(20))));
                lhs = SyntaxNode::from_children(SyntaxKind::EXPR_INFIX, children);
                continue;
            }
            break;
        }
        lhs
    }
    fn parse_expr_atom(&mut self) -> SyntaxNode {
        if self.can_parse_ident_expr() {
            return self.parse_ident_expr();
        }
        if self.can_parse_num_expr() {
            return self.parse_num_expr();
        }
        if self.can_parse_str_expr() {
            return self.parse_str_expr();
        }
        if self.can_parse_paren_expr() {
            return self.parse_paren_expr();
        }
        if self.can_parse_object_expr() {
            return self.parse_object_expr();
        }
        if self.can_parse_array_expr() {
            return self.parse_array_expr();
        }
        if self.can_parse_fn_expr() {
            return self.parse_fn_expr();
        }
        self.c.error_here("expected Expr".to_owned());
        // Consume one token so enclosing loops make progress.
        if self.c.eof() {
            SyntaxNode::from_children(SyntaxKind::ERROR, Vec::new())
        } else {
            let mut children = Vec::new();
            self.c.bump_into(&mut children);
            SyntaxNode::from_children(SyntaxKind::ERROR, children)
        }
    }

    fn can_parse_file(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_CONST)
    }
    fn parse_file(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        loop {
            if self.c.at(SyntaxKind::KEYWORD_CONST) {
                children.push(SyntaxElement::Node(Box::new(self.parse_const_decl())));
                continue;
            }
            if !self.c.eof() && !false {
                self.c.error_here("unexpected input".to_owned());
                let mut bad = Vec::new();
                while !self.c.eof() && !false && !self.c.at(SyntaxKind::KEYWORD_CONST) {
                    self.c.bump_into(&mut bad);
                }
                children.push(SyntaxElement::Node(Box::new(SyntaxNode::from_children(SyntaxKind::ERROR, bad))));
                continue;
            }
            break;
        }
        SyntaxNode::from_children(SyntaxKind::FILE, children)
    }

    fn can_parse_fn_expr(&self) -> bool {
        self.c.at(SyntaxKind::KEYWORD_FUNCTION)
    }
    fn parse_fn_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::KEYWORD_FUNCTION, &mut children);
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        self.c.expect_into(SyntaxKind::BRACE_OPEN, &mut children);
        self.c.expect_into(SyntaxKind::KEYWORD_RETURN, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        self.c.expect_into(SyntaxKind::SEMI, &mut children);
        self.c.expect_into(SyntaxKind::BRACE_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::FN_EXPR, children)
    }

    fn can_parse_ident_expr(&self) -> bool {
        self.c.at(SyntaxKind::IDENT)
    }
    fn parse_ident_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        SyntaxNode::from_children(SyntaxKind::IDENT_EXPR, children)
    }

    fn can_parse_index_arg(&self) -> bool {
        self.c.at_any(&[SyntaxKind::BRACE_OPEN, SyntaxKind::BRACKET_OPEN, SyntaxKind::IDENT, SyntaxKind::KEYWORD_FUNCTION, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN])
    }
    fn parse_index_arg(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        SyntaxNode::from_children(SyntaxKind::INDEX_ARG, children)
    }

    fn can_parse_member_name(&self) -> bool {
        self.c.at(SyntaxKind::IDENT)
    }
    fn parse_member_name(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        SyntaxNode::from_children(SyntaxKind::MEMBER_NAME, children)
    }

    fn can_parse_num_expr(&self) -> bool {
        self.c.at(SyntaxKind::LIT_NUMBER)
    }
    fn parse_num_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::LIT_NUMBER, &mut children);
        SyntaxNode::from_children(SyntaxKind::NUM_EXPR, children)
    }

    fn can_parse_object_expr(&self) -> bool {
        self.c.at(SyntaxKind::BRACE_OPEN)
    }
    fn parse_object_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::BRACE_OPEN, &mut children);
        if self.c.at(SyntaxKind::IDENT) {
            children.push(SyntaxElement::Node(Box::new(self.parse_object_prop())));
            while self.c.at(SyntaxKind::COMMA) {
                self.c.bump_into(&mut children);
                // Trailing separator is allowed.
                if self.c.at(SyntaxKind::IDENT) {
                    children.push(SyntaxElement::Node(Box::new(self.parse_object_prop())));
                } else {
                    break;
                }
            }
        }
        self.c.expect_into(SyntaxKind::BRACE_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::OBJECT_EXPR, children)
    }

    fn can_parse_object_prop(&self) -> bool {
        self.c.at(SyntaxKind::IDENT)
    }
    fn parse_object_prop(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::IDENT, &mut children);
        self.c.expect_into(SyntaxKind::COLON, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        SyntaxNode::from_children(SyntaxKind::OBJECT_PROP, children)
    }

    fn can_parse_paren_expr(&self) -> bool {
        self.c.at(SyntaxKind::PAREN_OPEN)
    }
    fn parse_paren_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::PAREN_OPEN, &mut children);
        if self.c.at_any(&[SyntaxKind::BRACE_OPEN, SyntaxKind::BRACKET_OPEN, SyntaxKind::IDENT, SyntaxKind::KEYWORD_FUNCTION, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN]) {
            children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
            while self.c.at(SyntaxKind::COMMA) {
                self.c.bump_into(&mut children);
                // Trailing separator is allowed.
                if self.c.at_any(&[SyntaxKind::BRACE_OPEN, SyntaxKind::BRACKET_OPEN, SyntaxKind::IDENT, SyntaxKind::KEYWORD_FUNCTION, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN]) {
                    children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
                } else {
                    break;
                }
            }
        }
        self.c.expect_into(SyntaxKind::PAREN_CLOSE, &mut children);
        SyntaxNode::from_children(SyntaxKind::PAREN_EXPR, children)
    }

    fn can_parse_str_expr(&self) -> bool {
        self.c.at(SyntaxKind::LIT_STRING)
    }
    fn parse_str_expr(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        self.c.expect_into(SyntaxKind::LIT_STRING, &mut children);
        SyntaxNode::from_children(SyntaxKind::STR_EXPR, children)
    }

    fn can_parse_ternary_tail(&self) -> bool {
        self.c.at_any(&[SyntaxKind::BRACE_OPEN, SyntaxKind::BRACKET_OPEN, SyntaxKind::IDENT, SyntaxKind::KEYWORD_FUNCTION, SyntaxKind::LIT_NUMBER, SyntaxKind::LIT_STRING, SyntaxKind::PAREN_OPEN])
    }
    fn parse_ternary_tail(&mut self) -> SyntaxNode {
        let mut children = Vec::new();
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        self.c.expect_into(SyntaxKind::COLON, &mut children);
        children.push(SyntaxElement::Node(Box::new(self.parse_expr())));
        SyntaxNode::from_children(SyntaxKind::TERNARY_TAIL, children)
    }
}
