// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum SyntaxKind { // language `JS`
    /// an unlexable byte
    UNKNOWN,
    /// a recovery node wrapping skipped input
    ERROR,
    /// token `arrow.fat`
    ARROW_FAT,
    /// token `brace.close`
    BRACE_CLOSE,
    /// token `brace.open`
    BRACE_OPEN,
    /// token `bracket.close`
    BRACKET_CLOSE,
    /// token `bracket.open`
    BRACKET_OPEN,
    /// token `colon`
    COLON,
    /// token `comma`
    COMMA,
    /// token `dot`
    DOT,
    /// token `keyword.const`
    KEYWORD_CONST,
    /// token `keyword.function`
    KEYWORD_FUNCTION,
    /// token `keyword.return`
    KEYWORD_RETURN,
    /// token `op.assign`
    OP_ASSIGN,
    /// token `op.eq3`
    OP_EQ3,
    /// token `paren.close`
    PAREN_CLOSE,
    /// token `paren.open`
    PAREN_OPEN,
    /// token `question`
    QUESTION,
    /// token `semi`
    SEMI,
    /// token `comment.line`
    COMMENT_LINE,
    /// token `ident`
    IDENT,
    /// token `lit.number`
    LIT_NUMBER,
    /// token `lit.string`
    LIT_STRING,
    /// token `whitespace`
    WHITESPACE,
    /// rule `ArrayExpr`
    ARRAY_EXPR,
    /// rule `CallArgs`
    CALL_ARGS,
    /// rule `ConstDecl`
    CONST_DECL,
    /// rule `Expr`
    EXPR,
    /// praat row of `Expr`
    EXPR_INFIX,
    /// praat row of `Expr`
    EXPR_POSTFIX,
    /// rule `File`
    FILE,
    /// rule `FnExpr`
    FN_EXPR,
    /// rule `IdentExpr`
    IDENT_EXPR,
    /// rule `IndexArg`
    INDEX_ARG,
    /// rule `MemberName`
    MEMBER_NAME,
    /// rule `NumExpr`
    NUM_EXPR,
    /// rule `ObjectExpr`
    OBJECT_EXPR,
    /// rule `ObjectProp`
    OBJECT_PROP,
    /// rule `ParenExpr`
    PAREN_EXPR,
    /// rule `StrExpr`
    STR_EXPR,
    /// rule `TernaryTail`
    TERNARY_TAIL,
}

impl SyntaxKind {
    pub fn is_trivia(self) -> bool {
        matches!(self, SyntaxKind::COMMENT_LINE | SyntaxKind::WHITESPACE)
    }

    /// Dotted token names double as highlight scopes (D-09).
    pub fn highlight_scope(self) -> Option<&'static str> {
        match self {
            SyntaxKind::ARROW_FAT => Some("arrow.fat"),
            SyntaxKind::BRACE_CLOSE => Some("brace.close"),
            SyntaxKind::BRACE_OPEN => Some("brace.open"),
            SyntaxKind::BRACKET_CLOSE => Some("bracket.close"),
            SyntaxKind::BRACKET_OPEN => Some("bracket.open"),
            SyntaxKind::KEYWORD_CONST => Some("keyword.const"),
            SyntaxKind::KEYWORD_FUNCTION => Some("keyword.function"),
            SyntaxKind::KEYWORD_RETURN => Some("keyword.return"),
            SyntaxKind::OP_ASSIGN => Some("op.assign"),
            SyntaxKind::OP_EQ3 => Some("op.eq3"),
            SyntaxKind::PAREN_CLOSE => Some("paren.close"),
            SyntaxKind::PAREN_OPEN => Some("paren.open"),
            SyntaxKind::COMMENT_LINE => Some("comment.line"),
            SyntaxKind::LIT_NUMBER => Some("lit.number"),
            SyntaxKind::LIT_STRING => Some("lit.string"),
            _ => None,
        }
    }
}
