//! Deterministic Rust emitters (D-21). Everything iterates BTree-ordered
//! collections, so `langc gen` is byte-stable for a given definition.

pub mod ast;
pub mod between;
pub mod builder;
pub mod elab;
pub mod lexer;
pub mod lossless;
pub mod naming;
pub mod parser;
pub mod printer;
pub mod registry;
pub mod syntax_kind;

use crate::project::model::{Definition, Language, TokenDef};
use crate::syntax::ast::TokenPattern;

pub const HEADER: &str = "// Auto-generated by `langc gen`. Do not edit.\n\
                          // The definition under `lumo/` is the source of truth.\n";

/// `(relative path, content)` pairs, ready to write under the `-o` dir.
pub fn generate(def: &Definition) -> Vec<(String, String)> {
    let mut files = Vec::new();
    for (lang_name, lang) in &def.languages {
        let module = naming::module_name(lang_name);
        let between_def = def.betweens.get(lang_name);
        files.push((format!("{module}/mod.rs"), language_mod(lang_name, between_def.is_some())));
        if let Some(between_def) = between_def {
            files.push((
                format!("{module}/between.rs"),
                between::generate(lang_name, lang, between_def),
            ));
        }
        files.push((
            format!("{module}/syntax_kind.rs"),
            syntax_kind::generate(lang_name, lang),
        ));
        files.push((format!("{module}/ast.rs"), ast::generate(lang)));
        files.push((format!("{module}/builder.rs"), builder::generate(lang)));
        files.push((format!("{module}/lexer.rs"), lexer::generate(lang)));
        files.push((format!("{module}/lossless.rs"), lossless::generate()));
        files.push((format!("{module}/parser.rs"), parser::generate(lang)));
        files.push((format!("{module}/printer.rs"), printer::generate()));
    }
    if !def.elabs.is_empty() {
        files.push(("elab/mod.rs".to_owned(), elab::generate_mod(def)));
        for ((from, to), elab_def) in &def.elabs {
            files.push((
                format!("elab/{}.rs", elab::pair_module(from, to)),
                elab::generate_pair(def, from, to, elab_def),
            ));
        }
    }
    files.push(("registry.rs".to_owned(), registry::generate(def)));
    files
}

fn language_mod(lang_name: &str, has_between: bool) -> String {
    let mut buf = Buf::new();
    buf.line(&format!("//! Generated modules for language `{lang_name}`."));
    buf.blank();
    buf.line("pub mod ast;");
    if has_between {
        buf.line("pub mod between;");
    }
    buf.line("pub mod builder;");
    buf.line("pub mod lexer;");
    buf.line("pub mod lossless;");
    buf.line("pub mod parser;");
    buf.line("pub mod printer;");
    buf.line("pub mod syntax_kind;");
    buf.finish()
}

/// Pattern order for the one-DFA-per-language lexer table (D-09):
/// literals first (so a literal wins length ties via smallest pattern
/// index), each group sorted by token name.
pub fn token_order(lang: &Language) -> Vec<&TokenDef> {
    let mut literals = Vec::new();
    let mut regexes = Vec::new();
    for token in lang.tokens.values() {
        match &token.pattern {
            TokenPattern::Literal(_) => literals.push(token),
            TokenPattern::Regex(_) => regexes.push(token),
        }
    }
    literals.into_iter().chain(regexes).collect()
}

/// Tiny indent writer shared by all emitters.
pub struct Buf {
    out: String,
    indent: usize,
}

impl Buf {
    pub fn new() -> Buf {
        Buf { out: HEADER.to_owned(), indent: 0 }
    }

    pub fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    pub fn blank(&mut self) {
        self.out.push('\n');
    }

    /// `line` + increase indent — for `foo {`.
    pub fn open(&mut self, s: &str) {
        self.line(s);
        self.indent += 1;
    }

    /// Decrease indent + `line` — for `}`.
    pub fn close(&mut self, s: &str) {
        self.indent -= 1;
        self.line(s);
    }

    /// Dedent, print, re-indent — for `} else {` / `} else if x {`.
    pub fn else_open(&mut self, s: &str) {
        self.indent -= 1;
        self.line(s);
        self.indent += 1;
    }

    pub fn finish(self) -> String {
        self.out
    }
}

impl Default for Buf {
    fn default() -> Self {
        Buf::new()
    }
}
