// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.
#![allow(dead_code, unused_variables, unused_mut, clippy::all)]

use langue_rt::{ElabCtx, ElabReport, PassPhase};

use crate::lumo::lossless::SyntaxNode as FromNode;
use crate::lumo::syntax_kind::SyntaxKind as FromKind;
use crate::mir::builder;
use crate::mir::syntax_kind::SyntaxKind as ToKind;

pub type ToFrag = langue_rt::Frag<ToKind>;

/// Extern hooks (D-01/D-38). Rules and passes declared in the
/// definition have no default body — the Rust implementation is
/// mandatory, which is the extern coverage check. Provide it as
/// `crate::elab_externs::lumo_to_mir() -> Box<dyn Externs>`.
pub trait Externs {
    /// Called with the parsed source before rule dispatch.
    fn init(&mut self, _root: &FromNode) {}

    /// D-38 sort coercion: turn `frag` into something acceptable where
    /// `expected` is required (typically bind a computation to a fresh
    /// value via `ctx.fresh()` and return the variable as a frag whose
    /// `pending` carries the binder). `None` = not coercible.
    fn coerce(&mut self, _ctx: &mut ElabCtx, _expected: &'static str, _frag: &ToFrag) -> Option<ToFrag> {
        None
    }

    /// Nodes at which pending coercion binders are inserted.
    fn is_binder_site(&mut self, _kind: ToKind) -> bool {
        false
    }

    /// Wrap `body` in binders for `pending` (outermost first); returns
    /// the new text and its root kind.
    fn wrap_pending(&mut self, _pending: &[(String, String)], body: &str, kind: ToKind) -> (String, ToKind) {
        (body.to_owned(), kind)
    }

    /// `extern rule module from Lumo to MIR`
    fn rule_module(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern rule fn_curry from Lumo to MIR`
    fn rule_fn_curry(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern rule block from Lumo to MIR`
    fn rule_block(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern rule match_arm from Lumo to MIR`
    fn rule_match_arm(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern rule member_classify from Lumo to MIR`
    fn rule_member_classify(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern rule use_decl from Lumo to MIR`
    fn rule_use_decl(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern pass scc_fix` — offered both phases; `None` = skip.
    fn pass_scc_fix(&mut self, phase: PassPhase, text: &str) -> Option<String>;

    /// `extern pass use_require` — offered both phases; `None` = skip.
    fn pass_use_require(&mut self, phase: PassPhase, text: &str) -> Option<String>;
}

/// Run `elab Lumo to MIR` end to end over source text.
pub fn elab(text: &str, externs: &mut dyn Externs) -> ElabReport {
    let mut errors: Vec<String> = Vec::new();
    let mut src = text.to_owned();
    if let Some(t) = externs.pass_scc_fix(PassPhase::PreSource, &src) {
        src = t;
    }
    if let Some(t) = externs.pass_use_require(PassPhase::PreSource, &src) {
        src = t;
    }
    let parsed = crate::lumo::parser::parse(&src);
    errors.extend(parsed.errors.iter().map(|e| format!("Lumo: {} at {}", e.message, e.span)));
    let mut ctx = ElabCtx::new();
    externs.init(&parsed.root);
    let mut output = String::new();
    match elab_node(&mut ctx, externs, &parsed.root) {
        Some(frag) => {
            if !frag.pending.is_empty() {
                ctx.error("dangling coercion binders at the root".to_owned());
            }
            output = frag.text;
        }
        None => ctx.error("elaboration produced no output".to_owned()),
    }
    errors.append(&mut ctx.errors);
    if let Some(t) = externs.pass_scc_fix(PassPhase::PostTarget, &output) {
        output = t;
    }
    if let Some(t) = externs.pass_use_require(PassPhase::PostTarget, &output) {
        output = t;
    }
    let reparsed = crate::mir::parser::parse(&output);
    errors.extend(reparsed.errors.iter().map(|e| format!("MIR: {} at {} in `{output}`", e.message, e.span)));
    ElabReport {
        output: crate::mir::printer::canonical(&reparsed.root),
        errors,
    }
}

/// Top-down dispatch by root kind. Extern rules go first, in
/// declaration order (they see every node and decline with `None`).
pub fn elab_node(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if let Some(frag) = externs.rule_module(ctx, node) {
        return Some(frag);
    }
    if let Some(frag) = externs.rule_fn_curry(ctx, node) {
        return Some(frag);
    }
    if let Some(frag) = externs.rule_block(ctx, node) {
        return Some(frag);
    }
    if let Some(frag) = externs.rule_match_arm(ctx, node) {
        return Some(frag);
    }
    if let Some(frag) = externs.rule_member_classify(ctx, node) {
        return Some(frag);
    }
    if let Some(frag) = externs.rule_use_decl(ctx, node) {
        return Some(frag);
    }
    match node.kind {
        FromKind::BIND_PATTERN => {
            if let Some(frag) = rule_13(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `BIND_PATTERN`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::BUNDLE_ENTRY => {
            if let Some(frag) = rule_11(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `BUNDLE_ENTRY`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::BUNDLE_EXPR => {
            if let Some(frag) = rule_10(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `BUNDLE_EXPR`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::EXPR_BODY => {
            if let Some(frag) = rule_7(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `EXPR_BODY`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::EXPR_POSTFIX => {
            if let Some(frag) = rule_16(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `EXPR_POSTFIX`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::FORCE_EXPR => {
            if let Some(frag) = rule_4(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `FORCE_EXPR`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::HANDLE_EXPR => {
            if let Some(frag) = rule_9(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `HANDLE_EXPR`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::IDENT_EXPR => {
            if let Some(frag) = rule_2(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `IDENT_EXPR`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::IDENT_PATTERN => {
            if let Some(frag) = rule_14(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `IDENT_PATTERN`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::MATCH_EXPR => {
            if let Some(frag) = rule_8(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `MATCH_EXPR`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::NUMBER_EXPR => {
            if let Some(frag) = rule_0(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `NUMBER_EXPR`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::PARAM => {
            if let Some(frag) = rule_12(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `PARAM`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::PAREN_EXPR => {
            if let Some(frag) = rule_6(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `PAREN_EXPR`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::PERFORM_EXPR => {
            if let Some(frag) = rule_5(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `PERFORM_EXPR`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::STRING_EXPR => {
            if let Some(frag) = rule_1(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `STRING_EXPR`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::THUNK_EXPR => {
            if let Some(frag) = rule_3(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `THUNK_EXPR`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        FromKind::WILDCARD_PATTERN => {
            if let Some(frag) = rule_15(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `WILDCARD_PATTERN`: {}", crate::lumo::printer::canonical(node)));
            None
        }
        other => {
            ctx.error(format!("no elab rule for `{other:?}`"));
            None
        }
    }
}

/// A frag placed where `kinds` (the concrete kinds of `expected`)
/// are required: pass through, coerce (D-38), or error.
fn expect_kind(ctx: &mut ElabCtx, externs: &mut dyn Externs, frag: ToFrag, kinds: &[ToKind], expected: &'static str) -> Option<ToFrag> {
    match frag.kind {
        None => Some(frag),
        Some(k) if kinds.contains(&k) => Some(frag),
        Some(k) => match externs.coerce(ctx, expected, &frag) {
            Some(mut coerced) => {
                let mut pending = frag.pending;
                pending.append(&mut coerced.pending);
                coerced.pending = pending;
                Some(coerced)
            }
            None => {
                ctx.error(format!("cannot place `{k:?}` where `{expected}` is expected: {}", frag.text));
                None
            }
        },
    }
}

/// Flush pending binders at a binder-site node (D-38).
fn flush_binders(externs: &mut dyn Externs, frag: &mut ToFrag) {
    if let Some(kind) = frag.kind {
        if !frag.pending.is_empty() && externs.is_binder_site(kind) {
            let (text, new_kind) = externs.wrap_pending(&frag.pending, &frag.text, kind);
            frag.text = text;
            frag.kind = Some(new_kind);
            frag.pending.clear();
        }
    }
}

/// Rule 0: `NumberExpr` ==> …
fn rule_0(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::NUMBER_EXPR {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::LIT_NUMBER, 0)?;
    let b_v = t0;
    let mut c2 = ToFrag::token(b_v.text.clone());
    let mut r3 = ToFrag::node(ToKind::NUM_V, builder::num_v(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 1: `StringExpr` ==> …
fn rule_1(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::STRING_EXPR {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::LIT_STRING, 0)?;
    let b_v = t0;
    let mut c2 = ToFrag::token(b_v.text.clone());
    let mut r3 = ToFrag::node(ToKind::STR_V, builder::str_v(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 2: `IdentExpr` ==> …
fn rule_2(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::IDENT_EXPR {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::IDENT, 0)?;
    let b_n = t0;
    let mut c2 = ToFrag::token(b_n.text.clone());
    let mut r3 = ToFrag::node(ToKind::VAR_V, builder::var_v(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 3: `ThunkExpr` ==> …
fn rule_3(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::THUNK_EXPR {
        return None;
    }
    let b_b = langue_rt::nth_node_in(node, &[FromKind::BLOCK_EXPR, FromKind::BUNDLE_EXPR, FromKind::EXPR_INFIX, FromKind::EXPR_POSTFIX, FromKind::EXPR_PREFIX, FromKind::FORCE_EXPR, FromKind::HANDLE_EXPR, FromKind::IDENT_EXPR, FromKind::IF_ELSE_EXPR, FromKind::LAMBDA_EXPR, FromKind::MATCH_EXPR, FromKind::NUMBER_EXPR, FromKind::PAREN_EXPR, FromKind::PERFORM_EXPR, FromKind::STRING_EXPR, FromKind::THUNK_EXPR], 0)?;
    let mut c1 = elab_node(ctx, externs, b_b)?;
    let mut c1 = expect_kind(ctx, externs, c1, &[ToKind::CASE_C, ToKind::COMP_POSTFIX, ToKind::FIX_C, ToKind::FORCE_C, ToKind::HANDLE_C, ToKind::LAM_C, ToKind::LET_C, ToKind::PAREN_C, ToKind::PERFORM_C, ToKind::RET_C, ToKind::SEL_C], "Comp")?;
    let mut r2 = ToFrag::node(ToKind::THUNK_V, builder::thunk_v(&c1.text));
    r2.absorb(&mut c1);
    flush_binders(externs, &mut r2);
    Some(r2)
}

/// Rule 4: `ForceExpr` ==> …
fn rule_4(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::FORCE_EXPR {
        return None;
    }
    let b_e = langue_rt::nth_node_in(node, &[FromKind::BLOCK_EXPR, FromKind::BUNDLE_EXPR, FromKind::EXPR_INFIX, FromKind::EXPR_POSTFIX, FromKind::EXPR_PREFIX, FromKind::FORCE_EXPR, FromKind::HANDLE_EXPR, FromKind::IDENT_EXPR, FromKind::IF_ELSE_EXPR, FromKind::LAMBDA_EXPR, FromKind::MATCH_EXPR, FromKind::NUMBER_EXPR, FromKind::PAREN_EXPR, FromKind::PERFORM_EXPR, FromKind::STRING_EXPR, FromKind::THUNK_EXPR], 0)?;
    let mut c1 = elab_node(ctx, externs, b_e)?;
    let mut c1 = expect_kind(ctx, externs, c1, &[ToKind::BUNDLE_V, ToKind::CTOR_V, ToKind::NUM_V, ToKind::PAREN_V, ToKind::ROLL_V, ToKind::STR_V, ToKind::THUNK_V, ToKind::UNROLL_V, ToKind::VAR_V], "Value")?;
    let mut r2 = ToFrag::node(ToKind::FORCE_C, builder::force_c(&c1.text));
    r2.absorb(&mut c1);
    flush_binders(externs, &mut r2);
    Some(r2)
}

/// Rule 5: `PerformExpr` ==> …
fn rule_5(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::PERFORM_EXPR {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::IDENT, 0)?;
    let b_c = t0;
    let mut c2 = ToFrag::token(b_c.text.clone());
    let mut r3 = ToFrag::node(ToKind::PERFORM_C, builder::perform_c(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 6: `ParenExpr` ==> …
fn rule_6(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::PAREN_EXPR {
        return None;
    }
    let b_e = langue_rt::nth_node_in(node, &[FromKind::BLOCK_EXPR, FromKind::BUNDLE_EXPR, FromKind::EXPR_INFIX, FromKind::EXPR_POSTFIX, FromKind::EXPR_PREFIX, FromKind::FORCE_EXPR, FromKind::HANDLE_EXPR, FromKind::IDENT_EXPR, FromKind::IF_ELSE_EXPR, FromKind::LAMBDA_EXPR, FromKind::MATCH_EXPR, FromKind::NUMBER_EXPR, FromKind::PAREN_EXPR, FromKind::PERFORM_EXPR, FromKind::STRING_EXPR, FromKind::THUNK_EXPR], 0)?;
    let mut c0 = elab_node(ctx, externs, b_e)?;
    Some(c0)
}

/// Rule 7: `ExprBody` ==> …
fn rule_7(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::EXPR_BODY {
        return None;
    }
    let b_e = langue_rt::nth_node_in(node, &[FromKind::BLOCK_EXPR, FromKind::BUNDLE_EXPR, FromKind::EXPR_INFIX, FromKind::EXPR_POSTFIX, FromKind::EXPR_PREFIX, FromKind::FORCE_EXPR, FromKind::HANDLE_EXPR, FromKind::IDENT_EXPR, FromKind::IF_ELSE_EXPR, FromKind::LAMBDA_EXPR, FromKind::MATCH_EXPR, FromKind::NUMBER_EXPR, FromKind::PAREN_EXPR, FromKind::PERFORM_EXPR, FromKind::STRING_EXPR, FromKind::THUNK_EXPR], 0)?;
    let mut c0 = elab_node(ctx, externs, b_e)?;
    Some(c0)
}

/// Rule 8: `MatchExpr` ==> …
fn rule_8(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::MATCH_EXPR {
        return None;
    }
    let b_s = langue_rt::nth_node_in(node, &[FromKind::BLOCK_EXPR, FromKind::BUNDLE_EXPR, FromKind::EXPR_INFIX, FromKind::EXPR_POSTFIX, FromKind::EXPR_PREFIX, FromKind::FORCE_EXPR, FromKind::HANDLE_EXPR, FromKind::IDENT_EXPR, FromKind::IF_ELSE_EXPR, FromKind::LAMBDA_EXPR, FromKind::MATCH_EXPR, FromKind::NUMBER_EXPR, FromKind::PAREN_EXPR, FromKind::PERFORM_EXPR, FromKind::STRING_EXPR, FromKind::THUNK_EXPR], 0)?;
    let b_a = langue_rt::nodes_in(node, &[FromKind::MATCH_ARM], 0);
    let mut c2 = elab_node(ctx, externs, b_s)?;
    let mut c2 = expect_kind(ctx, externs, c2, &[ToKind::BUNDLE_V, ToKind::CTOR_V, ToKind::NUM_V, ToKind::PAREN_V, ToKind::ROLL_V, ToKind::STR_V, ToKind::THUNK_V, ToKind::UNROLL_V, ToKind::VAR_V], "Value")?;
    let mut r3 = ToFrag::node(ToKind::UNROLL_V, builder::unroll_v(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    let mut l4: Vec<ToFrag> = Vec::new();
    for n in &b_a {
        let f = elab_node(ctx, externs, n)?;
        let f = expect_kind(ctx, externs, f, &[ToKind::CASE_ARM], "CaseArm")?;
        l4.push(f);
    }
    let texts5: Vec<&str> = l4.iter().map(|f| f.text.as_str()).collect();
    let mut r6 = ToFrag::node(ToKind::CASE_C, builder::case_c(&r3.text, &texts5));
    r6.absorb(&mut r3);
    for f in &mut l4 {
        r6.absorb(f);
    }
    flush_binders(externs, &mut r6);
    Some(r6)
}

/// Rule 9: `HandleExpr` ==> …
fn rule_9(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::HANDLE_EXPR {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::IDENT, 0)?;
    let b_c = t0;
    let b_h = langue_rt::nth_node_in(node, &[FromKind::BLOCK_EXPR, FromKind::BUNDLE_EXPR, FromKind::EXPR_INFIX, FromKind::EXPR_POSTFIX, FromKind::EXPR_PREFIX, FromKind::FORCE_EXPR, FromKind::HANDLE_EXPR, FromKind::IDENT_EXPR, FromKind::IF_ELSE_EXPR, FromKind::LAMBDA_EXPR, FromKind::MATCH_EXPR, FromKind::NUMBER_EXPR, FromKind::PAREN_EXPR, FromKind::PERFORM_EXPR, FromKind::STRING_EXPR, FromKind::THUNK_EXPR], 0)?;
    let b_b = langue_rt::nth_node_in(node, &[FromKind::BLOCK_EXPR, FromKind::BUNDLE_EXPR, FromKind::EXPR_INFIX, FromKind::EXPR_POSTFIX, FromKind::EXPR_PREFIX, FromKind::FORCE_EXPR, FromKind::HANDLE_EXPR, FromKind::IDENT_EXPR, FromKind::IF_ELSE_EXPR, FromKind::LAMBDA_EXPR, FromKind::MATCH_EXPR, FromKind::NUMBER_EXPR, FromKind::PAREN_EXPR, FromKind::PERFORM_EXPR, FromKind::STRING_EXPR, FromKind::THUNK_EXPR], 1)?;
    let mut c2 = ToFrag::token(b_c.text.clone());
    let mut c3 = elab_node(ctx, externs, b_h)?;
    let mut c3 = expect_kind(ctx, externs, c3, &[ToKind::BUNDLE_V, ToKind::CTOR_V, ToKind::NUM_V, ToKind::PAREN_V, ToKind::ROLL_V, ToKind::STR_V, ToKind::THUNK_V, ToKind::UNROLL_V, ToKind::VAR_V], "Value")?;
    let mut c4 = elab_node(ctx, externs, b_b)?;
    let mut c4 = expect_kind(ctx, externs, c4, &[ToKind::CASE_C, ToKind::COMP_POSTFIX, ToKind::FIX_C, ToKind::FORCE_C, ToKind::HANDLE_C, ToKind::LAM_C, ToKind::LET_C, ToKind::PAREN_C, ToKind::PERFORM_C, ToKind::RET_C, ToKind::SEL_C], "Comp")?;
    let mut r5 = ToFrag::node(ToKind::HANDLE_C, builder::handle_c(&c2.text, &c3.text, &c4.text));
    r5.absorb(&mut c4);
    r5.absorb(&mut c2);
    r5.absorb(&mut c3);
    flush_binders(externs, &mut r5);
    Some(r5)
}

/// Rule 10: `BundleExpr` ==> …
fn rule_10(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::BUNDLE_EXPR {
        return None;
    }
    let b_e = langue_rt::nodes_in(node, &[FromKind::BUNDLE_ENTRY], 0);
    let mut l1: Vec<ToFrag> = Vec::new();
    for n in &b_e {
        let f = elab_node(ctx, externs, n)?;
        let f = expect_kind(ctx, externs, f, &[ToKind::BUNDLE_CLAUSE], "BundleClause")?;
        l1.push(f);
    }
    let texts2: Vec<&str> = l1.iter().map(|f| f.text.as_str()).collect();
    let mut r3 = ToFrag::node(ToKind::BUNDLE_V, builder::bundle_v(&texts2));
    for f in &mut l1 {
        r3.absorb(f);
    }
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 11: `BundleEntry` ==> …
fn rule_11(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::BUNDLE_ENTRY {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::IDENT, 0)?;
    let b_n = t0;
    let v1 = langue_rt::nth_node_in(node, &[FromKind::PARAM_LIST], 0)?;
    if v1.kind != FromKind::PARAM_LIST {
        return None;
    }
    let b_p = langue_rt::nodes_in(v1, &[FromKind::PARAM], 0);
    let b_b = langue_rt::nth_node_in(node, &[FromKind::BLOCK_EXPR, FromKind::EXPR_BODY], 0)?;
    let mut c3 = ToFrag::token(b_n.text.clone());
    let mut l4: Vec<ToFrag> = Vec::new();
    for n in &b_p {
        let f = elab_node(ctx, externs, n)?;
        l4.push(f);
    }
    let mut c5 = elab_node(ctx, externs, b_b)?;
    let mut c5 = expect_kind(ctx, externs, c5, &[ToKind::CASE_C, ToKind::COMP_POSTFIX, ToKind::FIX_C, ToKind::FORCE_C, ToKind::HANDLE_C, ToKind::LAM_C, ToKind::LET_C, ToKind::PAREN_C, ToKind::PERFORM_C, ToKind::RET_C, ToKind::SEL_C], "Comp")?;
    let texts6: Vec<&str> = l4.iter().map(|f| f.text.as_str()).collect();
    let mut r7 = ToFrag::node(ToKind::BUNDLE_CLAUSE, builder::bundle_clause(&c3.text, &texts6, &c5.text));
    r7.absorb(&mut c5);
    r7.absorb(&mut c3);
    for f in &mut l4 {
        r7.absorb(f);
    }
    flush_binders(externs, &mut r7);
    Some(r7)
}

/// Rule 12: `Param` ==> …
fn rule_12(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::PARAM {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::IDENT, 0)?;
    let b_n = t0;
    let mut c2 = ToFrag::token(b_n.text.clone());
    let mut r3 = ToFrag::node(ToKind::VAR_V, builder::var_v(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 13: `BindPattern` ==> …
fn rule_13(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::BIND_PATTERN {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::IDENT, 0)?;
    let b_n = t0;
    let mut c2 = ToFrag::token(b_n.text.clone());
    let mut r3 = ToFrag::node(ToKind::VAR_V, builder::var_v(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 14: `IdentPattern` ==> …
fn rule_14(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::IDENT_PATTERN {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::IDENT, 0)?;
    let b_n = t0;
    let mut c2 = ToFrag::token(b_n.text.clone());
    let mut r3 = ToFrag::node(ToKind::VAR_V, builder::var_v(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 15: `WildcardPattern` ==> …
fn rule_15(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::WILDCARD_PATTERN {
        return None;
    }
    let mut c1 = ToFrag::token("_".to_owned());
    let mut r2 = ToFrag::node(ToKind::VAR_V, builder::var_v(&c1.text));
    r2.absorb(&mut c1);
    flush_binders(externs, &mut r2);
    Some(r2)
}

/// Rule 16: `ExprPostfix` ==> …
fn rule_16(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::EXPR_POSTFIX {
        return None;
    }
    let b_f = langue_rt::nth_node_in(node, &[FromKind::BLOCK_EXPR, FromKind::BUNDLE_EXPR, FromKind::EXPR_INFIX, FromKind::EXPR_POSTFIX, FromKind::EXPR_PREFIX, FromKind::FORCE_EXPR, FromKind::HANDLE_EXPR, FromKind::IDENT_EXPR, FromKind::IF_ELSE_EXPR, FromKind::LAMBDA_EXPR, FromKind::MATCH_EXPR, FromKind::NUMBER_EXPR, FromKind::PAREN_EXPR, FromKind::PERFORM_EXPR, FromKind::STRING_EXPR, FromKind::THUNK_EXPR], 0)?;
    let v0 = langue_rt::nth_node_in(node, &[FromKind::CALL_ARGS], 0)?;
    if v0.kind != FromKind::CALL_ARGS {
        return None;
    }
    let b_a = langue_rt::nodes_in(v0, &[FromKind::BLOCK_EXPR, FromKind::BUNDLE_EXPR, FromKind::EXPR_INFIX, FromKind::EXPR_POSTFIX, FromKind::EXPR_PREFIX, FromKind::FORCE_EXPR, FromKind::HANDLE_EXPR, FromKind::IDENT_EXPR, FromKind::IF_ELSE_EXPR, FromKind::LAMBDA_EXPR, FromKind::MATCH_EXPR, FromKind::NUMBER_EXPR, FromKind::PAREN_EXPR, FromKind::PERFORM_EXPR, FromKind::STRING_EXPR, FromKind::THUNK_EXPR], 0);
    let mut c4 = elab_node(ctx, externs, b_f)?;
    let mut c4 = expect_kind(ctx, externs, c4, &[ToKind::BUNDLE_V, ToKind::CTOR_V, ToKind::NUM_V, ToKind::PAREN_V, ToKind::ROLL_V, ToKind::STR_V, ToKind::THUNK_V, ToKind::UNROLL_V, ToKind::VAR_V], "Value")?;
    let mut r5 = ToFrag::node(ToKind::FORCE_C, builder::force_c(&c4.text));
    r5.absorb(&mut c4);
    flush_binders(externs, &mut r5);
    let mut l7: Vec<ToFrag> = Vec::new();
    for n in &b_a {
        let f = elab_node(ctx, externs, n)?;
        let f = expect_kind(ctx, externs, f, &[ToKind::BUNDLE_V, ToKind::CTOR_V, ToKind::NUM_V, ToKind::PAREN_V, ToKind::ROLL_V, ToKind::STR_V, ToKind::THUNK_V, ToKind::UNROLL_V, ToKind::VAR_V], "Value")?;
        l7.push(f);
    }
    let texts8: Vec<&str> = l7.iter().map(|f| f.text.as_str()).collect();
    let mut r9 = ToFrag::node(ToKind::VALUE_ARGS, builder::value_args(&texts8));
    for f in &mut l7 {
        r9.absorb(f);
    }
    flush_binders(externs, &mut r9);
    let mut r2 = ToFrag::node(ToKind::COMP_POSTFIX, builder::comp_postfix(builder::Operand { text: &r5.text, kind: r5.kind }, &r9.text));
    r2.absorb(&mut r5);
    r2.absorb(&mut r9);
    flush_binders(externs, &mut r2);
    Some(r2)
}
