// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.
#![allow(dead_code, unused_variables, unused_mut, clippy::all)]

use langue_rt::{ElabCtx, ElabReport, PassPhase};

use crate::mir::lossless::SyntaxNode as FromNode;
use crate::mir::syntax_kind::SyntaxKind as FromKind;
use crate::js::builder;
use crate::js::syntax_kind::SyntaxKind as ToKind;

pub type ToFrag = langue_rt::Frag<ToKind>;

/// Extern hooks (D-01/D-38). Rules and passes declared in the
/// definition have no default body — the Rust implementation is
/// mandatory, which is the extern coverage check. Provide it as
/// `crate::elab_externs::mir_to_js() -> Box<dyn Externs>`.
pub trait Externs {
    /// Called with the parsed source before rule dispatch.
    fn init(&mut self, _root: &FromNode) {}

    /// D-38 sort coercion: turn `frag` into something acceptable where
    /// `expected` is required (typically bind a computation to a fresh
    /// value via `ctx.fresh()` and return the variable as a frag whose
    /// `pending` carries the binder). `None` = not coercible.
    fn coerce(&mut self, _ctx: &mut ElabCtx, _expected: &'static str, _frag: &ToFrag) -> Option<ToFrag> {
        None
    }

    /// Nodes at which pending coercion binders are inserted.
    fn is_binder_site(&mut self, _kind: ToKind) -> bool {
        false
    }

    /// Wrap `body` in binders for `pending` (outermost first); returns
    /// the new text and its root kind.
    fn wrap_pending(&mut self, _pending: &[(String, String)], body: &str, kind: ToKind) -> (String, ToKind) {
        (body.to_owned(), kind)
    }

    /// `extern rule thunk_lambda from MIR to JS`
    fn rule_thunk_lambda(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern rule force_apply from MIR to JS`
    fn rule_force_apply(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern rule let_fix from MIR to JS`
    fn rule_let_fix(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern rule case_arms from MIR to JS`
    fn rule_case_arms(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern rule ctor_bundle from MIR to JS`
    fn rule_ctor_bundle(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern rule caps from MIR to JS`
    fn rule_caps(&mut self, ctx: &mut ElabCtx, node: &FromNode) -> Option<ToFrag>;

    /// `extern pass scc_fix` — offered both phases; `None` = skip.
    fn pass_scc_fix(&mut self, phase: PassPhase, text: &str) -> Option<String>;

    /// `extern pass use_require` — offered both phases; `None` = skip.
    fn pass_use_require(&mut self, phase: PassPhase, text: &str) -> Option<String>;
}

/// Run `elab MIR to JS` end to end over source text.
pub fn elab(text: &str, externs: &mut dyn Externs) -> ElabReport {
    let mut errors: Vec<String> = Vec::new();
    let mut src = text.to_owned();
    if let Some(t) = externs.pass_scc_fix(PassPhase::PreSource, &src) {
        src = t;
    }
    if let Some(t) = externs.pass_use_require(PassPhase::PreSource, &src) {
        src = t;
    }
    let parsed = crate::mir::parser::parse(&src);
    errors.extend(parsed.errors.iter().map(|e| format!("MIR: {} at {}", e.message, e.span)));
    let mut ctx = ElabCtx::new();
    externs.init(&parsed.root);
    let mut output = String::new();
    match elab_node(&mut ctx, externs, &parsed.root) {
        Some(frag) => {
            if !frag.pending.is_empty() {
                ctx.error("dangling coercion binders at the root".to_owned());
            }
            output = frag.text;
        }
        None => ctx.error("elaboration produced no output".to_owned()),
    }
    errors.append(&mut ctx.errors);
    if let Some(t) = externs.pass_scc_fix(PassPhase::PostTarget, &output) {
        output = t;
    }
    if let Some(t) = externs.pass_use_require(PassPhase::PostTarget, &output) {
        output = t;
    }
    let reparsed = crate::js::parser::parse(&output);
    errors.extend(reparsed.errors.iter().map(|e| format!("JS: {} at {} in `{output}`", e.message, e.span)));
    ElabReport {
        output: crate::js::printer::canonical(&reparsed.root),
        errors,
    }
}

/// Top-down dispatch by root kind. Extern rules go first, in
/// declaration order (they see every node and decline with `None`).
pub fn elab_node(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if let Some(frag) = externs.rule_thunk_lambda(ctx, node) {
        return Some(frag);
    }
    if let Some(frag) = externs.rule_force_apply(ctx, node) {
        return Some(frag);
    }
    if let Some(frag) = externs.rule_let_fix(ctx, node) {
        return Some(frag);
    }
    if let Some(frag) = externs.rule_case_arms(ctx, node) {
        return Some(frag);
    }
    if let Some(frag) = externs.rule_ctor_bundle(ctx, node) {
        return Some(frag);
    }
    if let Some(frag) = externs.rule_caps(ctx, node) {
        return Some(frag);
    }
    match node.kind {
        FromKind::DEF => {
            if let Some(frag) = rule_1(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `DEF`: {}", crate::mir::printer::canonical(node)));
            None
        }
        FromKind::FILE => {
            if let Some(frag) = rule_0(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `FILE`: {}", crate::mir::printer::canonical(node)));
            None
        }
        FromKind::NUM_V => {
            if let Some(frag) = rule_3(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `NUM_V`: {}", crate::mir::printer::canonical(node)));
            None
        }
        FromKind::PAREN_C => {
            if let Some(frag) = rule_9(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `PAREN_C`: {}", crate::mir::printer::canonical(node)));
            None
        }
        FromKind::PAREN_V => {
            if let Some(frag) = rule_8(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `PAREN_V`: {}", crate::mir::printer::canonical(node)));
            None
        }
        FromKind::RET_C => {
            if let Some(frag) = rule_5(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `RET_C`: {}", crate::mir::printer::canonical(node)));
            None
        }
        FromKind::ROLL_V => {
            if let Some(frag) = rule_6(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `ROLL_V`: {}", crate::mir::printer::canonical(node)));
            None
        }
        FromKind::SEL_C => {
            if let Some(frag) = rule_10(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `SEL_C`: {}", crate::mir::printer::canonical(node)));
            None
        }
        FromKind::STR_V => {
            if let Some(frag) = rule_4(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `STR_V`: {}", crate::mir::printer::canonical(node)));
            None
        }
        FromKind::UNROLL_V => {
            if let Some(frag) = rule_7(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `UNROLL_V`: {}", crate::mir::printer::canonical(node)));
            None
        }
        FromKind::VAR_V => {
            if let Some(frag) = rule_2(ctx, externs, node) {
                return Some(frag);
            }
            ctx.error(format!("no rule matched `VAR_V`: {}", crate::mir::printer::canonical(node)));
            None
        }
        other => {
            ctx.error(format!("no elab rule for `{other:?}`"));
            None
        }
    }
}

/// A frag placed where `kinds` (the concrete kinds of `expected`)
/// are required: pass through, coerce (D-38), or error.
fn expect_kind(ctx: &mut ElabCtx, externs: &mut dyn Externs, frag: ToFrag, kinds: &[ToKind], expected: &'static str) -> Option<ToFrag> {
    match frag.kind {
        None => Some(frag),
        Some(k) if kinds.contains(&k) => Some(frag),
        Some(k) => match externs.coerce(ctx, expected, &frag) {
            Some(mut coerced) => {
                let mut pending = frag.pending;
                pending.append(&mut coerced.pending);
                coerced.pending = pending;
                Some(coerced)
            }
            None => {
                ctx.error(format!("cannot place `{k:?}` where `{expected}` is expected: {}", frag.text));
                None
            }
        },
    }
}

/// Flush pending binders at a binder-site node (D-38).
fn flush_binders(externs: &mut dyn Externs, frag: &mut ToFrag) {
    if let Some(kind) = frag.kind {
        if !frag.pending.is_empty() && externs.is_binder_site(kind) {
            let (text, new_kind) = externs.wrap_pending(&frag.pending, &frag.text, kind);
            frag.text = text;
            frag.kind = Some(new_kind);
            frag.pending.clear();
        }
    }
}

/// Rule 0: `File` ==> …
fn rule_0(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::FILE {
        return None;
    }
    let b_d = langue_rt::nodes_in(node, &[FromKind::DEF], 0);
    let mut l1: Vec<ToFrag> = Vec::new();
    for n in &b_d {
        let f = elab_node(ctx, externs, n)?;
        let f = expect_kind(ctx, externs, f, &[ToKind::CONST_DECL], "ConstDecl")?;
        l1.push(f);
    }
    let texts2: Vec<&str> = l1.iter().map(|f| f.text.as_str()).collect();
    let mut r3 = ToFrag::node(ToKind::FILE, builder::file(&texts2));
    for f in &mut l1 {
        r3.absorb(f);
    }
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 1: `Def` ==> …
fn rule_1(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::DEF {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::IDENT, 0)?;
    let b_n = t0;
    let b_v = langue_rt::nth_node_in(node, &[FromKind::BUNDLE_V, FromKind::CTOR_V, FromKind::NUM_V, FromKind::PAREN_V, FromKind::ROLL_V, FromKind::STR_V, FromKind::THUNK_V, FromKind::UNROLL_V, FromKind::VAR_V], 0)?;
    let mut c2 = ToFrag::token(b_n.text.clone());
    let mut c3 = elab_node(ctx, externs, b_v)?;
    let mut c3 = expect_kind(ctx, externs, c3, &[ToKind::ARRAY_EXPR, ToKind::EXPR_INFIX, ToKind::EXPR_POSTFIX, ToKind::FN_EXPR, ToKind::IDENT_EXPR, ToKind::NUM_EXPR, ToKind::OBJECT_EXPR, ToKind::PAREN_EXPR, ToKind::STR_EXPR], "Expr")?;
    let mut r4 = ToFrag::node(ToKind::CONST_DECL, builder::const_decl(&c2.text, &c3.text));
    r4.absorb(&mut c2);
    r4.absorb(&mut c3);
    flush_binders(externs, &mut r4);
    Some(r4)
}

/// Rule 2: `VarV` ==> …
fn rule_2(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::VAR_V {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::IDENT, 0)?;
    let b_n = t0;
    let mut c2 = ToFrag::token(b_n.text.clone());
    let mut r3 = ToFrag::node(ToKind::IDENT_EXPR, builder::ident_expr(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 3: `NumV` ==> …
fn rule_3(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::NUM_V {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::LIT_NUMBER, 0)?;
    let b_v = t0;
    let mut c2 = ToFrag::token(b_v.text.clone());
    let mut r3 = ToFrag::node(ToKind::NUM_EXPR, builder::num_expr(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 4: `StrV` ==> …
fn rule_4(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::STR_V {
        return None;
    }
    let t0 = langue_rt::nth_token_of(node, FromKind::LIT_STRING, 0)?;
    let b_v = t0;
    let mut c2 = ToFrag::token(b_v.text.clone());
    let mut r3 = ToFrag::node(ToKind::STR_EXPR, builder::str_expr(&c2.text));
    r3.absorb(&mut c2);
    flush_binders(externs, &mut r3);
    Some(r3)
}

/// Rule 5: `RetC` ==> …
fn rule_5(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::RET_C {
        return None;
    }
    let b_v = langue_rt::nth_node_in(node, &[FromKind::BUNDLE_V, FromKind::CTOR_V, FromKind::NUM_V, FromKind::PAREN_V, FromKind::ROLL_V, FromKind::STR_V, FromKind::THUNK_V, FromKind::UNROLL_V, FromKind::VAR_V], 0)?;
    let mut c0 = elab_node(ctx, externs, b_v)?;
    Some(c0)
}

/// Rule 6: `RollV` ==> …
fn rule_6(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::ROLL_V {
        return None;
    }
    let b_v = langue_rt::nth_node_in(node, &[FromKind::BUNDLE_V, FromKind::CTOR_V, FromKind::NUM_V, FromKind::PAREN_V, FromKind::ROLL_V, FromKind::STR_V, FromKind::THUNK_V, FromKind::UNROLL_V, FromKind::VAR_V], 0)?;
    let mut c0 = elab_node(ctx, externs, b_v)?;
    Some(c0)
}

/// Rule 7: `UnrollV` ==> …
fn rule_7(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::UNROLL_V {
        return None;
    }
    let b_v = langue_rt::nth_node_in(node, &[FromKind::BUNDLE_V, FromKind::CTOR_V, FromKind::NUM_V, FromKind::PAREN_V, FromKind::ROLL_V, FromKind::STR_V, FromKind::THUNK_V, FromKind::UNROLL_V, FromKind::VAR_V], 0)?;
    let mut c0 = elab_node(ctx, externs, b_v)?;
    Some(c0)
}

/// Rule 8: `ParenV` ==> …
fn rule_8(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::PAREN_V {
        return None;
    }
    let b_v = langue_rt::nth_node_in(node, &[FromKind::BUNDLE_V, FromKind::CTOR_V, FromKind::NUM_V, FromKind::PAREN_V, FromKind::ROLL_V, FromKind::STR_V, FromKind::THUNK_V, FromKind::UNROLL_V, FromKind::VAR_V], 0)?;
    let mut c0 = elab_node(ctx, externs, b_v)?;
    Some(c0)
}

/// Rule 9: `ParenC` ==> …
fn rule_9(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::PAREN_C {
        return None;
    }
    let b_c = langue_rt::nth_node_in(node, &[FromKind::CASE_C, FromKind::COMP_POSTFIX, FromKind::FIX_C, FromKind::FORCE_C, FromKind::HANDLE_C, FromKind::LAM_C, FromKind::LET_C, FromKind::PAREN_C, FromKind::PERFORM_C, FromKind::RET_C, FromKind::SEL_C], 0)?;
    let mut c0 = elab_node(ctx, externs, b_c)?;
    Some(c0)
}

/// Rule 10: `SelC` ==> …
fn rule_10(ctx: &mut ElabCtx, externs: &mut dyn Externs, node: &FromNode) -> Option<ToFrag> {
    if node.kind != FromKind::SEL_C {
        return None;
    }
    let b_v = langue_rt::nth_node_in(node, &[FromKind::BUNDLE_V, FromKind::CTOR_V, FromKind::NUM_V, FromKind::PAREN_V, FromKind::ROLL_V, FromKind::STR_V, FromKind::THUNK_V, FromKind::UNROLL_V, FromKind::VAR_V], 0)?;
    let t0 = langue_rt::nth_token_of(node, FromKind::IDENT, 0)?;
    let b_f = t0;
    let mut c3 = elab_node(ctx, externs, b_v)?;
    let mut c3 = expect_kind(ctx, externs, c3, &[ToKind::ARRAY_EXPR, ToKind::EXPR_INFIX, ToKind::EXPR_POSTFIX, ToKind::FN_EXPR, ToKind::IDENT_EXPR, ToKind::NUM_EXPR, ToKind::OBJECT_EXPR, ToKind::PAREN_EXPR, ToKind::STR_EXPR], "Expr")?;
    let mut c5 = ToFrag::token(b_f.text.clone());
    let mut r6 = ToFrag::node(ToKind::MEMBER_NAME, builder::member_name(&c5.text));
    r6.absorb(&mut c5);
    flush_binders(externs, &mut r6);
    let mut r2 = ToFrag::node(ToKind::EXPR_POSTFIX, builder::expr_postfix_0(builder::Operand { text: &c3.text, kind: c3.kind }, &r6.text));
    r2.absorb(&mut c3);
    r2.absorb(&mut r6);
    flush_binders(externs, &mut r2);
    Some(r2)
}
