// Auto-generated by langue. Do not edit.
// Regenerate: scripts/gen_langue.sh

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum SyntaxKind {
    // Named tokens
    NUMBER_LIT,
    STRING_LIT,
    IDENT,
    // Trivia
    WHITESPACE,
    NEWLINE,
    UNKNOWN,
    // Keywords
    BUNDLE_KW, // 'bundle'
    CAP_KW, // 'cap'
    DATA_KW, // 'data'
    ELSE_KW, // 'else'
    EXTERN_KW, // 'extern'
    FN_KW, // 'fn'
    FORCE_KW, // 'force'
    HANDLE_KW, // 'handle'
    IF_KW, // 'if'
    IMPL_KW, // 'impl'
    IN_KW, // 'in'
    LET_KW, // 'let'
    MATCH_KW, // 'match'
    THUNK_KW, // 'thunk'
    TYPE_KW, // 'type'
    USE_KW, // 'use'
    WITH_KW, // 'with'
    // Symbols
    BANG, // '!'
    BANG_EQ, // '!='
    HASH, // '#'
    PERCENT, // '%'
    AMP_AMP, // '&&'
    L_PAREN, // '('
    R_PAREN, // ')'
    STAR, // '*'
    PLUS, // '+'
    MINUS, // '-'
    DOT, // '.'
    SLASH, // '/'
    COLON, // ':'
    SEMICOLON, // ';'
    LT, // '<'
    LT_EQ, // '<='
    EQUALS, // '='
    EQ_EQ, // '=='
    FAT_ARROW, // '=>'
    GT, // '>'
    GT_EQ, // '>='
    L_BRACKET, // '['
    R_BRACKET, // ']'
    UNDERSCORE, // '_'
    L_BRACE, // '{'
    PIPE_PIPE, // '||'
    R_BRACE, // '}'
    // Nodes
    FILE, // File
    ATTRIBUTE, // Attribute
    ATTRIBUTE_ARGS, // AttributeArgs
    ATTRIBUTE_ARG, // AttributeArg
    DATA_DECL, // DataDecl
    VARIANT, // Variant
    VARIANT_FIELDS, // VariantFields
    FN_DECL, // FnDecl
    EXPR_BODY, // ExprBody
    GENERIC_PARAMS, // GenericParams
    GENERIC_PARAM, // GenericParam
    PARAM_LIST, // ParamList
    PARAM, // Param
    CAP_ANNOTATION, // CapAnnotation
    CAP_SIG, // CapSig
    CAP_DECL, // CapDecl
    OPERATION_DECL, // OperationDecl
    EXTERN_TYPE_DECL, // ExternTypeDecl
    EXTERN_FN_DECL, // ExternFnDecl
    USE_DECL, // UseDecl
    USE_PATH, // UsePath
    USE_TREE, // UseTree
    IMPL_DECL, // ImplDecl
    IMPL_METHOD, // ImplMethod
    IDENT_EXPR, // IdentExpr
    STRING_EXPR, // StringExpr
    NUMBER_EXPR, // NumberExpr
    LET_EXPR, // LetExpr
    THUNK_EXPR, // ThunkExpr
    FORCE_EXPR, // ForceExpr
    MATCH_EXPR, // MatchExpr
    MATCH_ARM, // MatchArm
    CALL_EXPR, // CallExpr
    MEMBER_EXPR, // MemberExpr
    BINARY_EXPR, // BinaryExpr
    UNARY_EXPR, // UnaryExpr
    HANDLE_EXPR, // HandleExpr
    BUNDLE_EXPR, // BundleExpr
    BUNDLE_ENTRY, // BundleEntry
    PAREN_EXPR, // ParenExpr
    ANNOTATION_EXPR, // AnnotationExpr
    BLOCK_EXPR, // BlockExpr
    IF_ELSE_EXPR, // IfElseExpr
    ASSIGN_EXPR, // AssignExpr
    LET_STMT, // LetStmt
    EXPR_STMT, // ExprStmt
    VARIANT_PATTERN, // VariantPattern
    BIND_PATTERN, // BindPattern
    WILDCARD_PATTERN, // WildcardPattern
    TYPE_EXPR, // TypeExpr
    GENERIC_ARGS, // GenericArgs
    BINARY_OP, // BinaryOp (token wrapper)
    UNARY_OP, // UnaryOp (token wrapper)
    // Sentinel
    ERROR,
}

impl SyntaxKind {
    pub fn is_trivia(self) -> bool {
        matches!(self, Self::WHITESPACE | Self::NEWLINE)
    }

    pub fn from_keyword(text: &str) -> Option<Self> {
        match text {
            "bundle" => Some(Self::BUNDLE_KW),
            "cap" => Some(Self::CAP_KW),
            "data" => Some(Self::DATA_KW),
            "else" => Some(Self::ELSE_KW),
            "extern" => Some(Self::EXTERN_KW),
            "fn" => Some(Self::FN_KW),
            "force" => Some(Self::FORCE_KW),
            "handle" => Some(Self::HANDLE_KW),
            "if" => Some(Self::IF_KW),
            "impl" => Some(Self::IMPL_KW),
            "in" => Some(Self::IN_KW),
            "let" => Some(Self::LET_KW),
            "match" => Some(Self::MATCH_KW),
            "thunk" => Some(Self::THUNK_KW),
            "type" => Some(Self::TYPE_KW),
            "use" => Some(Self::USE_KW),
            "with" => Some(Self::WITH_KW),
            _ => None,
        }
    }

    pub fn from_symbol(text: &str) -> Option<Self> {
        match text {
            "!" => Some(Self::BANG),
            "!=" => Some(Self::BANG_EQ),
            "#" => Some(Self::HASH),
            "%" => Some(Self::PERCENT),
            "&&" => Some(Self::AMP_AMP),
            "(" => Some(Self::L_PAREN),
            ")" => Some(Self::R_PAREN),
            "*" => Some(Self::STAR),
            "+" => Some(Self::PLUS),
            "-" => Some(Self::MINUS),
            "." => Some(Self::DOT),
            "/" => Some(Self::SLASH),
            ":" => Some(Self::COLON),
            ";" => Some(Self::SEMICOLON),
            "<" => Some(Self::LT),
            "<=" => Some(Self::LT_EQ),
            "=" => Some(Self::EQUALS),
            "==" => Some(Self::EQ_EQ),
            "=>" => Some(Self::FAT_ARROW),
            ">" => Some(Self::GT),
            ">=" => Some(Self::GT_EQ),
            "[" => Some(Self::L_BRACKET),
            "]" => Some(Self::R_BRACKET),
            "_" => Some(Self::UNDERSCORE),
            "{" => Some(Self::L_BRACE),
            "||" => Some(Self::PIPE_PIPE),
            "}" => Some(Self::R_BRACE),
            _ => None,
        }
    }
}
