/// Code generation: Grammar → Rust source files.
use crate::grammar::{Alternative, Element, Grammar, NodeRef, Rule, RuleBody, TokenRef};
use std::collections::BTreeSet;
use std::fmt::Write;

/// Generate the `syntax_kind.rs` file contents.
pub fn generate_syntax_kind(grammar: &Grammar) -> String {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by langue. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]"
    )
    .unwrap();
    writeln!(out, "#[repr(u16)]").unwrap();
    writeln!(out, "pub enum SyntaxKind {{").unwrap();

    // --- Tokens ---
    writeln!(out, "    // Named tokens").unwrap();
    for tok in &grammar.token_defs {
        writeln!(out, "    {},", to_screaming_snake(tok)).unwrap();
    }

    writeln!(out, "    // Trivia").unwrap();
    writeln!(out, "    WHITESPACE,").unwrap();
    writeln!(out, "    NEWLINE,").unwrap();
    writeln!(out, "    UNKNOWN,").unwrap();

    // Collect all keywords and symbols from rules
    let (keywords, symbols) = collect_tokens(grammar);

    if !keywords.is_empty() {
        writeln!(out, "    // Keywords").unwrap();
        for kw in &keywords {
            writeln!(out, "    {}, // '{kw}'", keyword_variant(kw)).unwrap();
        }
    }

    if !symbols.is_empty() {
        writeln!(out, "    // Symbols").unwrap();
        for sym in &symbols {
            writeln!(out, "    {}, // '{sym}'", symbol_variant(sym)).unwrap();
        }
    }

    // --- Nodes ---
    writeln!(out, "    // Nodes").unwrap();
    for rule in &grammar.rules {
        // Only sequence rules get a SyntaxKind. Alternative rules are virtual
        // (they don't have their own node kind — they match child node kinds).
        match &rule.body {
            RuleBody::Sequence(_) => {
                writeln!(
                    out,
                    "    {}, // {}",
                    to_screaming_snake(&rule.name),
                    rule.name
                )
                .unwrap();
            }
            RuleBody::Alternatives(_) => {
                // Token-only alternatives (like BinaryOp, UnaryOp) still need
                // a SyntaxKind for the wrapper node
                if is_token_only_alternatives(grammar, rule) {
                    writeln!(
                        out,
                        "    {}, // {} (token wrapper)",
                        to_screaming_snake(&rule.name),
                        rule.name
                    )
                    .unwrap();
                }
            }
        }
    }

    writeln!(out, "    // Sentinel").unwrap();
    writeln!(out, "    ERROR,").unwrap();
    writeln!(out, "}}").unwrap();

    // --- Helper methods ---
    writeln!(out).unwrap();
    writeln!(out, "impl SyntaxKind {{").unwrap();
    writeln!(out, "    pub fn is_trivia(self) -> bool {{").unwrap();
    writeln!(
        out,
        "        matches!(self, Self::WHITESPACE | Self::NEWLINE)"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();

    // from_keyword helper
    if !keywords.is_empty() {
        writeln!(out).unwrap();
        writeln!(
            out,
            "    pub fn from_keyword(text: &str) -> Option<Self> {{"
        )
        .unwrap();
        writeln!(out, "        match text {{").unwrap();
        for kw in &keywords {
            writeln!(out, "            \"{kw}\" => Some(Self::{}),", keyword_variant(kw)).unwrap();
        }
        writeln!(out, "            _ => None,").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
    }

    // from_symbol helper
    if !symbols.is_empty() {
        writeln!(out).unwrap();
        writeln!(
            out,
            "    pub fn from_symbol(text: &str) -> Option<Self> {{"
        )
        .unwrap();
        writeln!(out, "        match text {{").unwrap();
        for sym in &symbols {
            writeln!(
                out,
                "            \"{sym}\" => Some(Self::{}),",
                symbol_variant(sym)
            )
            .unwrap();
        }
        writeln!(out, "            _ => None,").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
    }

    writeln!(out, "}}").unwrap();

    out
}

/// Generate the `ast.rs` file contents.
pub fn generate_ast(grammar: &Grammar) -> String {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by langue. Do not edit.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use super::SyntaxKind;").unwrap();
    writeln!(out).unwrap();

    // We reference the lossless tree types. Use a generic import path
    // that the consumer crate must provide.
    writeln!(out, "/// A node in the lossless syntax tree.").unwrap();
    writeln!(out, "/// The consumer crate must provide this type alias:").unwrap();
    writeln!(
        out,
        "/// `type SyntaxNode = crate::lst::lossless::SyntaxNode;`"
    )
    .unwrap();
    writeln!(out, "use super::{{SyntaxNode, SyntaxElement, LosslessToken}};").unwrap();
    writeln!(out).unwrap();

    // AstNode trait
    writeln!(out, "pub trait AstNode<'a>: Sized {{").unwrap();
    writeln!(
        out,
        "    fn cast(node: &'a SyntaxNode) -> Option<Self>;"
    )
    .unwrap();
    writeln!(out, "    fn syntax(&self) -> &'a SyntaxNode;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    for rule in &grammar.rules {
        match &rule.body {
            RuleBody::Sequence(elements) => {
                generate_struct_node(&mut out, grammar, &rule.name, elements);
            }
            RuleBody::Alternatives(alts) => {
                if is_token_only_alternatives_from_alts(alts) {
                    // Token-only alternatives (BinaryOp, UnaryOp) — just a wrapper
                    generate_token_wrapper_node(&mut out, &rule.name);
                } else {
                    generate_enum_node(&mut out, grammar, &rule.name, alts);
                }
            }
        }
    }

    out
}

// --- Struct node (sequence rule) ---

fn generate_struct_node(out: &mut String, grammar: &Grammar, name: &str, elements: &[Element]) {
    let kind = to_screaming_snake(name);

    // struct
    writeln!(out, "pub struct {name}<'a>(pub(crate) &'a SyntaxNode);").unwrap();
    writeln!(out).unwrap();

    // AstNode impl
    writeln!(out, "impl<'a> AstNode<'a> for {name}<'a> {{").unwrap();
    writeln!(
        out,
        "    fn cast(node: &'a SyntaxNode) -> Option<Self> {{"
    )
    .unwrap();
    writeln!(
        out,
        "        (node.kind == SyntaxKind::{kind}).then(|| Self(node))"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(
        out,
        "    fn syntax(&self) -> &'a SyntaxNode {{ self.0 }}"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Accessor methods
    let accessors = collect_accessors(grammar, elements);
    if !accessors.is_empty() {
        writeln!(out, "impl<'a> {name}<'a> {{").unwrap();
        for acc in &accessors {
            generate_accessor(out, grammar, acc);
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}

// --- Enum node (alternative rule) ---

fn generate_enum_node(out: &mut String, _grammar: &Grammar, name: &str, alts: &[Alternative]) {
    // enum
    writeln!(out, "pub enum {name}<'a> {{").unwrap();
    for alt in alts {
        let variant = &alt.name;
        writeln!(out, "    {variant}({variant}<'a>),").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // AstNode impl — try casting each alternative
    writeln!(out, "impl<'a> AstNode<'a> for {name}<'a> {{").unwrap();
    writeln!(
        out,
        "    fn cast(node: &'a SyntaxNode) -> Option<Self> {{"
    )
    .unwrap();
    writeln!(out, "        None").unwrap();
    for alt in alts {
        let variant = &alt.name;
        writeln!(
            out,
            "            .or_else(|| {variant}::cast(node).map(Self::{variant}))"
        )
        .unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(
        out,
        "    fn syntax(&self) -> &'a SyntaxNode {{"
    )
    .unwrap();
    writeln!(out, "        match self {{").unwrap();
    for alt in alts {
        let variant = &alt.name;
        writeln!(out, "            Self::{variant}(n) => n.syntax(),").unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

// --- Token wrapper node (token-only alternatives like BinaryOp) ---

fn generate_token_wrapper_node(out: &mut String, name: &str) {
    let kind = to_screaming_snake(name);
    writeln!(out, "pub struct {name}<'a>(pub(crate) &'a SyntaxNode);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl<'a> AstNode<'a> for {name}<'a> {{").unwrap();
    writeln!(
        out,
        "    fn cast(node: &'a SyntaxNode) -> Option<Self> {{"
    )
    .unwrap();
    writeln!(
        out,
        "        (node.kind == SyntaxKind::{kind}).then(|| Self(node))"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(
        out,
        "    fn syntax(&self) -> &'a SyntaxNode {{ self.0 }}"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

// --- Accessor generation ---

#[derive(Debug)]
struct Accessor {
    label: String,
    kind: AccessorKind,
    repeated: bool,
}

#[derive(Debug)]
enum AccessorKind {
    /// A token child (returns `Option<&LosslessToken>` or iterator)
    Token(TokenTarget),
    /// A node child (returns `Option<NodeType>` or iterator)
    Node(String),
}

#[derive(Debug)]
enum TokenTarget {
    /// A named token: Ident, StringLit, etc.
    Named(String),
    /// A specific keyword: 'data', 'fn', etc.
    Keyword(String),
    /// A specific symbol: '(', ')', etc.
    Symbol(String),
}

fn collect_accessors(grammar: &Grammar, elements: &[Element]) -> Vec<Accessor> {
    let mut accessors = Vec::new();
    for elem in elements {
        collect_accessors_from_element(grammar, elem, &mut accessors);
    }
    accessors
}

fn collect_accessors_from_element(
    grammar: &Grammar,
    elem: &Element,
    accessors: &mut Vec<Accessor>,
) {
    match elem {
        Element::Labeled(label, inner) => {
            let (kind, repeated) = resolve_accessor_kind(grammar, inner);
            if let Some(kind) = kind {
                accessors.push(Accessor {
                    label: label.clone(),
                    kind,
                    repeated,
                });
            }
        }
        // Unlabeled elements don't generate accessors
        _ => {}
    }
}

fn resolve_accessor_kind(grammar: &Grammar, elem: &Element) -> (Option<AccessorKind>, bool) {
    match elem {
        Element::Token(TokenRef::Named(name)) => {
            (Some(AccessorKind::Token(TokenTarget::Named(name.clone()))), false)
        }
        Element::Token(TokenRef::Keyword(kw)) => {
            (Some(AccessorKind::Token(TokenTarget::Keyword(kw.clone()))), false)
        }
        Element::Token(TokenRef::Symbol(sym)) => {
            (Some(AccessorKind::Token(TokenTarget::Symbol(sym.clone()))), false)
        }
        Element::Node(NodeRef { name }) => (Some(AccessorKind::Node(name.clone())), false),
        Element::Optional(inner) => {
            let (kind, _) = resolve_accessor_kind(grammar, inner);
            (kind, false) // Optional just makes the return type Option<>
        }
        Element::Repeated(inner) => {
            let (kind, _) = resolve_accessor_kind(grammar, inner);
            (kind, true)
        }
        Element::Group(_) => (None, false), // Groups don't generate direct accessors
        Element::Labeled(_, inner) => resolve_accessor_kind(grammar, inner),
    }
}

fn generate_accessor(out: &mut String, _grammar: &Grammar, acc: &Accessor) {
    let label = &acc.label;
    match (&acc.kind, acc.repeated) {
        (AccessorKind::Token(target), false) => {
            let filter = token_filter_expr(target);
            writeln!(
                out,
                "    pub fn {label}(&self) -> Option<&'a LosslessToken> {{"
            )
            .unwrap();
            writeln!(
                out,
                "        self.0.children.iter().find_map(|c| match c {{"
            )
            .unwrap();
            writeln!(
                out,
                "            SyntaxElement::Token(t) if {filter} => Some(t),"
            )
            .unwrap();
            writeln!(out, "            _ => None,").unwrap();
            writeln!(out, "        }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        (AccessorKind::Token(target), true) => {
            let filter = token_filter_expr(target);
            writeln!(
                out,
                "    pub fn {label}(&self) -> impl Iterator<Item = &'a LosslessToken> + 'a {{"
            )
            .unwrap();
            writeln!(
                out,
                "        self.0.children.iter().filter_map(|c| match c {{"
            )
            .unwrap();
            writeln!(
                out,
                "            SyntaxElement::Token(t) if {filter} => Some(t),"
            )
            .unwrap();
            writeln!(out, "            _ => None,").unwrap();
            writeln!(out, "        }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        (AccessorKind::Node(node_name), false) => {
            writeln!(
                out,
                "    pub fn {label}(&self) -> Option<{node_name}<'a>> {{"
            )
            .unwrap();
            writeln!(
                out,
                "        self.0.children.iter().find_map(|c| match c {{"
            )
            .unwrap();
            writeln!(
                out,
                "            SyntaxElement::Node(n) => {node_name}::cast(n),"
            )
            .unwrap();
            writeln!(out, "            _ => None,").unwrap();
            writeln!(out, "        }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        (AccessorKind::Node(node_name), true) => {
            writeln!(
                out,
                "    pub fn {label}(&self) -> impl Iterator<Item = {node_name}<'a>> + 'a {{"
            )
            .unwrap();
            writeln!(
                out,
                "        self.0.children.iter().filter_map(|c| match c {{"
            )
            .unwrap();
            writeln!(
                out,
                "            SyntaxElement::Node(n) => {node_name}::cast(n),"
            )
            .unwrap();
            writeln!(out, "            _ => None,").unwrap();
            writeln!(out, "        }})").unwrap();
            writeln!(out, "    }}").unwrap();
        }
    }
}

fn token_filter_expr(target: &TokenTarget) -> String {
    match target {
        TokenTarget::Named(name) => {
            format!("t.kind == SyntaxKind::{}", to_screaming_snake(name))
        }
        TokenTarget::Keyword(kw) => {
            format!("t.kind == SyntaxKind::{}", keyword_variant(kw))
        }
        TokenTarget::Symbol(sym) => {
            format!("t.kind == SyntaxKind::{}", symbol_variant(sym))
        }
    }
}

// --- Token collection ---

fn collect_tokens(grammar: &Grammar) -> (BTreeSet<String>, BTreeSet<String>) {
    let mut keywords = BTreeSet::new();
    let mut symbols = BTreeSet::new();

    for rule in &grammar.rules {
        match &rule.body {
            RuleBody::Sequence(elems) => {
                for elem in elems {
                    collect_tokens_from_element(elem, &mut keywords, &mut symbols);
                }
            }
            RuleBody::Alternatives(alts) => {
                for alt in alts {
                    // Token-only alternatives (like `| '+'`) have their literal in the name
                    if alt.name.starts_with('\'') && alt.name.ends_with('\'') {
                        let text = &alt.name[1..alt.name.len() - 1];
                        let tok = TokenRef::from_literal(text);
                        match tok {
                            TokenRef::Keyword(k) => {
                                keywords.insert(k);
                            }
                            TokenRef::Symbol(s) => {
                                symbols.insert(s);
                            }
                            _ => {}
                        }
                    }
                }
            }
        }
    }

    (keywords, symbols)
}

fn collect_tokens_from_element(
    elem: &Element,
    keywords: &mut BTreeSet<String>,
    symbols: &mut BTreeSet<String>,
) {
    match elem {
        Element::Token(TokenRef::Keyword(k)) => {
            keywords.insert(k.clone());
        }
        Element::Token(TokenRef::Symbol(s)) => {
            symbols.insert(s.clone());
        }
        Element::Token(TokenRef::Named(_)) => {}
        Element::Node(_) => {}
        Element::Labeled(_, inner) => {
            collect_tokens_from_element(inner, keywords, symbols);
        }
        Element::Optional(inner) | Element::Repeated(inner) => {
            collect_tokens_from_element(inner, keywords, symbols);
        }
        Element::Group(elems) => {
            for e in elems {
                collect_tokens_from_element(e, keywords, symbols);
            }
        }
    }
}

// --- Naming helpers ---

fn to_screaming_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() && i > 0 {
            // Don't add underscore between consecutive uppercase (e.g. "ID" → "ID")
            let prev = name.as_bytes()[i - 1];
            if prev.is_ascii_lowercase() || prev.is_ascii_digit() {
                out.push('_');
            }
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

fn keyword_variant(kw: &str) -> String {
    format!("{}_KW", kw.to_ascii_uppercase())
}

fn symbol_variant(sym: &str) -> String {
    match sym {
        "#" => "HASH".to_owned(),
        "(" => "L_PAREN".to_owned(),
        ")" => "R_PAREN".to_owned(),
        "[" => "L_BRACKET".to_owned(),
        "]" => "R_BRACKET".to_owned(),
        "{" => "L_BRACE".to_owned(),
        "}" => "R_BRACE".to_owned(),
        ";" => "SEMICOLON".to_owned(),
        ":" => "COLON".to_owned(),
        "," => "COMMA".to_owned(),
        "=" => "EQUALS".to_owned(),
        ":=" => "COLON_EQ".to_owned(),
        "=>" => "FAT_ARROW".to_owned(),
        "->" => "ARROW".to_owned(),
        "." => "DOT".to_owned(),
        "+" => "PLUS".to_owned(),
        "-" => "MINUS".to_owned(),
        "*" => "STAR".to_owned(),
        "/" => "SLASH".to_owned(),
        "%" => "PERCENT".to_owned(),
        "!" => "BANG".to_owned(),
        "<" => "LT".to_owned(),
        ">" => "GT".to_owned(),
        "<=" => "LT_EQ".to_owned(),
        ">=" => "GT_EQ".to_owned(),
        "==" => "EQ_EQ".to_owned(),
        "!=" => "BANG_EQ".to_owned(),
        "&&" => "AMP_AMP".to_owned(),
        "||" => "PIPE_PIPE".to_owned(),
        "_" => "UNDERSCORE".to_owned(),
        other => {
            // Fallback: escape to SYM_<chars>
            let mut name = "SYM".to_owned();
            for c in other.chars() {
                name.push('_');
                name.push_str(&format!("{:02X}", c as u32));
            }
            name
        }
    }
}

fn is_token_only_alternatives(_grammar: &Grammar, rule: &Rule) -> bool {
    match &rule.body {
        RuleBody::Alternatives(alts) => is_token_only_alternatives_from_alts(alts),
        _ => false,
    }
}

fn is_token_only_alternatives_from_alts(alts: &[Alternative]) -> bool {
    alts.iter()
        .all(|a| a.name.starts_with('\'') && a.name.ends_with('\''))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;

    #[test]
    fn syntax_kind_basic() {
        let g = parse(
            r#"
@token Ident StringLit

File = Item*

Item =
  | DataDecl
  | FnDecl

DataDecl = 'data' name:Ident '{' variants:Variant* '}'
Variant = '.' name:Ident
FnDecl = 'fn' name:Ident ':=' body:Expr
Expr = name:Ident
"#,
        )
        .unwrap();

        let code = generate_syntax_kind(&g);
        assert!(code.contains("IDENT,"));
        assert!(code.contains("STRING_LIT,"));
        assert!(code.contains("WHITESPACE,"));
        assert!(code.contains("DATA_KW,"));
        assert!(code.contains("FN_KW,"));
        assert!(code.contains("L_BRACE,"));
        assert!(code.contains("R_BRACE,"));
        assert!(code.contains("DOT,"));
        assert!(code.contains("COLON_EQ,"));
        assert!(code.contains("FILE,"));
        assert!(code.contains("DATA_DECL,"));
        assert!(code.contains("FN_DECL,"));
        assert!(code.contains("VARIANT,"));
        assert!(code.contains("EXPR,"));
        assert!(code.contains("ERROR,"));
        // Item is alternatives → no SyntaxKind variant
        assert!(!code.contains("ITEM,"));
    }

    #[test]
    fn ast_struct_generation() {
        let g = parse(
            r#"
@token Ident
DataDecl = 'data' name:Ident '{' variants:Variant* '}'
Variant = '.' name:Ident
"#,
        )
        .unwrap();

        let code = generate_ast(&g);
        assert!(code.contains("pub struct DataDecl<'a>"));
        assert!(code.contains("pub fn name(&self) -> Option<&'a LosslessToken>"));
        assert!(code.contains("pub fn variants(&self) -> impl Iterator<Item = Variant<'a>>"));
        assert!(code.contains("pub struct Variant<'a>"));
    }

    #[test]
    fn ast_enum_generation() {
        let g = parse(
            r#"
@token Ident
Item =
  | DataDecl
  | FnDecl
DataDecl = 'data' name:Ident
FnDecl = 'fn' name:Ident
"#,
        )
        .unwrap();

        let code = generate_ast(&g);
        assert!(code.contains("pub enum Item<'a>"));
        assert!(code.contains("DataDecl(DataDecl<'a>),"));
        assert!(code.contains("FnDecl(FnDecl<'a>),"));
    }

    #[test]
    fn to_screaming_snake_cases() {
        assert_eq!(to_screaming_snake("File"), "FILE");
        assert_eq!(to_screaming_snake("DataDecl"), "DATA_DECL");
        assert_eq!(to_screaming_snake("FnDecl"), "FN_DECL");
        assert_eq!(to_screaming_snake("ExternTypeDecl"), "EXTERN_TYPE_DECL");
        assert_eq!(to_screaming_snake("IdentExpr"), "IDENT_EXPR");
        assert_eq!(to_screaming_snake("StringLit"), "STRING_LIT");
        assert_eq!(to_screaming_snake("GenericParams"), "GENERIC_PARAMS");
        assert_eq!(to_screaming_snake("CapAnnotation"), "CAP_ANNOTATION");
    }

    #[test]
    fn token_only_alternatives_generate_wrapper() {
        let g = parse(
            r#"
BinaryOp =
  | '+'
  | '-'
  | '*'
"#,
        )
        .unwrap();

        let sk = generate_syntax_kind(&g);
        assert!(sk.contains("BINARY_OP,")); // gets a SyntaxKind
        assert!(sk.contains("PLUS,"));
        assert!(sk.contains("MINUS,"));
        assert!(sk.contains("STAR,"));

        let ast = generate_ast(&g);
        assert!(ast.contains("pub struct BinaryOp<'a>"));
    }

    #[test]
    fn lumo_langue_full_grammar() {
        let source = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .parent()
                .unwrap()
                .join("compiler/lumo.langue"),
        )
        .unwrap();
        let g = parse(&source).unwrap();

        // Verify token defs
        assert_eq!(g.token_defs, vec!["Ident", "StringLit", "NumberLit"]);

        // Verify key rules exist
        let rule_names: Vec<&str> = g.rules.iter().map(|r| r.name.as_str()).collect();
        assert!(rule_names.contains(&"File"));
        assert!(rule_names.contains(&"Item"));
        assert!(rule_names.contains(&"DataDecl"));
        assert!(rule_names.contains(&"FnDecl"));
        assert!(rule_names.contains(&"Expr"));
        assert!(rule_names.contains(&"Pattern"));
        assert!(rule_names.contains(&"TypeExpr"));
        assert!(rule_names.contains(&"BinaryOp"));
        assert!(rule_names.contains(&"UnaryOp"));
        assert!(rule_names.contains(&"ImplDecl"));
        assert!(rule_names.contains(&"CapDecl"));
        assert!(rule_names.contains(&"UseDecl"));

        // Verify codegen produces valid output
        let sk = generate_syntax_kind(&g);
        assert!(sk.contains("pub enum SyntaxKind"));
        assert!(sk.contains("DATA_KW,"));
        assert!(sk.contains("FN_KW,"));
        assert!(sk.contains("FILE,"));
        assert!(sk.contains("ERROR,"));
        assert!(sk.contains("pub fn from_keyword"));
        assert!(sk.contains("pub fn from_symbol"));

        let ast = generate_ast(&g);
        assert!(ast.contains("pub trait AstNode"));
        assert!(ast.contains("pub struct File<'a>"));
        assert!(ast.contains("pub enum Item<'a>"));
        assert!(ast.contains("pub enum Expr<'a>"));
        assert!(ast.contains("pub enum Pattern<'a>"));
        assert!(ast.contains("pub struct DataDecl<'a>"));
        assert!(ast.contains("pub fn variants(&self)"));
    }
}
