// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.
#![allow(dead_code)]

use super::syntax_kind::SyntaxKind;

/// A praat operand: rendered text plus its root kind, when known.
/// `None` renders defensively (always parenthesized).
pub struct Operand<'a> {
    pub text: &'a str,
    pub kind: Option<SyntaxKind>,
}

fn push(out: &mut String, s: &str) {
    if s.is_empty() {
        return;
    }
    if !out.is_empty() {
        out.push(' ');
    }
    out.push_str(s);
}

/// Render a `AssocTypeBinding` node as reparseable text.
pub fn assoc_type_binding(name: &str, ty: &str) -> String {
    let mut out = String::new();
    push(&mut out, "type");
    push(&mut out, name);
    push(&mut out, "=");
    push(&mut out, ty);
    out
}

/// Render a `AssocTypeDecl` node as reparseable text.
pub fn assoc_type_decl(name: &str) -> String {
    let mut out = String::new();
    push(&mut out, "type");
    push(&mut out, name);
    out
}

// `Attribute` is not buildable: alternatives cannot be chosen from field values.

/// Render a `AttributeArgItem` node as reparseable text.
pub fn attribute_arg_item(name: &str, value: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, name);
    if value.is_some() {
        push(&mut out, "=");
        if let Some(v) = value {
            push(&mut out, v);
        }
    }
    out
}

/// Render a `AttributeArgs` node as reparseable text.
pub fn attribute_args(items: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    out
}

/// Render a `BindPattern` node as reparseable text.
pub fn bind_pattern(name: &str) -> String {
    let mut out = String::new();
    push(&mut out, "let");
    push(&mut out, name);
    out
}

/// Render a `BlockExpr` node as reparseable text.
pub fn block_expr(stmts: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "{");
    for item in stmts {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `BoundList` node as reparseable text.
pub fn bound_list(bounds: &[&str]) -> String {
    let mut out = String::new();
    for (i, item) in bounds.iter().enumerate() {
        if i > 0 {
            push(&mut out, "+");
        }
        push(&mut out, item);
    }
    out
}

/// Render a `BundleEntry` node as reparseable text.
pub fn bundle_entry(name: &str, param_list: &str, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "fn");
    push(&mut out, name);
    push(&mut out, param_list);
    push(&mut out, body);
    out
}

/// Render a `BundleExpr` node as reparseable text.
pub fn bundle_expr(entries: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "bundle");
    push(&mut out, "{");
    for item in entries {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `CallArgs` node as reparseable text.
pub fn call_args(args: &[&str]) -> String {
    let mut out = String::new();
    for (i, item) in args.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    out
}

/// Render a `CapAnnotation` node as reparseable text.
pub fn cap_annotation(cap: &str) -> String {
    let mut out = String::new();
    push(&mut out, "/");
    push(&mut out, cap);
    out
}

/// Render a `CapDecl` node as reparseable text.
pub fn cap_decl(name: &str, items: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "cap");
    push(&mut out, name);
    push(&mut out, "{");
    for item in items {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `CapEntry` node as reparseable text.
pub fn cap_entry(body: &str) -> String {
    let mut out = String::new();
    push(&mut out, body);
    out
}

/// Render a `CapRest` node as reparseable text.
pub fn cap_rest(name: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, "..");
    if let Some(v) = name {
        push(&mut out, v);
    }
    out
}

/// Render a `CapSet` node as reparseable text.
pub fn cap_set(entries: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "{");
    for item in entries {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `CapSig` node as reparseable text.
pub fn cap_sig(name: &str, generic_args: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, name);
    if let Some(v) = generic_args {
        push(&mut out, v);
    }
    out
}

/// Render a `DataDecl` node as reparseable text.
pub fn data_decl(name: &str, generic_params: Option<&str>, variants: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "data");
    push(&mut out, name);
    if let Some(v) = generic_params {
        push(&mut out, v);
    }
    push(&mut out, "{");
    for item in variants {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Trailing openness of a `Expr` operand (see module docs).
fn expr_r_bound(kind: Option<SyntaxKind>) -> u16 {
    let Some(kind) = kind else { return 0 };
    match kind {
        SyntaxKind::FORCE_EXPR | SyntaxKind::HANDLE_EXPR | SyntaxKind::IF_ELSE_EXPR | SyntaxKind::LAMBDA_EXPR | SyntaxKind::THUNK_EXPR => 0,
        SyntaxKind::EXPR_PREFIX => 100,
        SyntaxKind::EXPR_INFIX => 40,
        _ => u16::MAX,
    }
}

fn expr_b_bound(kind: Option<SyntaxKind>) -> u16 {
    let Some(kind) = kind else { return 0 };
    match kind {
        SyntaxKind::EXPR_INFIX => 39,
        SyntaxKind::EXPR_POSTFIX => 110,
        _ => u16::MAX,
    }
}

fn expr_paren(text: &str) -> String {
    paren_expr(text, None)
}

/// Left operand of an operator row: parenthesize iff the row would
/// bind inside it.
fn expr_left(op: Operand, bind: u16) -> String {
    if bind > expr_r_bound(op.kind) {
        expr_paren(op.text)
    } else {
        op.text.to_owned()
    }
}

/// Operand parsed at a known min_bp (prefix/infix right side).
fn expr_at(op: Operand, min_bp: u16) -> String {
    if expr_b_bound(op.kind) <= min_bp {
        expr_paren(op.text)
    } else {
        op.text.to_owned()
    }
}

pub fn expr_prefix(op: &str, expr: Operand) -> String {
    let mut out = String::new();
    debug_assert!(["-", "!"].contains(&op));
    push(&mut out, op);
    push(&mut out, &expr_at(expr, 100));
    out
}

pub fn expr_postfix_0(expr: Operand, member_name: &str) -> String {
    let mut out = String::new();
    push(&mut out, &expr_left(expr, 110));
    push(&mut out, ".");
    push(&mut out, member_name);
    out
}

pub fn expr_postfix_1(expr: Operand, call_args: &str) -> String {
    let mut out = String::new();
    push(&mut out, &expr_left(expr, 110));
    push(&mut out, "(");
    push(&mut out, call_args);
    push(&mut out, ")");
    out
}

pub fn expr_infix_0(lhs: Operand, op: &str, rhs: Operand) -> String {
    let mut out = String::new();
    debug_assert!(["**"].contains(&op));
    push(&mut out, &expr_left(lhs, 90));
    push(&mut out, op);
    push(&mut out, &expr_at(rhs, 89));
    out
}

pub fn expr_infix_1(lhs: Operand, op: &str, rhs: Operand) -> String {
    let mut out = String::new();
    debug_assert!(["*", "/", "%"].contains(&op));
    push(&mut out, &expr_left(lhs, 79));
    push(&mut out, op);
    push(&mut out, &expr_at(rhs, 80));
    out
}

pub fn expr_infix_2(lhs: Operand, op: &str, rhs: Operand) -> String {
    let mut out = String::new();
    debug_assert!(["+", "-"].contains(&op));
    push(&mut out, &expr_left(lhs, 69));
    push(&mut out, op);
    push(&mut out, &expr_at(rhs, 70));
    out
}

pub fn expr_infix_3(lhs: Operand, op: &str, rhs: Operand) -> String {
    let mut out = String::new();
    debug_assert!(["==", "!=", "<", "<=", ">", ">="].contains(&op));
    push(&mut out, &expr_left(lhs, 59));
    push(&mut out, op);
    push(&mut out, &expr_at(rhs, 60));
    out
}

pub fn expr_infix_4(lhs: Operand, op: &str, rhs: Operand) -> String {
    let mut out = String::new();
    debug_assert!(["&&"].contains(&op));
    push(&mut out, &expr_left(lhs, 49));
    push(&mut out, op);
    push(&mut out, &expr_at(rhs, 50));
    out
}

pub fn expr_infix_5(lhs: Operand, op: &str, rhs: Operand) -> String {
    let mut out = String::new();
    debug_assert!(["||"].contains(&op));
    push(&mut out, &expr_left(lhs, 39));
    push(&mut out, op);
    push(&mut out, &expr_at(rhs, 40));
    out
}

/// Render a `ExprBody` node as reparseable text.
pub fn expr_body(body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "=");
    push(&mut out, body);
    out
}

/// Render a `ExprStmt` node as reparseable text.
pub fn expr_stmt(expr: &str) -> String {
    let mut out = String::new();
    push(&mut out, expr);
    out
}

/// Render a `ExternBlockItem` node as reparseable text.
pub fn extern_block_item(attrs: &[&str], body: &str) -> String {
    let mut out = String::new();
    for item in attrs {
        push(&mut out, item);
    }
    push(&mut out, body);
    out
}

/// Render a `ExternBlockTail` node as reparseable text.
pub fn extern_block_tail(items: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "{");
    for item in items {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `ExternDecl` node as reparseable text.
pub fn extern_decl(rest: &str) -> String {
    let mut out = String::new();
    push(&mut out, "extern");
    push(&mut out, rest);
    out
}

/// Render a `ExternFnTail` node as reparseable text.
pub fn extern_fn_tail(name: &str, param_list: &str, return_type: Option<&str>, cap_annotation: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, "fn");
    push(&mut out, name);
    push(&mut out, param_list);
    if return_type.is_some() {
        push(&mut out, ":");
        if let Some(v) = return_type {
            push(&mut out, v);
        }
    }
    if let Some(v) = cap_annotation {
        push(&mut out, v);
    }
    out
}

/// Render a `ExternTypeTail` node as reparseable text.
pub fn extern_type_tail(name: &str) -> String {
    let mut out = String::new();
    push(&mut out, "type");
    push(&mut out, name);
    out
}

/// Render a `File` node as reparseable text.
pub fn file(items: &[&str]) -> String {
    let mut out = String::new();
    for item in items {
        push(&mut out, item);
    }
    out
}

/// Render a `FnDecl` node as reparseable text.
pub fn fn_decl(name: &str, generic_params: Option<&str>, param_list: &str, return_type: Option<&str>, cap_annotation: Option<&str>, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "fn");
    push(&mut out, name);
    if let Some(v) = generic_params {
        push(&mut out, v);
    }
    push(&mut out, param_list);
    if return_type.is_some() {
        push(&mut out, ":");
        if let Some(v) = return_type {
            push(&mut out, v);
        }
    }
    if let Some(v) = cap_annotation {
        push(&mut out, v);
    }
    push(&mut out, body);
    out
}

/// Render a `FnTypeExpr` node as reparseable text.
pub fn fn_type_expr(params: &[&str], return_type: &str, cap_annotation: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    for (i, item) in params.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    push(&mut out, "->");
    push(&mut out, return_type);
    if let Some(v) = cap_annotation {
        push(&mut out, v);
    }
    out
}

/// Render a `ForceExpr` node as reparseable text.
pub fn force_expr(expr: &str) -> String {
    let mut out = String::new();
    push(&mut out, "force");
    push(&mut out, expr);
    out
}

/// Render a `GenericArgs` node as reparseable text.
pub fn generic_args(args: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "[");
    for (i, item) in args.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, "]");
    out
}

/// Render a `GenericParam` node as reparseable text.
pub fn generic_param(name: &str, constraint: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, name);
    if constraint.is_some() {
        push(&mut out, ":");
        if let Some(v) = constraint {
            push(&mut out, v);
        }
    }
    out
}

/// Render a `GenericParams` node as reparseable text.
pub fn generic_params(params: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "[");
    for (i, item) in params.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, "]");
    out
}

/// Render a `HandleExpr` node as reparseable text.
pub fn handle_expr(cap_name: &str, cap_type: Option<&str>, handler: &str, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "handle");
    push(&mut out, cap_name);
    if cap_type.is_some() {
        push(&mut out, "for");
        if let Some(v) = cap_type {
            push(&mut out, v);
        }
    }
    push(&mut out, "with");
    push(&mut out, handler);
    push(&mut out, "in");
    push(&mut out, body);
    out
}

/// Render a `IdentExpr` node as reparseable text.
pub fn ident_expr(name: &str) -> String {
    let mut out = String::new();
    push(&mut out, name);
    out
}

/// Render a `IdentPattern` node as reparseable text.
pub fn ident_pattern(name: &str, fields: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, name);
    if let Some(v) = fields {
        push(&mut out, v);
    }
    out
}

/// Render a `IfElseExpr` node as reparseable text.
pub fn if_else_expr(condition: &str, then_body: &str, else_clause: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, "if");
    push(&mut out, condition);
    push(&mut out, then_body);
    if else_clause.is_some() {
        push(&mut out, "else");
        if let Some(v) = else_clause {
            push(&mut out, v);
        }
    }
    out
}

/// Render a `ImplAssign` node as reparseable text.
pub fn impl_assign(target: &str) -> String {
    let mut out = String::new();
    push(&mut out, "=");
    push(&mut out, target);
    out
}

/// Render a `ImplCap` node as reparseable text.
pub fn impl_cap(cap: &str) -> String {
    let mut out = String::new();
    push(&mut out, ":");
    push(&mut out, cap);
    out
}

/// Render a `ImplDecl` node as reparseable text.
pub fn impl_decl(generic_params: Option<&str>, head: &str, assign: Option<&str>, cap: Option<&str>, items: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "impl");
    if let Some(v) = generic_params {
        push(&mut out, v);
    }
    push(&mut out, head);
    if let Some(v) = assign {
        push(&mut out, v);
    }
    if let Some(v) = cap {
        push(&mut out, v);
    }
    push(&mut out, "{");
    for item in items {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `ImplItem` node as reparseable text.
pub fn impl_item(body: &str) -> String {
    let mut out = String::new();
    push(&mut out, body);
    out
}

/// Render a `ImplMethod` node as reparseable text.
pub fn impl_method(name: &str, generic_params: Option<&str>, param_list: &str, return_type: Option<&str>, cap_annotation: Option<&str>, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "fn");
    push(&mut out, name);
    if let Some(v) = generic_params {
        push(&mut out, v);
    }
    push(&mut out, param_list);
    if return_type.is_some() {
        push(&mut out, ":");
        if let Some(v) = return_type {
            push(&mut out, v);
        }
    }
    if let Some(v) = cap_annotation {
        push(&mut out, v);
    }
    push(&mut out, body);
    out
}

/// Render a `Item` node as reparseable text.
pub fn item(attrs: &[&str], body: &str) -> String {
    let mut out = String::new();
    for item in attrs {
        push(&mut out, item);
    }
    push(&mut out, body);
    out
}

/// Render a `LambdaExpr` node as reparseable text.
pub fn lambda_expr(param_list: &str, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "fn");
    push(&mut out, param_list);
    push(&mut out, body);
    out
}

/// Render a `LambdaParam` node as reparseable text.
pub fn lambda_param(name: &str, ty: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, name);
    if ty.is_some() {
        push(&mut out, ":");
        if let Some(v) = ty {
            push(&mut out, v);
        }
    }
    out
}

/// Render a `LambdaParamList` node as reparseable text.
pub fn lambda_param_list(params: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    for (i, item) in params.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    out
}

/// Render a `LetStmt` node as reparseable text.
pub fn let_stmt(name: &str, ty: Option<&str>, value: &str) -> String {
    let mut out = String::new();
    push(&mut out, "let");
    push(&mut out, name);
    if ty.is_some() {
        push(&mut out, ":");
        if let Some(v) = ty {
            push(&mut out, v);
        }
    }
    push(&mut out, "=");
    push(&mut out, value);
    push(&mut out, ";");
    out
}

/// Render a `MatchArm` node as reparseable text.
pub fn match_arm(pattern: &str, body: &str) -> String {
    let mut out = String::new();
    push(&mut out, pattern);
    push(&mut out, "=>");
    push(&mut out, body);
    out
}

/// Render a `MatchExpr` node as reparseable text.
pub fn match_expr(scrutinee: &str, arms: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "match");
    push(&mut out, scrutinee);
    push(&mut out, "{");
    for item in arms {
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `MemberName` node as reparseable text.
pub fn member_name(name: &str) -> String {
    let mut out = String::new();
    push(&mut out, name);
    out
}

/// Render a `NamedTypeExpr` node as reparseable text.
pub fn named_type_expr(name: &str, generic_args: Option<&str>, assoc: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, name);
    if let Some(v) = generic_args {
        push(&mut out, v);
    }
    if assoc.is_some() {
        push(&mut out, ".");
        if let Some(v) = assoc {
            push(&mut out, v);
        }
    }
    out
}

/// Render a `NumberExpr` node as reparseable text.
pub fn number_expr(value: &str) -> String {
    let mut out = String::new();
    push(&mut out, value);
    out
}

/// Render a `OperationDecl` node as reparseable text.
pub fn operation_decl(name: &str, generic_params: Option<&str>, param_list: &str, return_type: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, "fn");
    push(&mut out, name);
    if let Some(v) = generic_params {
        push(&mut out, v);
    }
    push(&mut out, param_list);
    if return_type.is_some() {
        push(&mut out, ":");
        if let Some(v) = return_type {
            push(&mut out, v);
        }
    }
    out
}

/// Render a `Param` node as reparseable text.
pub fn param(name: &str, ty: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, name);
    if ty.is_some() {
        push(&mut out, ":");
        if let Some(v) = ty {
            push(&mut out, v);
        }
    }
    out
}

/// Render a `ParamList` node as reparseable text.
pub fn param_list(params: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    for (i, item) in params.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    out
}

/// Render a `ParenExpr` node as reparseable text.
pub fn paren_expr(inner: &str, ty: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    push(&mut out, inner);
    if ty.is_some() {
        push(&mut out, ":");
        if let Some(v) = ty {
            push(&mut out, v);
        }
    }
    push(&mut out, ")");
    out
}

/// Render a `PerformExpr` node as reparseable text.
pub fn perform_expr(name: &str) -> String {
    let mut out = String::new();
    push(&mut out, "perform");
    push(&mut out, name);
    out
}

/// Render a `StringExpr` node as reparseable text.
pub fn string_expr(value: &str) -> String {
    let mut out = String::new();
    push(&mut out, value);
    out
}

/// Render a `ThunkExpr` node as reparseable text.
pub fn thunk_expr(body: &str) -> String {
    let mut out = String::new();
    push(&mut out, "thunk");
    push(&mut out, body);
    out
}

/// Render a `ThunkTypeExpr` node as reparseable text.
pub fn thunk_type_expr(inner: &str) -> String {
    let mut out = String::new();
    push(&mut out, "thunk");
    push(&mut out, inner);
    out
}

/// Render a `UseDecl` node as reparseable text.
pub fn use_decl(path: &str) -> String {
    let mut out = String::new();
    push(&mut out, "use");
    push(&mut out, path);
    push(&mut out, ";");
    out
}

/// Render a `UseNameItem` node as reparseable text.
pub fn use_name_item(name: &str) -> String {
    let mut out = String::new();
    push(&mut out, name);
    out
}

/// Render a `UsePath` node as reparseable text.
pub fn use_path(head: &str, rest: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, head);
    if let Some(v) = rest {
        push(&mut out, v);
    }
    out
}

/// Render a `UsePathBranch` node as reparseable text.
pub fn use_path_branch(next: &str, cont: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, next);
    if let Some(v) = cont {
        push(&mut out, v);
    }
    out
}

/// Render a `UsePathRest` node as reparseable text.
pub fn use_path_rest(item: &str) -> String {
    let mut out = String::new();
    push(&mut out, ".");
    push(&mut out, item);
    out
}

/// Render a `UseTree` node as reparseable text.
pub fn use_tree(names: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "{");
    for (i, item) in names.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, "}");
    out
}

/// Render a `Variant` node as reparseable text.
pub fn variant(attrs: &[&str], name: &str, fields: Option<&str>) -> String {
    let mut out = String::new();
    for item in attrs {
        push(&mut out, item);
    }
    push(&mut out, ".");
    push(&mut out, name);
    if let Some(v) = fields {
        push(&mut out, v);
    }
    out
}

/// Render a `VariantFields` node as reparseable text.
pub fn variant_fields(fields: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    for (i, item) in fields.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    out
}

/// Render a `VariantPattern` node as reparseable text.
pub fn variant_pattern(name: &str, fields: Option<&str>) -> String {
    let mut out = String::new();
    push(&mut out, ".");
    push(&mut out, name);
    if let Some(v) = fields {
        push(&mut out, v);
    }
    out
}

/// Render a `VariantPatternFields` node as reparseable text.
pub fn variant_pattern_fields(fields: &[&str]) -> String {
    let mut out = String::new();
    push(&mut out, "(");
    for (i, item) in fields.iter().enumerate() {
        if i > 0 {
            push(&mut out, ",");
        }
        push(&mut out, item);
    }
    push(&mut out, ")");
    out
}

/// Render a `WildcardPattern` node as reparseable text.
pub fn wildcard_pattern() -> String {
    let mut out = String::new();
    push(&mut out, "_");
    out
}
