// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.

use super::syntax_kind::SyntaxKind;

pub type Token = langue_rt::Token<SyntaxKind>;
pub type SyntaxElement = langue_rt::SyntaxElement<SyntaxKind>;
pub type SyntaxNode = langue_rt::SyntaxNode<SyntaxKind>;
pub type ParseOutput = langue_rt::ParseOutput<SyntaxKind>;
pub use langue_rt::ParseError;
