// Auto-generated by `langc gen`. Do not edit.
// The definition under `lumo/` is the source of truth.

use super::lossless::SyntaxNode;
use super::syntax_kind::SyntaxKind;

/// Byte-exact source reproduction.
pub fn lossless(node: &SyntaxNode) -> String {
    node.text()
}

/// Non-trivia tokens; a space appears iff re-lexing the bare
/// concatenation would merge the neighbors.
pub fn canonical(node: &SyntaxNode) -> String {
    langue_rt::print_canonical(node, super::lexer::lex, SyntaxKind::is_trivia)
}

/// Named-node S-expression (the `:parse` fixture expectation).
pub fn sexpr(node: &SyntaxNode) -> String {
    langue_rt::sexpr(node)
}
