// Auto-generated by langue. Do not edit.
// Regenerate: scripts/gen_langue.sh

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum SyntaxKind {
    // Named tokens
    NUMBER_LIT,
    STRING_LIT,
    IDENT,
    // Trivia
    WHITESPACE,
    NEWLINE,
    UNKNOWN,
    // Keywords
    ALWAYS_KW, // 'always'
    AS_KW, // 'as'
    BUNDLE_KW, // 'bundle'
    CAP_KW, // 'cap'
    CTOR_KW, // 'ctor'
    DATA_KW, // 'data'
    ERROR_KW, // 'error'
    EXTERN_KW, // 'extern'
    FN_KW, // 'fn'
    FORCE_KW, // 'force'
    HANDLE_KW, // 'handle'
    IMPL_KW, // 'impl'
    IN_KW, // 'in'
    INLINE_KW, // 'inline'
    LAMBDA_KW, // 'lambda'
    LET_KW, // 'let'
    MATCH_KW, // 'match'
    PERFORM_KW, // 'perform'
    PRODUCE_KW, // 'produce'
    ROLL_KW, // 'roll'
    THUNK_KW, // 'thunk'
    TYPE_KW, // 'type'
    UNROLL_KW, // 'unroll'
    USE_KW, // 'use'
    WITH_KW, // 'with'
    // Symbols
    HASH, // '#'
    L_PAREN, // '('
    R_PAREN, // ')'
    DOT, // '.'
    SLASH, // '/'
    COLON, // ':'
    COLON_EQ, // ':='
    SEMICOLON, // ';'
    LT, // '<'
    EQUALS, // '='
    FAT_ARROW, // '=>'
    GT, // '>'
    L_BRACKET, // '['
    R_BRACKET, // ']'
    UNDERSCORE, // '_'
    L_BRACE, // '{'
    R_BRACE, // '}'
    // Nodes
    FILE, // File
    EXTERN_TYPE_DECL, // ExternTypeDecl
    EXTERN_FN_DECL, // ExternFnDecl
    EXTERN_AS, // ExternAs
    INLINE_HINT, // InlineHint
    DATA_DECL, // DataDecl
    VARIANT, // Variant
    VARIANT_FIELDS, // VariantFields
    CAP_DECL, // CapDecl
    OPERATION_DECL, // OperationDecl
    FN_DECL, // FnDecl
    USE_DECL, // UseDecl
    USE_PATH, // UsePath
    USE_TREE, // UseTree
    IMPL_DECL, // ImplDecl
    IMPL_NAME, // ImplName
    IMPL_CAP, // ImplCap
    IMPL_METHOD, // ImplMethod
    GENERIC_PARAMS, // GenericParams
    PARAM_LIST, // ParamList
    PARAM, // Param
    RETURN_ANN, // ReturnAnn
    CAP_ANNOTATION, // CapAnnotation
    TYPE_EXPR, // TypeExpr
    GENERIC_ARGS, // GenericArgs
    IDENT_EXPR, // IdentExpr
    STRING_EXPR, // StringExpr
    NUMBER_EXPR, // NumberExpr
    CTOR_EXPR, // CtorExpr
    CTOR_ARGS, // CtorArgs
    THUNK_EXPR, // ThunkExpr
    ROLL_EXPR, // RollExpr
    PRODUCE_EXPR, // ProduceExpr
    FORCE_EXPR, // ForceExpr
    LAMBDA_EXPR, // LambdaExpr
    APPLY_EXPR, // ApplyExpr
    LET_EXPR, // LetExpr
    MATCH_EXPR, // MatchExpr
    MATCH_ARM, // MatchArm
    UNROLL_EXPR, // UnrollExpr
    PERFORM_EXPR, // PerformExpr
    HANDLE_EXPR, // HandleExpr
    BUNDLE_EXPR, // BundleExpr
    BUNDLE_ENTRY, // BundleEntry
    MEMBER_EXPR, // MemberExpr
    ANN_EXPR, // AnnExpr
    ERROR_EXPR, // ErrorExpr
    VARIANT_PATTERN, // VariantPattern
    BIND_PATTERN, // BindPattern
    WILDCARD_PATTERN, // WildcardPattern
    // Sentinel
    ERROR,
}

impl SyntaxKind {
    pub fn is_trivia(self) -> bool {
        matches!(self, Self::WHITESPACE | Self::NEWLINE)
    }

    pub fn from_keyword(text: &str) -> Option<Self> {
        match text {
            "always" => Some(Self::ALWAYS_KW),
            "as" => Some(Self::AS_KW),
            "bundle" => Some(Self::BUNDLE_KW),
            "cap" => Some(Self::CAP_KW),
            "ctor" => Some(Self::CTOR_KW),
            "data" => Some(Self::DATA_KW),
            "error" => Some(Self::ERROR_KW),
            "extern" => Some(Self::EXTERN_KW),
            "fn" => Some(Self::FN_KW),
            "force" => Some(Self::FORCE_KW),
            "handle" => Some(Self::HANDLE_KW),
            "impl" => Some(Self::IMPL_KW),
            "in" => Some(Self::IN_KW),
            "inline" => Some(Self::INLINE_KW),
            "lambda" => Some(Self::LAMBDA_KW),
            "let" => Some(Self::LET_KW),
            "match" => Some(Self::MATCH_KW),
            "perform" => Some(Self::PERFORM_KW),
            "produce" => Some(Self::PRODUCE_KW),
            "roll" => Some(Self::ROLL_KW),
            "thunk" => Some(Self::THUNK_KW),
            "type" => Some(Self::TYPE_KW),
            "unroll" => Some(Self::UNROLL_KW),
            "use" => Some(Self::USE_KW),
            "with" => Some(Self::WITH_KW),
            _ => None,
        }
    }

    pub fn from_symbol(text: &str) -> Option<Self> {
        match text {
            "#" => Some(Self::HASH),
            "(" => Some(Self::L_PAREN),
            ")" => Some(Self::R_PAREN),
            "." => Some(Self::DOT),
            "/" => Some(Self::SLASH),
            ":" => Some(Self::COLON),
            ":=" => Some(Self::COLON_EQ),
            ";" => Some(Self::SEMICOLON),
            "<" => Some(Self::LT),
            "=" => Some(Self::EQUALS),
            "=>" => Some(Self::FAT_ARROW),
            ">" => Some(Self::GT),
            "[" => Some(Self::L_BRACKET),
            "]" => Some(Self::R_BRACKET),
            "_" => Some(Self::UNDERSCORE),
            "{" => Some(Self::L_BRACE),
            "}" => Some(Self::R_BRACE),
            _ => None,
        }
    }
}
