[package]
name = "lumoc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
ron = "0.10.1"
eyre.workspace = true

liblumoc.workspace = true
lumo-syntax.workspace = true

annotate-snippets = "0.11.5"
