export const TokenKind = Object.freeze({
  SpaceHorizotanl: 'SpaceHorizontanl',
  SpaceVertical: 'SpaceVertical',

  Identifier: 'Identifier',
  KeywordEnum: 'KeywordEnum',
  KeywordMut: 'KeywordMut',
  KeywordStruct: 'KeywordStruct',

  PunctuationExclamationMark: 'PunctuationExclamationMark',
  PunctuationNumberSign: 'PunctuationNumberSign',
  PunctuationDollarSign: 'PunctuationDollarSign',
  PunctuationPercentSign: 'PunctuationPercentSign',
  PunctuationAmpersand: 'PunctuationAmpersand',
  PunctuationAsterisk: 'PunctuationAsterisk',
  PunctuationPlusSign: 'PunctuationPlusSign',
  PunctuationComma: 'PunctuationComma',
  PunctuationHyphenMinus: 'PunctuationHyphenMinus',
  PunctuationFullStop: 'PunctuationFullStop',
  PunctuationSolidus: 'PunctuationSolidus',
  PunctuationColon: 'PunctuationColon',
  PunctuationSemicolon: 'PunctuationSemicolon',
  PunctuationLessThanSign: 'PunctuationLessThanSign',
  PunctuationEqualsSign: 'PunctuationEqualsSign',
  PunctuationGreaterThanSign: 'PunctuationGreaterThanSign',
  PunctuationQuestionMark: 'PunctuationQuestionMark',
  PunctuationCommercialAt: 'PunctuationCommercialAt',
  PunctuationReverseSolidus: 'PunctuationReverseSolidus',
  PunctuationCircumflexAccent: 'PunctuationCircumflexAccent',
  PunctuationVerticalLine: 'PunctuationVerticalLine',
  PunctuationTilde: 'PunctuationTilde',
  PunctuationLeftParenthesis: 'PunctuationLeftParenthesis',
  PunctuationLeftSquareBracket: 'PunctuationLeftSquareBracket',
  PunctuationLeftCurlyBracket: 'PunctuationLeftCurlyBracket',
  PunctuationRightParenthesis: 'PunctuationRightParenthesis',
  PunctuationRightSquareBracket: 'PunctuationRightSquareBracket',
  PunctuationRightCurlyBracket: 'PunctuationRightCurlyBracket',
});
export type TokenKind = (typeof TokenKind)[keyof typeof TokenKind];
